google/cadvisor

container/raw/handler.go, utils/sysfs/fakesysfs/fake.go, utils/sysfs/sysfs.go, utils/sysinfo/sysinfo.go, utils/sysinfo/sysinfo_test.go
Provides machine-level networking stats.
=> Add network stats to root container.

healthz/healthz.go, integration/framework/framework.go, integration/tests/api/docker_test.go, integration/tests/api/machine_test.go, integration/tests/api/test_utils.go, integration/tests/healthz/healthz_test.go, storage/memory/stats_buffer.go, storage/memory/stats_buffer_test.go
We'll add a travis rule when this is in.
=> Add missing copyright notices.

utils/percentiles.go, utils/percentiles_test.go
This is copied verbatim for our older prototype. We'll use it as
a starting point for building stats summary.
=> Add percentiles utility methods.

container/raw/container_hints_test.go, fs/fs.go, fs/fs_test.go, fs/types.go, hooks/boilerplate.go.txt, hooks/check_boilerplate.sh, pages/docker.go, pages/pages.go
=> Add some more missing copyrights and script to verify copyright.

docs/running.md
=> Adding documentation for enabling memory cgroup in Debian.

validate/validate.go
Sample output:
Block device setup: [Supported and recommended]
Atleast one device supports 'cfq' I/O scheduler. Some disk stats can be reported.
Disk "dm-1" Scheduler type "none".
Disk "sda" Scheduler type "cfq".
Disk "dm-0" Scheduler type "none".
=> Add I/O scheduler information to validator.

manager/container.go, manager/manager.go, utils/cpuload/cpuload.go, utils/cpuload/netlink/conn.go, utils/cpuload/netlink/defs.go, utils/cpuload/netlink/example/example.go, utils/cpuload/netlink/netlink.go, utils/cpuload/netlink/reader.go
This allows us to plug in a scheddebug based interface.
=> Refactor netlink implementation.

docs/api.md, docs/clients.md
A few links were broken... no longer.
=> docs: broken relative link fixes

integration/tests/api/test_utils.go
This should be a sane default.
=> Expect user + cpu to be within 500ms of total.

info/container.go, integration/tests/api/test_utils.go, manager/container.go, storage/memory/stats_buffer_test.go
Load is now LoadAverage. Also added comments about smoothing interval.
=> Rename load to load average.

utils/cpuload/scheddebug/scheddebug.go
. Remove counting of taskgroups from scheddebug.
. Move monitoring thread 500ms ahead of other containers housekeeping.
. Rely on /proc/loadavg for root load.
. Cover up for scheddebug atomicity issues (WIP)
. Remove counting of monitoring thread.
Getting better, but still a bit farther away from ideal load :(
=> Set of fixes for cpuload calculations.

info/machine.go
We already added memory hierarchy.
=> Remove stale comments.

api/handler.go, api/versions.go
This should make it easier to add future API versions and makes it a bit
simpler to look through the API.
=> Refactoring API version handling.

utils/sysfs/sysfs.go
=> Filter out non-netdev entries in sysfs/class/net

integration/runner/run.sh, integration/runner/runner.go
pkill is available on more systems.
=> Use pkill instead of killall.

events/handler.go, events/handler_test.go
Adding preliminary events handler
=> Basic event handler to monitor events as they occur and grab events that have already happened

storage/memory/stats_buffer.go, storage/memory/stats_buffer_test.go
This will allow us to accept queries over a narrower window of time.
=> Add InTimeRange() to StatsBuffer.

integration/framework/framework.go, integration/tests/healthz/healthz_test.go
Also rename Host() to Hostname().
=> Add ShellActions to integration test Framework.

container/docker/handler.go, container/raw/handler.go, utils/utils.go
=> Fix cpuset returned in spec on a single core machine.

events/handler.go
Made changes to events library to make it thread safe.
=> Events branch

manager/manager.go
=> Don't fail startup if OOM watching failed.

info/container.go, manager/container.go
=> Sort subcontainers in ContainerSpec.

summary/summary.go
Use timestamps instead of sample counts for generating summary.
=> Handle dynamic housekeeping in derived stats.

validate/validate.go
We still report 'Supported and Recommended' even if hierarchical accounting is disabled.
Most current distros don't enable it by default.
=> Report status of hierarchical memory accounting in validate output.

info/v1/container.go, metrics/prometheus.go
I also plan on following this up with a larger refactoring of the Prometheus metrics part, as well as adding tests to that.
=> Fix Prometheus metrics and typo in container info stats

api/versions.go
Next: Apply similar handling to spec and summary endpoints.
=> Add handling of docker container to 2.0 stats API.

api/versions.go, info/v2/machine.go
Only difference from v1 /machine is that both h/w and s/w states are included.
=> Add /machine endpoint for 2.0

deploy/Dockerfile
=> Switch to gliderlabs/alpine Docker image.

deploy/Dockerfile
Alpine doesn't have glibc which we build with.
Fixes #601
=> Revert back to progrium/busybox.

container/docker/factory.go
OpenShift has some cAdvisor packages in its import chain. The init() here
invokes Dbus start even when cAdvisor is not actively running or being
used (in our packages).  This change makes the systemd check and dbus
initialization and connection lazy, occuring only the first time someone
invokes UseSystemd().
Seemed like the simplest possible tweak.
=> Lazily init DBus only when it is needed

events/handler.go, events/handler_test.go
Ordered structs around a bit and updated comments.
=> Readability changes for events.

client/README.md, client/v2/README.md, client/v2/client.go, client/v2/client_test.go
I'll probably move the existing API down to a v1 directory next.
=> Add a v2 client library, starting with machine information.

http/handlers.go
=> Return error if can't register digest handler

client/client.go, client/clientexample/main.go, integration/framework/framework.go, integration/tests/api/event_test.go
These integration tests don't work yet but this is the basic setup.  One main issue is that I cannot oom kill the docker containers in a reasonable timeframe.
=> Preliminary integration tests for getting events

api/handler.go, api/versions.go, client/client.go, container/factory.go, events/handler.go, manager/container.go, manager/manager.go, pages/containers.go, pages/docker.go, summary/percentiles.go, utils/cpuload/netlink/reader.go, utils/oomparser/oomparser.go
Reduce common logging using Kubernetes logging standards.
=> Lowering log levels.

manager/manager.go
=> Make cpu load reader flag controlled.

CHANGELOG.md, version/version.go
Please do not merge before the other PR. Will try to get this out today.
=> cAdvisor 0.12.0

events/handler.go, events/handler_test.go
Queries for root were not being correctly diagnosed.
=> Fix subcontainer queries in subcontainers.

integration/tests/api/event_test.go
=> Eliminate race in integration test

utils/oomparser/oomparser.go
This file is present in most distros and provides most of the logs we're
looking for. We support the others if this one is not available.
=> Add /var/log/kern.log to kernel log files.

events/handler.go, events/handler_test.go, manager/manager.go
There is a TODO to make this configurable.
=> Limit the number of events stored to 24h.

container/libcontainer/helpers.go, events/handler.go, events/handler_test.go, manager/manager.go
=> Add flags for event storage limits

CHANGELOG.md, version/version.go
=> cAdvisor 0.13.0

collector/collector_manager.go, collector/collector_manager_test.go, collector/fakes.go, collector/types.go, manager/container.go, manager/container_test.go, manager/manager.go, manager/manager_test.go
=> Add Collector executor support

pages/containers.go, pages/containers_html.go, pages/pages.go, pages/static/containers_js.go
=> Revert "Make all links relative."

pages/containers.go, pages/containers_html.go, pages/docker.go, pages/pages.go, pages/static/containers_js.go
Added missing docker page handling.
=> Make all link relative - part 2.

manager/container.go, manager/manager.go, utils/oomparser/oomparser.go
=> Lower logging level of some common logs.

integration/common/gce.go, integration/framework/framework.go, integration/runner/runner.go
Working, will ping when ready.
=> Replace gcutil with gcloud usage

docs/running.md
Fixes #379
/cc @vishh @rjnagal
=> Document that cAdvisor needs --privilege in RHEL/CentOS

container/libcontainer/helpers.go
=> Fix WorkingSet calculation

collector/collector_manager.go, collector/collector_manager_test.go, collector/fakes.go, collector/types.go, info/v2/metric.go, manager/container.go
@rjnagal we can start with this and iterate forward.
=> Add basic metric structures

api/versions.go, container/docker/handler.go, container/libcontainer/helpers.go, container/raw/handler.go, info/v2/container.go, manager/container.go, manager/manager.go, manager/manager_mock.go
I need the ps/top output for the UI. Not sure if we should be adding it as an API. WDYT?
Also check the fields that I selected to show. Do we have any issues showing the full command. My guess is that we don't care.
=> Add an api to support ps/top.

container/docker/handler.go, manager/manager.go, manager/manager_mock.go
This is only meant to populate /docker UI page.
=> Add manager methods to get docker status and images.

Godeps/Godeps.json, Godeps/_workspace/src/github.com/garyburd/redigo/internal/commandinfo.go, Godeps/_workspace/src/github.com/garyburd/redigo/internal/redistest/testdb.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/conn.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/conn_test.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/doc.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/log.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/pool.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/pool_test.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/pubsub.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/pubsub_test.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/redis.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/reply.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/reply_test.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/scan.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/scan_test.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/script.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/script_test.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/test_test.go, Godeps/_workspace/src/github.com/garyburd/redigo/redis/zpop_example_test.go, storage/redis/redis.go, storagedriver.go
provide redis driver for cAdvisor's storage
=> Add the support for redis in cAdvisor's storage

manager/manager.go
This will allow for delayed registration for client users (e.g.: Kubelet).
/cc @rjnagal @dchen1107
=> Register factories in Start() instead of New().

info/v2/container.go, manager/container.go, pages/static/containers_js.go
Use pretty prints, but maintain sorting capabilities.
=> Improve process table output.

pages/containers_html.go, pages/docker.go, pages/pages.go, pages/static/containers_css.go, pages/static/containers_js.go
Added the basics. Still needs better styling. But its good enough to go.
=> Add docker status and images info to /docker page.

integration/runner/run.sh
These are now in the Jenkins config.
This is also the first PR where Jenkins will run the CI component as well.
=> Remove Jenkins env setup

container/raw/handler.go, container/raw/inotify_watcher.go
=> Report the last cgroup destroy event.

CHANGELOG.md, version/version.go
Should wait for #726 to be merged.
/cc @rjnagal
=> cAdvisor 0.14.0

container/docker/factory.go, container/factory.go, container/factory_test.go, container/raw/factory.go, container/raw/handler.go, manager/manager.go, validate/validate.go
First customer: inotify watches
/cc @rjnagal
=> Add debug info to /validate

manager/manager.go
=> Add managed containers to debug output

pages/static/containers_js.go
=> Change Cgroup to Container in ps output.

utils/sysfs/sysfs.go
This patch adds requisite support to retrieve system uuid details for Power
systems. Power systems do not have DMI data. However most of the relevant details
are either in /proc or /sys. For baremetal servers, the UID is available in
/proc/device-tree/system-id. For guests the UUID is available in
/proc/device-tree/vm,uuid inside the guest. Guest's /proc filesystem do not have
/proc/device-tree/system-id
Example
On baremetal system
$cat /proc/device-tree/system-id
2122AAA
On a guest VM
$cat /proc/device-tree/vm,uuid
4b1a1a7e-079e-479c-8072-d8108f31050c
Signed-off-by: Pradipta Kr. Banerjee <bpradip@in.ibm.com>
=> Handle system UUID retrieval for Power(ppc64) Systems

manager/container.go, manager/manager.go
Use /rootfs/proc to build the process listing.
=> Make process listing work when cadvisor is running in docker.

README.md, docs/running.md
=> Minor organization update in running doc

docs/running.md
@rjnagal sorry I thought I had put this into the last one.
=> Mention Fedora

api/versions.go, container/docker/handler.go, container/libcontainer/helpers.go, info/v1/container.go, info/v2/container.go, metrics/prometheus_test.go, utils/sysinfo/sysinfo.go, utils/sysinfo/sysinfo_test.go
=> Expose multiple network interfaces in API.

container/raw/handler.go, pages/containers_html.go, pages/static/containers_js.go
=> Show multiple network interfaces in UI

pages/static/containers_js.go
This makes the switch more responsive.
/cc @rjnagal
=> Refresh network stats on interface change

CHANGELOG.md, version/version.go
=> cAdvisor 0.15.0

pages/static/static.go
=> Set Content-Type on static files.

cache/cache.go, cache/memory/memory.go, manager/container.go
=> Remove stats from cache when container is destroyed

CHANGELOG.md, version/version.go
=> cAdvisor 0.15.1

container/docker/handler.go, integration/tests/api/docker_test.go
=> Fix mirrored network stats

pages/containers.go, pages/docker.go, pages/pages.go
=> Escape container names.

deploy/build.sh, deploy/canary/Dockerfile
Much credit to @afein 
/cc @rjnagal
=> Add a self-built canary cAdvisor.

docs/running.md
=> Add cAdvisor canary image to running docs

info/v1/machine.go, info/v2/machine.go, manager/machine.go, utils/cloudinfo/cloudinfo.go, utils/cloudinfo/gce.go
Started implementing the cloudinfo package. This is my first time writing production Go code, so I'm sending a short (50 line) diff for feedback. Thanks!
=> Create package cloudinfo

CHANGELOG.md, version/version.go
=> cAdvisor 0.16.0

collector/config.go, collector/config/sample_config.json, collector/generic_collector.go, collector/generic_collector_test.go
Create a config : Includes endpoint and metrics metadata
Extract config information
Create nginx collector using the config
=> Collector Config

.travis.yml
/cc @rjnagal lets see if this works.
=> Make Travis use their new infra.

collector/generic_collector.go
Calculation of minimum polling frequency and check for validity of regular expressions of all metrics of a collector has been done during initialization of the collector.
=> Modification in Collect() method of GenericCollector

api/versions.go, info/v1/container.go, info/v2/container.go
API changes for v2.0 : Add endpoint appmetrics
=> API changes for custom metrics

pages/containers.go, pages/containers_html.go, pages/docker.go, pages/pages.go, pages/static/containers_js.go
The function startCustomMetrics is called once to setup the custom graphs depending on the number of custom metrics.
The function drawCustomMetrics is called periodically to draw all the graphs of custom metrics.
=> UI changes to display custom metrics

api/versions.go, collector/collector_manager.go, collector/collector_manager_test.go, collector/fakes.go, collector/generic_collector.go, collector/generic_collector_test.go, collector/types.go, info/v1/container.go, info/v1/metric.go, info/v2/container.go, manager/container.go, pages/static/containers_js.go
These are the changes that need to be done before we add a prometheus collector.
=> Modify generic collector

storage/stdout/stdout.go, storagedriver.go
Resolving branch and commit issues made. This PR is originally from PR #849
=> Stdout storage

pages/static/containers_js.go
This displays custom metrics on the UI. Each metric has a drop-down list of all labels associated with it.
@rjnagal , @vmarmol
=> UI changes

Godeps/Godeps.json, Godeps/_workspace/src/github.com/vishvananda/netns/LICENSE, Godeps/_workspace/src/github.com/vishvananda/netns/README.md, Godeps/_workspace/src/github.com/vishvananda/netns/netns.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_386.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_amd64.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_arm.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_arm64.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_ppc64le.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_s390x.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_test.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_unspecified.go, container/docker/handler.go, container/libcontainer/helpers.go, container/raw/handler.go
=> Get network stats by switching network namespace on newer Docker versions.

metrics/prometheus.go, metrics/prometheus_test.go, metrics/testdata/prometheus_metrics
=> Expose all interfaces in Prometheus metrics.

container/docker/handler.go, metrics/prometheus.go, metrics/prometheus_test.go, metrics/testdata/prometheus_metrics
* Only add container name & image for docker containers
* Add container start time
* Add container cpu & memory specs
* Add version info metrics
@juliusv @discordianfish Looking at git logs I guess you might be users of this so might want to take a look?
Thinking of adding in machine info too.
=> Prometheus metrics improvements

docs/application_metrics.md
Not linked off from the main page yet. Needs few more tweaks, links, and
sample images.
=> Initial skeleton for application metrics docs.

storage/elasticsearch/elasticsearch.go, storagedriver.go
* fix #881 
* Add support for ElasticSearch heath check and find all nodes of cluster
* Rename command-line flag about ElasticSearch
=> Fix problem about ElasticSearch container

container/libcontainer/helpers.go, info/v1/container.go, info/v2/container.go
first working prototype for #889 , atm only workt for v1 api please review
=> add tcp/tcp6 statistics

docs/runtime_options.md
=> Fix typo in document

info/v1/container.go
=> Fix typo in comment

container/docker/fsHandler.go, container/docker/handler.go
`du` can cause a lot of cpu usage.
#898
=> Compute fs usage for docker containers less often.

container/docker/factory.go, container/docker/handler.go, deploy/Dockerfile, deploy/canary/Dockerfile, fs/fs.go, manager/manager.go
Fixes #920
This currently only implements docker storage dir usage & not container FS usage.
=> Support devicemapper storage for docker images dir

container/libcontainer/helpers.go
=> Disable tcp stats collection

container/libcontainer/helpers.go, container/libcontainer/helpers_test.go, container/libcontainer/testdata/procnetdev
Reported in kubernetes/kubernetes#16296
/cc @vishh @yujuhong
=> Drop regexp for net stats parsing

deploy/canary/Dockerfile
=> Fix canary docker image.

api/handler.go, cadvisor.go, container/docker/handler.go, container/raw/handler.go, healthz/healthz.go, http/handlers.go, pages/pages.go
I mess things up when solve conflict after rebase this PR https://github.com/google/cadvisor/pull/934, and can not reopen the existing one, so I close it and recommit here.
=> Fix imported package names to not use mixedCaps or under_scores

container/docker/handler.go
Signed-off-by: Vishnu Kannan <vishnuk@google.com>
cc @yujuhong
=> Include log usage for aufs driver.

container/docker/factory.go
Setting this flag to true, forces cAdvisor to not assume systemd to be the cgroups owner for docker containers.
#947
=> Add a `--nosystemd` flag 

README.md
=> Add Slack references to README

fs/fs.go, fs/fs_test.go
See kubernetes/kubernetes#17725 for more details.
/cc @vishh
=> Fix Devicemapper output parsing

container/libcontainer/helpers.go
This reduces CPU usage (fmt.*scanf are real hogs & I've learned should be avoided when you can).
=> Improve perf of interface stats parsing

container/docker/factory.go, container/docker/handler.go, fs/fs.go
=> Add support for Overlayfs.

client/README.md
Now the links go into the right place (:
=> Updated links in Client README.md

client/README.md
I should have done it in the previous PR
=> Modified links to the right lines

manager/container.go
Defer calculation of `loadDecay`. Flags must be parsed before they can
be read, and therefore cannot be reliably be read at package init time.
=> Fix usage of housekeeping_interval flag

container/container.go, container/docker/handler.go, container/mock.go, container/raw/handler.go, manager/container.go
=> Fix goroutine leak in docker fs handler logic.

build/boilerplate/boilerplate.go.txt, build/boilerplate/boilerplate.py, build/boilerplate/boilerplate.py.txt, build/boilerplate/boilerplate.sh.txt, build/build.sh, build/check_gofmt.sh, build/release.sh, deploy/build.sh
Copied the kubernetes boilerplate checker from
https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate,
and updated templates for cAdvisor.
=> Fix check_boilerplate.sh for 2016

container/libcontainer/helpers.go, info/v1/container.go, info/v1/test/datagen.go, metrics/prometheus.go, metrics/prometheus_test.go, metrics/testdata/prometheus_metrics
Fixes #975. This PR supersedes #1036.
=> Expose rss and cache via API and /metrics

info/v2/conversion.go, info/v2/conversion_test.go
Fix for https://github.com/google/cadvisor/issues/1060
=> Fix v2 stats conversion NPD & add test

container/docker/handler.go
Fixes #1076 
@damianopezzotti This should fix your issue - works for me. If you can test that would be great but I can't see any problems with this approach.
/cc @vishh @pwittrock
=> Fix up networking stats for new docker network functionality

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/README.md, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/container.go, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/container_linux.go, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/generic_error.go, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/init_linux.go, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/process_linux.go, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/state_linux.go, Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/utils/utils.go
runc was retagged at 0.0.7 - this uses the correct tag.
Also contains some fixes between the 2 0.0.7 tags - this was messy!
=> bump(github.com/opencontainers/runc/libcontainer)

integration/runner/runner.go
=> Fix integration test runner.

container/docker/factory.go, container/docker/handler.go
=> Use storage dir from docker info for filesystem usage tracking.

container/docker/factory.go, validate/validate.go
@vishh @pwittrock Please review when you get a chance.
=> Remove systemd docker container name check

build/integration.sh, build/jenkins_e2e.sh
The script should make updates to the test infra explicit.
=> Adding a script that will run e2e tests on our jenkins builder.

container/docker/fsHandler.go, container/docker/handler.go, container/raw/handler.go, fs/fs.go, fs/fs_test.go, fs/types.go, integration/runner/runner.go, integration/tests/api/docker_test.go
=> Timeout `du` after a minute.

container/docker/fsHandler.go, fs/fs.go
=> Ignore empty strings paths while calculting disk usage.

container/docker/handler.go, container/raw/handler.go, fs/fs.go, fs/types.go, info/v1/container.go, info/v1/machine.go, info/v2/conversion.go, info/v2/conversion_test.go, info/v2/machine.go, integration/tests/api/docker_test.go, integration/tests/api/machine_test.go, integration/tests/api/machinestats_test.go, manager/machine.go
=> Adding support for inodes.

container/docker/factory.go, container/docker/handler.go, container/factory.go, container/libcontainer/helpers.go, container/raw/factory.go, container/raw/handler.go, integration/tests/api/docker_test.go, manager/manager.go, manager/manager_test.go
This patch should let users disable disk and network metrics aggregation if required.
=> Support opt out for metrics.

build/build.sh
=> fix build for rhel7, go 1.4

container/docker/handler.go
=> nil pointer check

integration/framework/framework.go, integration/tests/api/docker_test.go
=> Fix test commands that are currently failing over ssh.

container/docker/handler.go
=> Set spec.hasFilesystem to true by default for docker containers.

integration/tests/api/docker_test.go
=> skip TestDockerFilesystemStats for devicemapper

info/v1/machine.go, utils/cloudinfo/aws.go, utils/cloudinfo/cloudinfo.go
=> PR #1152 cherrypick

fs/fs.go, fs/fs_test.go
My specific use-case is running the kubelet in a rkt container, where / will be overlayfs.
/cc @sjpotter @vishh
=> Evaluate labels from all mount points (rather than just "supported" fs)

integration/runner/runner.go
=> Remove test args from the runner since it is not needed/used.

cadvisor.go, container/libcontainer/helpers.go, container/raw/handler.go
cc @ncdc @sjenning @derekwaynecarr
=> Avoid collecting network stats for non root cgroups in raw handler.

cadvisor.go, cadvisor_test.go, container/libcontainer/helpers.go, container/raw/handler.go, integration/runner/runner.go, manager/manager.go, manager/manager_test.go
cc @timstclair @ncdc @derekwaynecarr
=> Cherry pick #1159 and #1158

cadvisor.go, cadvisor_test.go
=> Fix --disable_metrics parsing to accept empty string as input.

build/integration.sh
- Poll localhost:8080/healthz to wait for cAdvisor to start
- Set the script exit code to the test exit status
- Fix bash formatting
- Check for sudo access at the start
/cc @vishh
=> Improve local cAdvisor integration test script

container/libcontainer/compatibility.go
Fixes https://github.com/google/cadvisor/issues/1206
/cc @yujuhong
=> Look for container state in containerd path

Godeps/Godeps.json, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/.travis.yml, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/AUTHORS, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/Makefile, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/README.markdown, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/auth.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/container.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/image.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/network.go, Godeps/_workspace/src/github.com/fsouza/go-dockerclient/volume.go
Needed to pull in graphdriver support
@vishh @sjenning
=> Bump godep for go-dockerclient

container/common/helpers.go, container/raw/handler.go, container/rkt/factory.go, container/rkt/handler.go
playing nice means not elliding the system.slice cgroup but allowing the raw handler to handle it
=> move ListContainers code to common and make rkt play nice

events/handler.go
For https://github.com/kubernetes/kubernetes/issues/24698
=> Don't create a EventStore if the event limit is set to 0

container/docker/client.go, container/docker/factory.go, container/libcontainer/helpers.go, validate/validate.go
- Don't validate docker state file, since it's no longer used
- Clean up docker root dir
=> Docker state cleanup

container/docker/factory.go, container/docker/handler.go, devicemapper/dmsetup_client.go, devicemapper/doc.go, devicemapper/fake/dmsetup_client_fake.go, devicemapper/fake/thin_ls_client_fake.go, devicemapper/thin_ls_client.go, devicemapper/thin_ls_client_test.go, devicemapper/thin_pool_watcher.go, devicemapper/thin_pool_watcher_test.go, fs/fs.go, fs/fs_test.go, integration/tests/api/docker_test.go, utils/docker/docker.go
=> devicemapper thin_ls support

utils/tail/tail.go
Follow up from https://github.com/google/cadvisor/pull/1264, taking over to unblock v0.23.2 for kubernetes 1.3
/cc @sjenning
=> Cleanup tail util from #1264

utils/tail/tail.go
IN_ATTRIB inotify events are generated when atime / mtime is changed,
which would cause the tail to be reset, and reread the same log
again (generating duplicate events). Instead, watch the directory for
file delete / move.
Also, use an exponential backoff when retrying opening the file.
/cc @sjenning
=> Fixes for log tailing

fs/fs.go
I picked the number `20` pretty arbitrarily. LMK if you prefer a different number, or have a suggestion for choosing in a scientific manner (e.g. roll 4 d20s).
Fixes https://github.com/google/cadvisor/issues/1300
Also noteworthy, this causes cAdvisor to startup much faster, and not crash docker if there are already 500 containers running.
=> Cap the maximum consecutive du commands

collector/prometheus_collector.go, collector/prometheus_collector_test.go, fs/fs.go
https://github.com/google/cadvisor/pull/1303
https://github.com/google/cadvisor/pull/1318
=> Cherry picks for Kubernetes 1.3

container/docker/factory.go, devicemapper/dmsetup_client.go, devicemapper/fake/dmsetup_client_fake.go, devicemapper/fake/thin_ls_client_fake.go, devicemapper/thin_ls_client.go, devicemapper/thin_pool_watcher.go, devicemapper/util.go
=> Check for thin_ls binary in path when using ThinPoolWatcher

container/docker/factory.go, utils/docker/docker.go
Cherry pick the DM fixes so we can get them into kube 1.3
@vishh @ncdc
=> v0.23: cherry pick dm fixes

Godeps/Godeps.json, Godeps/_workspace/src/golang.org/x/exp/inotify/inotify_linux.go
Picking up a fix I made in https://go-review.googlesource.com/#/c/24289/
#1339
=> Updating inotify to fix memory leak

Godeps/Godeps.json, Godeps/_workspace/src/golang.org/x/exp/inotify/inotify_linux.go
Cherry-pick of https://github.com/google/cadvisor/pull/1346
=> Updating inotify to fix memory leak v0.23 cherrypick

build/jenkins_e2e.sh, integration/runner/runner.go
Injected a race into cadvisor.go and verified this caught it. Also, fix
the runner to grab the logs even when the tests don't complete.
=> Detect race conditions in jenkins integration tests

utils/cloudinfo/gce.go
Fixes https://github.com/google/cadvisor/issues/1273
=> cloudinfo: identify gce from file

docs/runtime_options.md
fix broken link to influxdb.md
=> fix broken link

build/jenkins_e2e.sh
=> Cherry pick #1357

container/libcontainer/helpers.go
=> Cherry pick for Modify working set memory stats calculation

manager/watcher/raw/raw.go
Address the `TODO` in `manager/watcher/raw/raw.go`.
```
TODO(vmarmol): We don't have to fail here, maybe we can recover and try to get as many registrations as we can.
```
Many reasons could cause `watch` to fail, such as file permission issue, file removed before watching etc.
In the original code, once a `watch` operation failed, the error will be returned through the recursive call stack and finally cause cadvsior start failure, which causes issues like https://github.com/kubernetes/kubernetes/issues/28997.
As the `TODO` said, we should keep on watching other subdirectories when error happens.
@vishh @timstclair
=> Continue watching other sub directories when there is watch error.

Godeps/Godeps.json, vendor/github.com/coreos/go-systemd/dbus/dbus.go, vendor/github.com/coreos/go-systemd/dbus/methods.go, vendor/github.com/coreos/go-systemd/util/util.go, vendor/github.com/coreos/pkg/LICENSE, vendor/github.com/coreos/pkg/NOTICE, vendor/github.com/coreos/pkg/dlopen/dlopen.go, vendor/github.com/coreos/pkg/dlopen/dlopen_example.go
@vishh 
Bump up go-systemd to 4484981625c1a6a2ecb40a390fcb6a9bcfee76e3 to sync with kubernetes.
=> Bump up go-systemd to 4484981625c1a6a2ecb40a390fcb6a9bcfee76e3.

container/docker/handler.go, devicemapper/thin_pool_watcher.go
=> Make ThinPoolWatcher loglevel consistent

container/raw/handler.go, fs/fs.go, fs/types.go, info/v1/container.go, info/v1/machine.go, info/v2/container.go, info/v2/conversion.go, machine/info.go, manager/manager.go
Fixes https://github.com/google/cadvisor/issues/1366
/cc @ncdc @vishh @ronnielai @timstclair
=> Allow clients to know if inodes data is available

storage/statsd/statsd.go
Added CPU user, system stats as well as the load average stat.
=> Added CPU Usage details to statsd

deploy/Dockerfile
- Update base image to alpine:3.4
- Fix zfs-utils reference (moved to zfs in main)
- Update glibc version to 2.23-r3
Fixes https://github.com/google/cadvisor/issues/1326
=> Update Dockerfile and dependencies

fs/fs.go, fs/fs_test.go, info/v2/conversion.go
Cherry picks of #1358 #1395 to release-v0.23
PTAL @vishh @timstclair @derekwaynecarr
=> Cherry picks of #1358 #1395 to release-v0.23

container/common/helpers.go
I was using cadvisor package in my project and found memory reservation is missing.
=> GetSpec missing memory reservation

http/handlers.go, metrics/prometheus.go, metrics/prometheus_test.go
@timstclair as requested in #1429.
=> Cherry-pick e76096d into release-v0.24

docs/application_metrics.md
There is a minor mistake of Dockerfile example
=> Fix an error in 'application_metrics.md'

CHANGELOG.md
Cherrypick release notes from `release-v0.23` branch into `master`
/cc @vishh @dchen1107 @sjenning
=> Cherrypick 1.3 changelog

CHANGELOG.md
Fixes https://github.com/google/cadvisor/issues/1431
/cc @dchen1107 @jimmidyson @ncdc @derekwaynecarr @pmorie
=> Add v0.24.0 release notes

Godeps/Godeps.json, container/libcontainer/helpers.go, vendor/github.com/opencontainers/runc/libcontainer/README.md, vendor/github.com/opencontainers/runc/libcontainer/SPEC.md, vendor/github.com/opencontainers/runc/libcontainer/cgroups/cgroups.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuset.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/devices.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go, vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unix.go, vendor/github.com/opencontainers/runc/libcontainer/configs/config.go, vendor/github.com/opencontainers/runc/libcontainer/configs/device_defaults.go, vendor/github.com/opencontainers/runc/libcontainer/container.go, vendor/github.com/opencontainers/runc/libcontainer/container_linux.go, vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go, vendor/github.com/opencontainers/runc/libcontainer/generic_error.go, vendor/github.com/opencontainers/runc/libcontainer/init_linux.go, vendor/github.com/opencontainers/runc/libcontainer/keys/keyctl.go, vendor/github.com/opencontainers/runc/libcontainer/label/label_selinux.go, vendor/github.com/opencontainers/runc/libcontainer/process_linux.go, vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go, vendor/github.com/opencontainers/runc/libcontainer/setns_init_linux.go, vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go, vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_386.go
Cherry-pick https://github.com/google/cadvisor/pull/1476
=> Backport: Fix running cAdvisor in container on RHEL systems

CHANGELOG.md
=> v0.24.1 release notes

utils/oomparser/oomparser_test.go
They had reflect.Equal instead of !reflect.Equal.
They also depended on the current year. Which changed.
=> oomparser: Fix tests

CHANGELOG.md
Cherry-pick of https://github.com/google/cadvisor/pull/1496 into master
=> Cherry-pick: v0.24.1 release notes

Makefile, build/jenkins_e2e.sh
Fixes https://github.com/google/cadvisor/issues/1432
/cc @dashpole
=> Build & test cAdvisor with go 1.7.1

docs/storage/prometheus.md
The GUI part of the blog post example seems not much relevant anymore, there are some nice starter projects from @vegasbrianc that could be interesting to mention here.
=> mention another prometheus example using Grafana

container/docker/factory.go
It has been found in production environments that the usage of thin_ls can result in a large number of iops operations.  In iops restricted environments, this can have an impact on end-user workloads.
=> disable thin_ls due to excessive iops

build/release.sh, docs/development/releasing.md
The recent news reminded me to fix this...
=> Record sha256 for cAdvisor releases

docs/development/releasing.md
This PR fix markdown format about code blocks. :)
/ping @timstclair
=> fix markdown format

fs/fs.go
Please see https://github.com/kubernetes/kubernetes/issues/38337 and https://github.com/kubernetes/kubernetes/pull/39862 for details.
=> Added fix for Kubernetes btrfs issue #38337

docs/running.md
I don't think this section was accurate, and I also don't think that filing an issue is the best way to get support.
/cc @vishh
=> Remove out of date support section of running doc

client/client.go
A new client builder **NewClientWithTimeout** is added, which can create a HTTP client with timeout instead of http.DefaultClient.
=> Create cadvisor client with http client timeout

CHANGELOG.md
This PR adds major changes for the v0.26.0 release to the changelog
/assign @timstclair
=> v0.26 release notes

build/jenkins_e2e.sh
=> Update go version for jenkins testing from 1.7 to 1.8

container/common/helpers.go
The `github.com/google/cadvisor/container/common` package has some helpers which race on checks for non-existent files. The race is as follows:
1. A call to stat is used to check for existence of the directory.
2. The directory is deleted by something else.
3. A call to open fails because the directory does not exist.
This change modifies the code to eliminate the call to stat and check the error code off the open operation. In practice, this bug causes startup failures in kuberneties kubelet:
```
Failed to start cAdvisor readdirent: no such file or directory
```
=> Fix race in ignoring non-existent directories

fs/fs.go
Sorry for the short description, all the details can be found here: https://github.com/kubernetes/kubernetes/issues/47046
=> Added fix for Kubernetes btrfs issue #47046

CHANGELOG.md
=> Add changelog for 0.26.1.

CHANGELOG.md
=> Cherrypick #1685 into release-v0.26

deploy/Dockerfile
=> thin-provisioning-tools moved to alpine main

deploy/Dockerfile
Cherry-pick of https://github.com/google/cadvisor/pull/1687
=> [cherry-pick] thin-provisioning-tools moved to alpine main

deploy/Dockerfile
Guys,
This PR fix this issue: https://github.com/google/cadvisor/issues/1641
Thanks!
=> Added findutils at the Dockerfile

Godeps/Godeps.json, vendor/github.com/docker/docker/AUTHORS, vendor/github.com/docker/docker/pkg/mount/flags.go, vendor/github.com/docker/docker/pkg/mount/flags_unsupported.go, vendor/github.com/docker/docker/pkg/mount/mount.go, vendor/github.com/docker/docker/pkg/mount/mounter_solaris.go, vendor/github.com/docker/docker/pkg/mount/mounter_unsupported.go, vendor/github.com/docker/docker/pkg/mount/mountinfo_solaris.go, vendor/github.com/docker/docker/pkg/mount/mountinfo_unsupported.go, vendor/github.com/docker/docker/pkg/mount/sharedsubtree_solaris.go, vendor/github.com/docker/docker/pkg/symlink/fs.go, vendor/github.com/docker/docker/pkg/symlink/fs_unix.go, vendor/github.com/docker/docker/pkg/symlink/fs_windows.go, vendor/github.com/docker/docker/pkg/system/events_windows.go, vendor/github.com/docker/docker/pkg/system/exitcode.go, vendor/github.com/docker/docker/pkg/system/filesys.go, vendor/github.com/docker/docker/pkg/system/filesys_windows.go, vendor/github.com/docker/docker/pkg/system/meminfo_solaris.go, vendor/github.com/docker/docker/pkg/system/meminfo_unsupported.go, vendor/github.com/docker/docker/pkg/system/meminfo_windows.go, vendor/github.com/docker/docker/pkg/system/path_unix.go, vendor/github.com/docker/docker/pkg/system/path_windows.go, vendor/github.com/docker/docker/pkg/system/stat_darwin.go, vendor/github.com/docker/docker/pkg/system/stat_unsupported.go, vendor/github.com/docker/docker/pkg/system/syscall_windows.go, vendor/github.com/docker/docker/pkg/system/umask.go, vendor/github.com/docker/docker/pkg/system/utimes_darwin.go, vendor/github.com/docker/docker/pkg/system/utimes_unsupported.go
Updates the docker godeps to be the same as in k8s:
https://github.com/kubernetes/kubernetes/pull/48308
=> Update docker godeps to be the same as k8s

deploy/canary/Dockerfile
fixes https://github.com/kubernetes/test-infra/issues/4403
=> Add apt-get update to dockerfile

CHANGELOG.md
=> 0.27.1 changelog update

deploy/canary/Dockerfile
follow-up to https://github.com/google/cadvisor/pull/1749
cc @ixdy
=> clean after apt-get install

metrics/prometheus.go, metrics/testdata/prometheus_metrics
Fixes #1744 
I am using the description from https://github.com/google/cadvisor/blob/master/info/v1/container.go#L328
cc @octete
=> Update memory usage helper message

container/docker/handler.go
monitor diff directory for overlay2
This is the cadvisor branch that corresponds to v1.8
=> Cherrypick of #1770 to 0.27 release branch

container/libcontainer/helpers.go
Cadvisor can inotify watch for new cgroups. This leads to it racing
fairly tightly with cgroup creation... So tightly, that sometimes
cpustats are nil.
The runc library code we call
(https://github.com/opencontainers/runc/blob/v1.0.0-rc4/libcontainer/cgroups/fs/apply_raw.go#L179-L182)
doesn't actaully consider this an error, so we have to handle that
scenario ourselves.
This fixes https://github.com/google/cadvisor/issues/1765
I've verified that applying this patch to the kubelet fixes the instance of the above issue I could observe.
As far as I can tell, this patch is cosmetic in that it fixes an error log, but no actually erroneous behavior.
=> libcontainer: ignore nil cpustats

container/crio/handler.go
=> CRI-O: fix handling of overlay2 storage

Godeps/Godeps.json, vendor/github.com/mistifyio/go-zfs/.travis.yml, vendor/github.com/mistifyio/go-zfs/README.md, vendor/github.com/mistifyio/go-zfs/utils.go, vendor/github.com/mistifyio/go-zfs/utils_notsolaris.go, vendor/github.com/mistifyio/go-zfs/utils_solaris.go, vendor/github.com/mistifyio/go-zfs/zfs.go, vendor/github.com/mistifyio/go-zfs/zpool.go
The issue reported in #1691 is fixed in upstream go-zfs.
=> Update go-zfs dependency

container/common/fsHandler.go
This two error checks where using the wrong error, fix this.
=> Fix wrong error checking in fsHandler.go

Godeps/Godeps.json, accelerators/nvidia.go, accelerators/nvidia_test.go, accelerators/types.go, build/build.sh, container/libcontainer/helpers.go, info/v1/container.go, info/v2/container.go, info/v2/conversion.go, info/v2/conversion_test.go, manager/container.go, manager/container_test.go, manager/manager.go, metrics/prometheus.go, metrics/prometheus_test.go, metrics/testdata/prometheus_metrics, vendor/github.com/mindprince/gonvml/LICENSE, vendor/github.com/mindprince/gonvml/Makefile, vendor/github.com/mindprince/gonvml/NVML_NOTICE, vendor/github.com/mindprince/gonvml/README.md, vendor/github.com/mindprince/gonvml/bindings.go, vendor/github.com/mindprince/gonvml/nvml.h
Fixes #1436.
The design doc is at: https://docs.google.com/document/d/13O4HNrB7QFpKQcLcJm28R-QBH3Xo0VmJ7w_Pkvmsf68/
=> Add per container GPU metrics

accelerators/nvidia.go
Fixes https://github.com/google/cadvisor/issues/1810
=> Avoid race in accessing nvidiaDevices between Setup() and GetCollector()

docs/running.md
=> Add docs for using nvidia gpu monitoring.

metrics/prometheus.go
=> Ensure all Prometheus metrics have the same labelnames.

container/docker/docker.go, manager/manager.go
For https://github.com/google/cadvisor/issues/1866.
=> Connect to docker with no timeout on startup

container/containerd/client.go
Currently, cadvisor will create a containerd client for echo containerd container handler, that will use a lot of memory when we create a large number of containers via containerd. 
This pr make all containerd container handlers share a single client instance to reduce memory usage of containerd  client (grpc).
Also fixes containerd/cri-containerd#587
/cc @Random-Liu @abhi 
Signed-off-by: Yanqiang Miao <miao.yanqiang@zte.com.cn>
=> All handlers of containerd containers share a single client instance

container/containerd/handler.go
Cherrypick of #1894 onto the v0.29 branch
/assign @Random-Liu
=> Use backoff to tolerant race condition.

manager/manager.go
=> fix #1902 on the v0.29 release branch

manager/manager.go
=> fix #1902 bug with retryDockerStatus

fs/fs.go
https://github.com/kubernetes/kubernetes/issues/65204
Signed-off-by: Maximilian Meister <mmeister@suse.de>
=> fix kubernetes issue #65204

cache/memory/memory.go, manager/manager.go
Fix: https://github.com/google/cadvisor/issues/1970
/assign @dashpole
=> Return best-effort result when AllDockerContainers hits the cache not synced issue

docs/storage/README.md, docs/storage/statsd.md
This is the start of documentation for statsd (issue #2002). Happy to add more detail if needed, but this should be enough to get people off the ground with it :)
=> statsd docs (Issue #2002)

container/mesos/client.go, container/mesos/client_test.go, container/mesos/factory.go, container/mesos/handler.go, container/mesos/mesos_agent.go, container/mesos/mesos_agent_test.go
This is an add on to issue 1965
=> Ensure that labels for mesos tasks launched via MesosCommandExecutor are collected

metrics/prometheus.go
https://github.com/google/cadvisor/issues/2020
prometheusCollector if condition error
=> networkUdpMetrics error if condition

pages/static/assets.go, pages/templates.go
This fixes test failures: https://k8s-testgrid.appspot.com/sig-node-cadvisor#cadvisor-e2e
=> update asset headers to 2019

utils/oomparser/oomparser_test.go
cleanup unused/outdate variables and functions in oomparser_test.go
=> cleanup oom parser test

docs/running.md
fix `priviledges` -> `privileges`
=> docs: fix typo

deploy/Dockerfile
=> Update GLIBC_VERSION and alpine Version

deploy/kubernetes/base/cluserrole.yaml, deploy/kubernetes/base/cluserrolebinding.yaml, deploy/kubernetes/base/daemonset.yaml, deploy/kubernetes/base/kustomization.yaml, deploy/kubernetes/base/podsecuritypolicy.yaml, deploy/kubernetes/base/serviceaccount.yaml
Allow cadvisor to run in clusters with PSPs enabled
=> add manifests for rbac and psps

cadvisor.go
=> Added missing quote

deploy/Dockerfile
I tried to build docker image and found mistake, there is no curl in the alpine image, I changed it to wget
=> Fix Healthcheck

cadvisor.go, integration/runner/runner.go, utils/cpuload/netlink/reader.go
fixes https://github.com/google/cadvisor/issues/2221
fixes https://github.com/google/cadvisor/issues/2222
fixes https://github.com/google/cadvisor/issues/2223
=> Fix code safe linter errors

fs/fs.go, fs/fs_test.go
Fixes #2218
Signed-off-by: Erik Jansson <erikja@axis.com>
=> Adding ability to handle OverlayFS mounts

container/docker/factory.go
Cadvisor in kubelet can't connect to docker daemon when docker and kubelet start together and docker daemon hasn't fully initialized, cadvisor can't get the docker root dir from docker daemon, and will get this value from kubelet's --docker-root flag,  its default value is /var/lib/docker, but when the user's docker dir is not a standard dir,  this will cause the lack of monitoring. 
such as the case metioned in  https://github.com/google/cadvisor/issues/1932#issuecomment-383044255, it is a case of node reboot. We also find when start a node, this problem will occasionally happen again, and will have lots of errors such as `Oct 27 23:35:32 tgamesdk-prod-caster-sh-app-14 kubelet[19472]: E1027 23:35:32.931339   19472 manager.go:1130] Failed to create existing container: …
=> Retry to get docker root and log when error

Makefile
Building in docker will do not make some effects on the local go environment
=> Support build this project by docker

fs/fs.go
For support for mips.
https://github.com/kubernetes/kubernetes/issues/86749
=> Support for mips

machine/machine.go
Add mips64 to clock speed ignore list.
=> Ignore CPU clock for mips64

container/docker/factory.go, container/docker/handler.go, container/docker/utils/docker.go, fs/fs.go
Move things a bit so references to docker/docker are under the same directory
=> moving docker/utils into container/docker

vendor/k8s.io/utils/mount/mount_helper_unix.go, vendor/k8s.io/utils/mount/mount_linux.go, vendor/modules.txt
Fix for https://github.com/google/cadvisor/issues/2394
=> Update vendor for k8s.io/utils

go.mod, go.sum, vendor/github.com/docker/distribution/reference/normalize.go, vendor/github.com/docker/distribution/reference/reference.go, vendor/github.com/docker/distribution/registry/api/errcode/errors.go, vendor/github.com/mindprince/gonvml/.travis.gofmt.sh, vendor/github.com/mindprince/gonvml/.travis.yml, vendor/github.com/mindprince/gonvml/Makefile, vendor/github.com/mindprince/gonvml/bindings.go, vendor/github.com/mindprince/gonvml/bindings_nocgo.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go, vendor/modules.txt
- updating containerd/containerd needs an update to docker/distribution
- updating mindprince/gonvml so builds work on macos
- use a specific released version of github.com/opencontainers/selinux (v1.3.2)
=> Update containerd/containerd to v1.3.3

go.mod, go.sum, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/modules.txt
To pick up a fix for a regression:
https://github.com/opencontainers/selinux/pull/71/commits/4e413ab11410afc49e426ed5e21dc41454f15a41
=> Bump github.com/opencontainers/selinux to v1.3.3

container/common/fsHandler.go
In realFsHandler#trackUsage, the error return from the first call to fh.update() is ignored.
This PR extracts the period adjustment logic into a func and calls this func in place of original fh.update()
=> Adjust period after each fh.update() call

README.md, docs/development/releasing.md, docs/running.md
=> Document that we don't update the latest tag

go.mod, go.sum
Pick up changes in:
[a905ae5f52ca711453609d0decaa2e2fa318e829](https://github.com/kubernetes/utils/commit/a905ae5f52ca711453609d0decaa2e2fa318e829)
=> Move to newer k8s.io/utils

manager/container.go
=> lower logging verbosity for summary reader creation failure

container/crio/client.go
Signed-off-by: Ted Yu <yuzhihong@gmail.com>
This PR stores crio client in a global variable.
Client() would return this client instance.
=> Construct crio client once

machine/topology_test.go, utils/sysfs/fakesysfs/fake.go, utils/sysfs/sysfs.go, utils/sysinfo/sysinfo.go, utils/sysinfo/sysinfo_test.go
Related to #2468 and  kubernetes/kubernetes#89859
=> Fix getting CPU topology

machine/machine.go
=> Returning error before using value

cmd/internal/pages/pages.go, cmd/internal/pages/static/static.go
commit c22edbcc7d2fff1437b261c97eaa4ab85c61099e moved the files under
cmd/internal.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> cmd: fix path for assets

info/v1/container.go
This PR adds missing fields to StatsEq method.
=> Add missing fields to ContainerStats#StatsEq

.github/workflows/test.yml, .gitignore, Makefile, build/integration-in-docker.sh, container/docker/factory.go, container/docker/handler.go, integration/tests/api/docker_test.go, integration/tests/api/machine_test.go, integration/tests/api/machinestats_test.go, utils/sysinfo/sysinfo_test.go
- Add a docker based test that works on ubuntu and macOS
- Run the new make target using github actions
=> Docker based integration test for cadvisor

.github/workflows/test.yml, Makefile, build/integration-in-docker.sh, build/unit-in-docker.sh, perf/collector_libpfm_test.go
=> Unit tests improvements

build/unit-in-docker.sh
Cleaning up development leftovers.
=> Tests must fail on bash error

docs/development/build.md
=> Add documentation for building and running cAdvisor with perf support

README.md
/assign @katarzyna-z 
ref: https://github.com/google/cadvisor/issues/2150
=> add --privileged to example to readme

README.md
=> Add /dev/kmsg to docker example

docs/running.md
=> Information about running cAdvisor without privileged option

utils/sysinfo/sysinfo.go
Some customers complain that k3s repo after having a log fill up with this message.
So let's move it from level-0 to level-1.
Signed-off-by: Bin Lu <bin.lu@arm.com>
=> Move the cache missing log from level-0 to level-1

container/raw/handler.go, container/raw/handler_test.go
=> Not collecting disk metric for root container when not requested to

utils/sysfs/fakesysfs/fake.go, utils/sysinfo/sysinfo.go, utils/sysinfo/sysinfo_test.go
=> Fix #2566 warning instead of error when core_id or physical_package_id not available

manager/manager.go
It provides cgroup v2 support for perf events.
#2485
=> Add cgroups v2 support for perf events.

cmd/go.sum, go.mod, go.sum
Update opencontainers/runc to version which includes https://github.com/opencontainers/runc/pull/2470
@dashpole @vynu Could you verify if this fixes #2583?
@giuseppe if this fixes the issue it'll be good to update opencontainers/runc in your pull request https://github.com/kubernetes/kubernetes/pull/91366
=> Fix #2583, update opencontainers/runc

docs/runtime_options.md, info/v1/container.go, info/v1/machine.go, info/v2/container.go, info/v2/conversion.go, info/v2/conversion_test.go, machine/info.go, manager/manager.go, metrics/prometheus.go, metrics/prometheus_fake.go, metrics/prometheus_test.go, metrics/testdata/prometheus_metrics, perf/collector_libpfm.go, perf/collector_libpfm_test.go, perf/config.go, perf/config_test.go, perf/manager_libpfm.go, perf/manager_libpfm_test.go, perf/manager_no_libpfm.go, perf/testing/grouped.json, perf/testing/perf-non-hardware.json, perf/testing/perf.json, perf/uncore_libpfm.go, perf/uncore_libpfm_test.go, utils/sysinfo/sysinfo.go, utils/sysinfo/sysinfo_test.go
It provides support for uncore perf events in which PMUs are not associated with a core but a whole socket.
=> Add perf uncore events support.

container/libcontainer/handler.go
Raw containers ( such as systemd services ) don't have main PID, so
before this change they weren't allowed to retrieve various stats from
the cgroup such as networking stats.
However, some process stats such as file descriptor counts or number of
processes are still valuable to those containers and we should be able
to retrieve them without depending on the main pid.
For example, on my laptop:
Before:
```
container_processes{id="/system.slice/containerd.service"} 0 1593123685900
```
After:
```
container_processes{id="/system.slice/containerd.service"} 4 1593123707235
```
=> Allow raw container to retrieve process stats

docs/runtime_options.md
=> Add information about configuring perf events using libpfm4

README.md
=> Update readme to point to discuss.kubernetes.io

docs/runtime_options.md
=> Add flags that were not previously published

nvm/machine_libipmctl.go
=> Fix runtime error when there are no NVM devices.

validate/validate.go
In v2, memory accounting is always hierarchical, so skip the checks.
=> validateMemoryAccounting: fix for cgroup v2

deploy/Dockerfile
=> Add checking checksum of libpfm4

deploy/Dockerfile
Update libpfm package in Dockerfile to the newest version.
=> Update libpfm to 4.11.0

.github/workflows/test.yml
Upgrading linter to newer and shinier version.
=> Upgrading golangci-lint to 1.34.1

manager/container.go, manager/container_test.go
=> Refactor process parsing to accommodate commands with spaces

build/prow_e2e.sh, cmd/internal/pages/static/assets.go
Ran `FORCE=true build/assets.sh`
=> Regen assets

build/assets.sh, build/boilerplate/boilerplate.py, build/prow_e2e.sh, cmd/internal/pages/static/assets.go
Cherrypicking #2777 #2778 and #2779
=> Fix assets on v0.38

docs/storage/prometheus.md, metrics/prometheus.go, metrics/prometheus_fake.go, metrics/testdata/prometheus_metrics
Signed-off-by: Wisniewski, Krzysztof2 <Krzysztof2.Wisniewski@intel.com>
=> Add container_blkio_device_usage metric

container/libcontainer/handler.go, container/libcontainer/handler_test.go, utils/sysinfo/sysinfo.go, utils/sysinfo/sysinfo_test.go
Porting of recent fixes applied to master.
=> Porting fixes to #2792 and #2798 to v0.38

container/docker/handler.go, container/docker/handler_test.go, fs/fs.go, fs/fs_test.go, fs/types.go
First reported in issue #2609 (https://github.com/google/cadvisor/issues/2609)
=> Added support for filesystem metrics on Docker

cmd/go.sum, go.mod, go.sum
Edit go.mod and bump containerd to v1.4.4 and run `go mod tidy`
=> Bump containerd to 1.4.4

container/docker/factory.go
Fixes #1936.
As far as I can tall all the `!= nil` has already been in place. Tested on:
* Docker with ZFS pool
* Docker with overlay
=> Conditionally gathering FS usage metrics.

CHANGELOG.md
- Update with 0.39.0 release notes
- Backfill changelog with older releases
=> Update changelog for 0.39.0

README.md
Updating readme with some details about the core team / contributors.
PTAL @iwankgb @Creatone @dims @mrunalp @haircommander @dashpole 
Thanks for all your contributions & help on cAdvisor!
=> Update README with contributor info

cmd/go.sum, go.mod, go.sum
keeping up with the Joneses!
Containerd : https://github.com/containerd/containerd/compare/v1.5.1...v1.5.2
Docker : https://github.com/docker/docker/compare/v20.10.2...v20.10.7
=> Bump docker and containerd for cadvisor

perf/manager_libpfm.go, perf/manager_libpfm_test.go, perf/testing/perf-no-events.json
=> Check if there are perf events to gather.

metrics/prometheus.go, metrics/prometheus_test.go, metrics/testdata/prometheus_metrics_whitelist_filtered
Signed-off-by: colstuwjx <colstuwjx@gmail.com>
It's a follow-up PR for #2921 and #2330.
=> feat: add container whitelisted envs as metrics labels.

manager/manager.go
=> Backporting #2868 on release v0.39.x

cmd/internal/pages/static/assets.go, cmd/internal/pages/templates.go
```
$ make assets FORCE=true
```
=> Regen assets due to 1.19 changes

info/v1/machine.go, machine/info.go
Fixes https://github.com/google/cadvisor/issues/2961
=> add support for swap in machine/info

build/integration-in-docker.sh
=> Mark GOPATH as git safe.directory to fix CI build

machine/machine.go
=> Decreasing verbosity level for "Cannot read vendor id correctly, set empty"

README.md
As I'm leaving my current company, let this info be up to date.
=> readme: Update Creatone contributor info.

build/assets.sh
Pin the version to v3.24.0 which is working (latest version seems to broken).
=> Fix asset build

build/check_container.sh, build/release.sh
Signed-off-by: Snehal Rajmane <srajmane@us.ibm.com>
=> Add s390x support for docker image

.golangci.yml, Makefile, build/assets.sh, build/boilerplate/boilerplate.py, build/boilerplate/boilerplate.py.txt, integration/framework/framework.go, integration/tests/api/docker_test.go
See commit by commit. Cherrypick a few changes to fix CI builds.
=> Fix CI jobs on v0.47

container/crio/handler.go
This PR backports the changes from https://github.com/google/cadvisor/pull/3301 to 0.45
=> [0.45] Request the pid of another container if current pid is not longer valid

container/libcontainer/handler.go
=> add ignored device

.github/workflows/test.yml
I upgraded actions/setup-go, actions/checkout and actions/upload-artifact in github workflow.
=> upgrade actions version in github workflow

container/podman/factory.go
=> Avoiding nil pointer in podmanFactory.CanHandleAndAccept()

.github/workflows/test.yml, build/config/libipmctl.sh, build/integration-in-docker.sh, integration/framework/framework.go
cherry pick commits in https://github.com/google/cadvisor/pull/3559 and https://github.com/google/cadvisor/pull/3540 to release-v0.49 to fix CI test
=> Cp fix test
