manager/machine.go

Use thread ids instead of core-ids to identify caches.

Fix reading cache info for machines with unused packages.

---

pages/static/containers_js.go

The first 5 gauges on the list may not be the same as the first 5 gauges
being displayed.

Limit to 5 FS gauges in a stable way.

---

manager/container.go

Also reduce logging to once every minute.

Handle initial zero value of lastError.

---

utils/sysfs/fakesysfs/fake.go
utils/sysinfo/sysinfo.go
utils/sysinfo/sysinfo_test.go

New logic ignores veth, docker, and loopback devices.

Handle root network device names other than eth.

---

fs/fs.go

Filesystem stats are hardcoded to sd* devices. Make it work on EC2 too. Probably related to #376.

Also process /dev/xvd? partitions

---

container/container.go
container/docker/handler.go
container/mock.go
container/raw/handler.go
info/container.go
manager/container.go
manager/container_test.go
manager/manager.go
manager/manager_test.go
utils/cpuload/cpuload.go
utils/cpuload/netlink.go

The stats are only populated when cAdvisor is running outside network namespaces.
We'll add a different backend to retrieve the same data from within namespaces.

Add task load stats to containers.

---

info/machine.go
utils/sysfs/fakesysfs/fake.go
utils/sysfs/sysfs.go
utils/sysinfo/sysinfo.go
utils/sysinfo/sysinfo_test.go

Type can be one of "none", "noop", "deadline", "cfq".
For block devices that don't use scheduler (like dm), the type will be "none".
We'll also report "none" for partitions when we start reporting those.

Add scheduler type to disk info.

---

container/libcontainer/helpers.go

I'm not sure this is intended omission, so looks like blkio should be there?
https://groups.google.com/forum/#!topic/google-containers/OyX_B_Qu-4c

Add blkio cgroup to list of supported subsystems

---

pages/containers_html.go

This is also consistent with the other container pages.

Move network graphs above filesystem info for root.

---

info/machine.go
utils/sysinfo/sysinfo.go

The kernel reports -1 in case of errors so it should be an allowable
returned value.
Fixes #454.

Make network fields signed integers.

---

manager/container.go
utils/cpuload/cpuload.go
utils/cpuload/netlink/example/example.go
utils/cpuload/netlink/reader.go
utils/cpuload/scheddebug/scheddebug.go

Prefer netlink based reader when available as it provides stats for
processes in state other than running (sleep, diskio, uninterruptible).

Add scheddebug based cpuload reader.

---

container/docker/handler.go

We were using the container name instead of the Docker ID which breaks
in systemd systems.
Fixes #475.

Fix detection of AUFS layers.

---

container/docker/handler.go
container/raw/handler.go
fs/fs.go
manager/container.go

This should make us more robust in the face of failure (at the cost of
making the failures less prominent). We allow GetStats() to return an
error and a partial result. We will process the result and report the
error.
Fixes #306.

Allow partial success of GetStats().

---

container/docker/factory.go

No longer do deduction from the cgroup path (only to get the Docker
container ID).
Fixes #450.

Detect Docker containers by asking the Docker.

---

manager/manager.go
pages/containers_html.go
pages/static/containers_js.go

I'd like to understand its resource usage and improve accuracy
before we ship it in an official release.

Disable cpu load tracking temporarily.

---

integration/common/gce.go
integration/framework/framework.go
integration/runner/runner.go

Some distros don't have screen. Here we wait for cAdvisor to come up
before continuing.

Don't use screen to run cAdvisor in the background.

---

api/versions.go

Presently, we just fail this request:
$ curl 0:8080/api/v1.2/docker/
failed to get Docker container "" with error: unable to find Docker container ""

Map request for 'api/v1.2/docker/' to 'api/v1.2/docker'

---

cadvisor.go
manager/manager.go
manager/manager_test.go
storagedriver.go

The current structure is a remnant of when the in memory storage was one
of the options for backing store. Today, we always have the memory
storage with an optional "backend storage" plugin. This commit makes the
InMemoryStorage use explicit.

Make explicit the use of InMemoryStorage in Manager.

---

api/versions.go
manager/container.go
manager/manager.go
summary/summary.go

Right now, we just do raw container name. More types to follow.
We'll re-do the older endpoint in 2.0 before we publish it.

Expose a minimal 2.0 API with the first summary endpoint.

---

info/container.go
summary/percentiles.go
summary/summary.go

Before this change, we do not return anything meaningful till cadvisor has been up
for a minute. Also, having instant usage in the same stat gives a more complete
picture.

Add instant stat to derived result.

---

CHANGELOG.md
info/version.go

Left out some work that is in progress (summary stats) as well as the 2.0 API (since we don't want that used just yet).

cAdvisor 0.10.0.

---

manager/container.go

Failures to create stats summary should be non-fatal.

---

pages/pages.go

This is useful for identifying k8 containers on /docker handler.
Since k8 handles are pretty long, I arbitrarily decided to truncate the display.
Let me know if you don't like it.

Always use alias as display name if its available.

---

cadvisor.go
manager/manager.go
manager/manager_test.go

This lets us simplify the startup of the manager.

Register container handler factories in manager.New().

---

manager/machine.go

Use "/etc/machine-id,/var/lib/dbus/machine-id" as default.

Make machine-id sources flag a comma-separated list.

---

docs/integration_testing.md

runner.go doesn't work on localhost as it tries to ssh to the local machine :)

Update documentation on running integration tests.

---

manager/container.go
summary/percentiles.go
utils/cpuload/netlink/reader.go

Lowering all frequent normal logs to v=3. Kubelet runs by default on
debug of v=2 and we don't want to log these events in that case.

Lowering log level for frequent events.

---

manager/machine.go

We won't have access to it if we're not running as root.

Don't fail requests if System UUID is not available.

---

api/handler.go
cadvisor.go
pages/pages.go
utils/mux.go

This will allow us to register handlers on the non-default HTTP handler.

Use mux to register HTTP handlers.

---

manager/manager.go

This will allow us to degrade gracefully in the environments where no
cgroups exist, but we'd still like cAdvisor to be running.

Don't fail if the raw cgroup factory fails to register.

---

api/versions.go
container/docker/factory.go
container/docker/handler.go
container/raw/factory.go
container/raw/handler.go
fs/fs.go
fs/types.go
info/v2/container.go
manager/machine.go
manager/manager.go
manager/manager_mock.go

/storage returns {device, mountpoint, capacity, usage} for all filesystems.
In addition, it also detect and applies label for each filesystem - currently two - "root", "docker-images".
/storage/<label> returns info about the filesystem with specific label. eg. /storage/root returns info for root filesystem.

Add /storage endpoint to 2.0 API.

---

container/factory.go
manager/manager.go

This allows us to handle the case where there are no factories as
happens when testing in a non-container environment. We will still serve
the machine information that is available.

Start() exits gracefully when there are no factories.

---

api/versions.go
info/v2/container.go

First cut on 2.0 stats API. Main change in returned stats is that presence checks (eg. HasCPU) are embedded in each stat.
Added support to handle querying container with name.
Current syntax:
/stats?name=/&count=1,
/stats?name=docker/928c058ce260ac2a55972b18cb991fa0475fbbb7bc15bd295e62b76964d05fe6 [default count: 64]
Other handlers to include: dockerid, dockeralias. We can make subcontainers inclusion as an option too.

WIP: Add stats API for 2.0.

---

metrics/prometheus.go

With this change, all definitions and functionality for a given metric
are in a single place only instead of being distributed all over the
file. This makes it easier to inspect the code for correctness and
adding/changing metrics.

Clean up code around Prometheus metrics, more DRY.

---

manager/manager.go

Before this we'd return an instance for each alias we'd saved.
Fixes #592.

Return unique containers in Subcontainers().

---

api/versions.go
info/v2/container.go
manager/manager.go
manager/manager_mock.go

spec, stats, and summary now all support the same options (except count,
which is only parsed for stats).

Add recursive and type options (raw/docker) to spec and summary endpoints.

---

manager/container.go
manager/manager.go

Following the Kubernetes convention of V(2) is normal verbosity (log
each request to a webserver).

Reduce the level for a few common log messages

---

api/handler.go
info/v1/container.go
storage/memory/stats_buffer.go
storage/memory/stats_buffer_test.go

Rather than relying on 64 being a "big enough" value.

Return all stats by default.

---

api/versions.go

The v2.0 API is separate and will evolve to have separate structured
from v1.x.

v2.0 API does not depend on v1.x.

---

storage/memory/stats_buffer.go

pointers that reference addresses of the internal circular buffer should not escape

---

info/v1/container.go
manager/manager.go

Having this as an interface was giving us a lot of problems with
unmarshaling. Made into a union of concrete types.

Make EventData a concrete type.

---

container/docker/handler.go
container/libcontainer/helpers.go
integration/tests/api/docker_test.go

A better fix is to directly use stats collected by libcontainer.

Fix networking stats by switching Tx and Rx stats.

---

docs/runtime_options.md
manager/manager_test.go
storage/memory/memory.go
storage/memory/memory_test.go
storage/memory/stats_buffer.go
storage/memory/stats_buffer_test.go
storagedriver.go

This is the first step in making StatsBuffer non-stats specific and usable elsewhere. There are some further simplifications we can make to the code which I will do in future PRs.

Move StatsBuffer to be time-based

---

storage/memory/memory.go
utils/timed_store.go
utils/timed_store_test.go

This will allow us to use it in other places.

Generalize StatsBuffer into TimedStore

---

container/docker/factory.go
container/factory.go
container/factory_test.go
container/raw/factory.go
manager/manager.go
manager/manager_mock.go
pages/containers.go

This reduces unnecessary load on the system and also cleans up the UI clutter.
Currently defaulted to false.

Add --docker_only flag to enable tracking for only docker containers & root.

---

events/handler.go
events/handler_test.go
manager/manager.go
storage/memory/memory.go
utils/timed_store.go
utils/timed_store_test.go

Made the default limit 100,000 elements which is a little over 1 event per second for a day and assuming 250 bytes per event it would take up ~24MiB per event type.
/cc @rjnagal

Add an item limit to TimedStore

---

pages/containers.go
pages/containers_html.go
pages/pages.go
pages/static/containers_js.go

This will allow cAdvisor to be reverse proxied, and fixes a long-standing feature request :)
Fixes #513
Fixes #566
Fixes #596
Fixes #667

Make all links relative.

---

events/handler_test.go
utils/timed_store.go

The current logic assumes that entries are added to the store in
monotonically increasing order for time. This is not true when
we add creation events for existing containers.
Also fixes the bug that we don't delete expired entries if all entries in the buffer are expired.
Modified the test that depended on that behavior.

Fix handling of time ranges in timed store.

---

container/raw/handler.go

Containers with subcontainers always report creation time to be same as the time
of creation of the latest subcontainer.
Still not an ideal solution, but accurate for most practical purposes.

Improve approximation of container creation time.

---

manager/machine.go

Everything other than cache information is available through /proc/cpuinfo.

Return partial topology information if cache info is not available.

---

docs/running.md

1) cgroups were getting mounted at /cgroup: not /cgroup
2) incorrect flag was used:
provided but not defined: --privilege
See 'docker run --help'.

update documentation for CentOS 7

---

container/raw/handler.go
fs/fs.go
fs/statvfs.c
fs/types.go
info/v1/container.go

The current capacity and usage numbers are insufficient to figure out
actual bytes available for a non-root user for the fs. Available is the
value used by df and the one we need to track to detect low diskspace
condition.

Add 'bytes available' to fs info.

---

container/raw/handler.go
container/raw/inotify_watcher.go

This makes it easier to ensure the error conditions are handled well and
that we don't leak watches.
Fixes #703
/cc @rjnagal

Separate inotify handling into its own object.

---

manager/machine.go

Add support for parsing CPU speed from /proc/cpuinfo on Power (ppc64) systems
/proc/cpuinfo format varies between architectures. For example
On Intel the cpu speed is shown like the following
cpu MHz		: 3000
whereas on Power systems its shown like the following
clock		: 3000MHz
This patch enables support for /proc/cpuinfo parsing on Power systems
Signed-off-by: Pradipta Kr. Banerjee <bpradip@in.ibm.com>

Add support for parsing CPU speed from /proc/cpuinfo on Power (ppc64) systems

---

storage/statsd/client.go

Restricted to supporting just gauges now as counters or timing are not very useful for cAdvisor.

Initial client library for statsd backend.

---

container/docker/factory.go

The previous approach was brittle from within a container and was inconsistent.
Fixes #666 
/cc @rjnagal tested in an Ubuntu 15.04 box.

Detect systemd with cgroup hierarchy.

---

container/docker/handler.go

Victor mentioned that there was a 1 line modification that solves the problem, but I couldn't find it. I'm still very new to the cAdvisor code base and to Docker - it took me pretty long to figure out where the specs were stored, and how to extract configuration information from Docker, so I certainly could be doing this in a sub-optimal way. Let me know!

Only show network statistics for containers with bridge network

---

integration/tests/api/docker_test.go
integration/tests/api/event_test.go

Use of sh was making the test flaky and harder to read.
@AnanyaKumar @anushree-n could one of you take a look when you have time? This fixes the integration test.

Use watch instead of sh.

---

info/v1/machine.go
utils/cloudinfo/gce.go

Sorry, I thought I tested my cloud-provider-info code on GCE, but I must have tested the version of the code before Victor's code review (I probably wasn't checked into the right branch, or didn't rebase my changes, when testing on a GCE instance). I've tested this code on my desktop, and on a GCE n1-standard-1 instance.
So when I execute "curl http://localhost:8080/api/v2.0/machine"
Locally, I get: "cloud_provider":"Unknown","instance_type":"Unknown"
On the n1-standard-1 instance, I get: "cloud_provider":"GCE","instance_type":"n1-standard-1"
All integration tests pass except TestDockerContainerNetworkStats. We might want to look at this test again, since I thought Victor's PR last Wednesday should fix this test.

Fix incorrect use of metadata library, correct typo

---

pages/containers.go

Seems like some kernels report a value a bit lower than MaxInt64.
Fixes #796 
/cc @rjnagal

Lower threshold for "unlimited".

---

collector/collector_manager.go
collector/collector_manager_test.go
collector/fakes.go
collector/generic_collector.go
collector/types.go
info/v1/container.go
info/v1/metric.go

v1.ContainerStats structure is being used to cache stats. 
To include CustomMetrics [ ]v2.Metric (originally defined in v2/metric.go), metric.go was moved from v2 to v1.

Include custom metrics in ContainerStats structure

---

collector/generic_collector.go
collector/generic_collector_test.go

@rjnagal , @vmarmol  This is a rough draft of how we could change the Collector structure
The newly added fields 'minPollingFrequency' and 'regexps' in collectorInfo field in Collector structure are necessary for collection of metrics.
We can avoid calculation of these during actual metric collection to prevent repeated calculation during every metric calculation.

Modify Collector structure

---

collector/generic_collector.go
collector/generic_collector_test.go

Based on #787 
Adds Implementation of Collect() method of Collector interface

Collection of custom metrics

---

collector/generic_collector.go

Since polling is tied to housekeeping, minimum supported polling
frequency is 1s.
Users can specify polling frequency higher than 1s. The polling loop
will be called at the minimum frequency specified in config as long as
its higher than the minimum supported frequency.

Change logic for determining minimum polling frequency.

---

collector/collector_manager.go
collector/collector_manager_test.go
manager/container.go
manager/container_test.go
manager/manager_test.go

v1.ContainerStats structure is being used to cache stats. 
To include CustomMetrics [ ]v2.Metric (originally defined in v2/metric.go), metric.go was moved from v2 to v1.
Should v2.ContainerStats be used instead to cache and retrieve stats?

Cache custom metrics

---

info/v2/container.go
summary/percentiles.go
summary/percentiles_test.go

These are some of the stats that will later be needed for kubelet to expose via an endpoint.

Add 50th and 95th percentiles

---

collector/collector_manager.go
collector/generic_collector.go
collector/generic_collector_test.go
container/container.go
container/docker/handler.go
container/mock.go
container/raw/handler.go
manager/container.go
manager/manager.go

Docker does not provide the rootfs path through docker inspect or statefile
and the path is dependent on the storage driver being used.
Instead of enumerating the storage drivers, we pick a pid from the container
and get the config from /proc/pid/root. Although a bit expensive, this method
works for non-docker containers too.

Add logic to read custom metric config files from container root.

---

collector/generic_collector.go
manager/container.go

- a typo in minPollingFrequency multiplies it with time.Second twice.
- Updating custom metrics is unnecessarily called for all containers.

Two small fixes to custom metric collection.

---

api/versions.go
collector/collector_manager.go
collector/collector_manager_test.go
collector/config.go
collector/fakes.go
collector/generic_collector.go
collector/generic_collector_test.go
collector/types.go
info/v1/container.go
info/v1/metric.go
info/v2/container.go
manager/container.go
manager/manager.go

Remove spec-related fields from stat.
We can simplify the stats a bit further by handling Int and Float better.
But this was big enough change already.
Verified v1 and v2 spec/stats/appmetrics APIs.

Add custom metrics to spec.

---

storage/statsd/client/client.go
storage/statsd/statsd.go
storagedriver.go

Hi, I just finish a statsd storage for cadvisor, if you wish try it and send me some feedback about how I did it, you can test it by running my docker image jmaitrehenry/cadvisor or by checking this PR 
This is how I run it:
```
docker run \
--volume=/:/rootfs:ro \
--volume=/var/run:/var/run:rw \
--volume=/sys:/sys:ro \
--volume=/var/lib/docker/:/var/lib/docker:ro \
--publish=8080:8080 \
--detach=true \
--name=cadvisor \
jmaitrehenry/cadvisor \
-storage_driver=statsd \
-storage_driver_host=192.168.59.3:8125 \
-storage_driver_db=docker_001
```
With storage_driver_db is use as a prefix for all stats, I use it for prefixing stats with the docker node hostname for example.
This is a sample of gauge receive by statsd :
```
gauges: 
{ [...]
'docker_001.lonely_yonath.memory_working_set': …
```

Update statsd storage - issue #724

---

collector/config.go
collector/config/sample_config.json
collector/generic_collector.go
collector/generic_collector_test.go
info/v1/metric.go

Renamed units to data_type in collector config.
Use units for actual display units eg MB/s, "number of connections".

Add units and data type to spec for custom metrics.

---

manager/container.go

Centos 6 uses a different ps lib resulting in different output.

Fix cgroup name parsing logic in ps output for centos6.

---

collector/prometheus_collector.go

We'll re-enable it when we have a better way in UI to handle these.

Ignore NaN values in collection.

---

manager/container.go

housekeeping function is invoked 1sec(default) even if system time changed greatly.
let's suppose that cadvisor is running on a vm and the vm is about to be suspended for 1 day,
and, after 1 day, vm is resumed.
At the moment, cadvisor runs at full speed, because nexthousekeeping is current housekeeping + 1sec.
Therefore, cadvisor collects stats 1day * 24hours * 60minutes * 60seconds times without sleep.
In my systems, cadvisor occupies 100% cpu time almost for 3 hours.
soluton:
If cadvisor notices time change(allowedHouseKeepingGap or higher), cadvisor has to adjust nexthousekeeping.
I implemented this patch with allowedHouseKeepingGap constant.
Signed-off-by: Jin-Hwan Jeong <jhjeong.kr@gmail.com>

issue: high cpu usage

---

manager/manager.go
metrics/prometheus.go

Fix two places where `glog.Warning` is used with a formatted string.

glog.Warning -> glog.Warningf

---

integration/framework/framework.go
integration/tests/api/attributes_test.go
manager/manager.go

This PR changes how VersionInfo is served
old: lookup/create and cache the version info at manager creation time
new: lookup/create the version info each time it is requested
This is necessary to correctly report the VersionInfo in the event that the docker daemon is not running at the time the manager is created.  This case may be encountered when cAdvisor is started in the same program that initializes the docker daemon / container bridge.

Always to a live lookup of version info instead of caching.

---

container/docker/handler.go

Docker still reports a loop device for these. Need to check for
more than one device to mark network as available.

Fix network info for docker containers running with --net=host.

---

api/versions.go
api/versions_test.go
info/v2/container.go

They will be useful in kubelet, since we want to expose instantaneous data in cores instead of accumulated data in seconds.
CC @vishh @vmarmol @rjnagal

Add instantaneous cpu metrics

---

container/docker/handler.go
info/v1/container.go
info/v2/container.go
manager/manager.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

Fixes #848 
As discussed in https://github.com/google/cadvisor/pull/780#issuecomment-134657301, this just exports the image name as this has most immediate value. We can discuss docker labels separately perhaps?

Add image name to container spec & prometheus metrics

---

pages/docker.go

The links on the docker pages do not work when running under a different context. Links to static content is one level too high (`../../static/`) and container links are defined absolute `http:/xxx/docker/...`.
This PR makes the `/docker` pages behave the same way as `/containers`.

use relative links on docker pages

---

utils/oomparser/oomparser.go

Hi guys,
I have a problem when my application sends many logs for journald, the command "journalctl -f" generates a high consumption of CPU. In some cases killing the journald.
I added the flag -k in journalctl to show only the kernel logs.
Do you see any problem in this change?
Thanks

Add flag -k to journalctl show only kernel messages

---

CHANGELOG.md
version/version.go

Didn't notice that we already had a tag for 0.17.0 from last week.
Let's skip that and move to 0.18.

Make release 0.18.0

---

pages/docker.go

A few missed links when running cadvisor under a different path, behind nginx or in a kubelet.

Fix docker containers relative links

---

manager/container.go

In case we have devices hierarchies mounted in named cgroup
or together with other hierarchy regexp parse will fail.
So after "devices" and before ":" can be name of cgroup or
other hierarchies names.
E.g.:
1) remount cgroups:
umount /sys/fs/cgroup/devices
mkdir /sys/fs/cgroup/named_cgroup
mount -n -t cgroup -o devices,name=named_cgroup cgroup
/sys/fs/cgroup/named_cgroup
2) add some task to nested device cgroup and check ps output
mkdir /sys/fs/cgroup/named_cgroup/test.slice
sleep 1000 &
[1] 22734
echo 22734 > /sys/fs/cgroup/named_cgroup/test.slice/tasks
ps -ao pid,cgroup | grep 22734
22734
14:devices,name=named_cgroup:/test.slice,1:name=systemd:/user.slice/user-1000.slice/session-1.scope
Signed-off-by: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>

Make getCgroupPath work in case of named or multi- hierarchies

---

container/docker/factory.go
container/docker/handler.go

When running with the `docker_only` flag, the manager will keep trying to find a handler for the "ignored" raw containers during the housekeeping (every minute.) Each time a container is passed to the docker driver it will send an inspect request to the Docker daemon, resulting in loads of log messages:
```log
Jul 18 19:18:45 hactar docker[1024]: time="2015-07-18T19:18:45+02:00" level=info msg="+job container_inspect(rsyslog.service)"
Jul 18 19:18:45 hactar docker[1024]: no such id: rsyslog.service
Jul 18 19:18:45 hactar docker[1024]: time="2015-07-18T19:18:45+02:00" level=info msg="-job container_inspect(rsyslog.service) = ERR (1)"
Jul 18 19:18:45 hactar docker[1024]: time="2015-07-18T19:18:45+02:00" level=error msg="Handler for GET /containers/{name:.*}/json returned error: no such id: …
```

Reduce the amount of bad Docker.inspects when using docker_only flag in combination with Systemd

---

cadvisor.go
http/handlers.go
metrics/prometheus.go
metrics/prometheus_test.go

This helps with the prometheus metrics in Kubernetes where the container name has info on namespace, pod name & container name. Disabled by default, but useful when embedded inside another app, like the kubelet.
/cc @vishh

Registration of custom function to map container name to prometheus labels

---

fs/fs.go
fs/fs_test.go

Forked off from #907. Reduced the scope to just updating nice value.
Fixes #898 temporarily.

Reduce cpu priority for `du`

---

utils/machine/machine.go

Signed-off-by: Yazen Ghannam <yazen.ghannam@linaro.org>

ClockSpeed not defined in /proc/cpuinfo for AArch64, so return 0.

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/golang/glog/glog.go

I tried to pull #966 and then update the kubernetes' Godep to use runc/libcontainer, found that kubernetes' glog is newer there. 
So would like to make this update in cadvisor to make it easier to bump godeps in kubernetes (otherwise will have to update a bunch of packages by hand instead of `rm -fr Godeps/, godep save ./...`

Godeps: Update glog version.

---

container/raw/handler.go

Minor rename for my benefit as I misunderstood the purpose of the function in a review.

Rename readInt64 -> readUInt64 for clarity

---

api/handler.go
container/docker/factory.go
container/libcontainer/helpers.go
fs/fs.go
integration/common/gce.go
manager/container.go
metrics/prometheus_test.go
utils/machine/machine.go
utils/machine/topology_test.go
utils/oomparser/oomparser.go
utils/sysinfo/sysinfo.go

Cleaned up some areas where regexps were either messy or unnecessary.

Regexp tidy up

---

manager/machine.go
manager/manager.go

Fixes #955 
This is a quick fix, we need to do a full clean-up sometime of filepaths when running in a container rather than passing `inHostNamespace` everywhere, but this is good enough for now IMO.

Fix machine ID file path when running in container

---

info/v1/container.go

In commit https://github.com/google/cadvisor/commit/6818ac9b9f873fd037f7bcc75c6eada7d03c8406, the comment for function ContainerInfoRequest didn't change.

comment fix for function ContainerInfoRequest

---

container/docker/handler.go

cf0adcc817e422e86966a24a1dc758369f3c076f introduced two switch
statements to facilitate the addition of the `overlayStorageDriver`;
unfortunately neither of them conform to the Go switch semantic, which
does not fallthrough unless explicitly requested. In one case this was
innocuous (because a `break` was effectively the same as a no-op) but in
the other it would cause the `HasFilesystem` bool to not be set
appropriately in the case of `aufsStorageDriver` being used.
IMHO it's also more idiomatic to perform the default behaviour in the
default case rather than pre-setting and overriding it.

Fix case statements dealing with storageDriver

---

cadvisor.go
docs/runtime_options.md

Make the `/debug/pprof` as developing level endpoints.
When the cAdvisor is used as a product, the users should not get the debug info, such as `profiler`.  So this patch adds a new tunable option `profiling`, by default, it will disable the profiling.

make profiling tunable

---

collector/config/sample_config_prometheus_filtered.json
collector/prometheus_collector.go
collector/prometheus_collector_test.go
docs/application_metrics.md

Previously, the Prometheus collector ignored the list of metrics specified in the custom metrics config, and just collected and stored all metrics.  This makes the Prometheus collector skip metrics that aren't listed.
Also included is a tweak to the custom metrics documentation.
Fixes #1005

Fix Prometheus Metrics Filtering

---

manager/container.go

If in getCgroupPath in cgroups we have some other hierarchies after
"devices" using ".*" will cause matching wrong string as a container path
so we need to prefer fewer matches here with ".*?".
e.g.
If cgroups is 14:devices,name=named_cgroup:/test.slice,1:name=systemd:/user.slice/user-1000.slice/session-1.scope
match[1] will be /user.slice/user-1000.slice/session-1.scope
but not /test.slice as intended.
These fixes the commit:
4cbd91c761 Make getCgroupPath work in case of named or multi- hierarchies

Fix cgroupPathRegExp to match path after the first colon after devices

---

.travis.yml
build/build.sh
docs/build.md

As discussed in https://github.com/google/cadvisor/pull/992#issuecomment-165908173 this makes 1.5 a requirement of using the build tooling (`make`) & disables the 1.4 build for travis (`vet` now doesn't support 1.4 any more so this works around this issue too).
/cc @vishh

Make Go 1.5 a requirement

---

storage/influxdb/influxdb_test.go

```
$ godep go test -v github.com/google/cadvisor/storage/influxdb -tags influxdb_test
storage/influxdb/influxdb_test.go:112: undefined: New
storage/influxdb/influxdb_test.go:131: undefined: New
storage/influxdb/influxdb_test.go:184: undefined: New
storage/influxdb/influxdb_test.go:253: undefined: New
FAIL	github.com/google/cadvisor/storage/influxdb [build failed]
godep: go exit status 2
```
```
$ godep go test -v github.com/google/cadvisor/storage/influxdb -tags influxdb_test
=== RUN   TestContainerFileSystemStatsToPoints
--- PASS: TestContainerFileSystemStatsToPoints (0.00s)
=== RUN   TestContainerStatsToPoints
--- PASS: TestContainerStatsToPoints (0.00s)
PASS
ok  	github.com/google/cadvisor/storage/influxdb	0.005s
```

fix compile issue of influxdb test

---

container/docker/factory.go
container/docker/handler.go
info/v1/container.go
info/v2/container.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

This rebase the patch in #780 and add a few more fixes:
- fix regex in test to do the correct thing
- sanitize all label name before setting them as prometheus label

Carry #780: Export env variables as prometheus labels

---

container/container.go
container/docker/handler.go
container/mock.go
container/raw/handler.go
manager/container.go
manager/manager.go

Reported in kubernetes/kubernetes#19633
/cc @vishh @timothysc

Fix FS usage goroutine leaks

---

manager/container.go

per https://github.com/google/cadvisor/issues/1053 adding jitter to housekeeping intervals similar to what is done internally in kubernetes.  
@jimmidyson @vishh

Add jitter to housekeeping interval

---

fs/fs.go
fs/fs_test.go

- If the Docker storage driver is devicemapper, and the devicemapper device is *not* loopback, fix
an issue where the device associated with the / mount point was being assigned LabelDockerImages,
instead of the devicemapper device
- If the devicemapper device is a loopback device, don't assign it LabelDockerImages; instead,
report the underlying partition's information
Fixes #944

Fixes for devicemapper partition reporting

---

info/v1/machine.go
info/v2/machine.go
utils/machine/machine.go

Fix https://github.com/google/cadvisor/issues/1065

Use uint64 for Memory Stats

---

container/docker/handler.go

Fix for change in #1023
Somehow i missed this commit when making the change request. Fixes the following error
```
panic: assignment to entry in nil map
goroutine 108 [running]:
github.com/google/cadvisor/container/docker.newDockerContainerHandler(0xc82013c480, 0xc82042cf9a, 0x5b, 0x7fa188edd9f8, 0xc820001c80, 0x7fa188ed8b20, 0xc8201b3
3f0, 0xc8202881e7, 0x7, 0xc820019c48, ...)
/var/lib/docker/work_repos/gocode/src/github.com/google/cadvisor/container/docker/handler.go:163 +0x11f2
github.com/google/cadvisor/container/docker.(*dockerFactory).NewContainerHandler(0xc820019c20, 0xc82042cf9a, 0x5b, 0xc820345a01, 0x0, 0x0, 0x0, 0x0)
/var/lib/docker/work_repos/gocode/src/github.com/google/cadvisor/container/docker/factory.go:135 +0x17e
github.com/google/cadvisor/container.NewContainerHandler(0xc8 …
```

Initialize env mapping for labels when creating docker container

---

Makefile
api/versions.go
client/v2/client.go
container/docker/factory.go
container/docker/handler.go
container/docker/handler_test.go
info/v2/conversion.go
integration/framework/framework.go
integration/runner/runner.go
integration/tests/api/docker_test.go

Updated the v2.1 `/stats` endpoint to return `map[ContainerName]v2.ContainerInfo` instead of just `map[ContainerName]v2.ContainerStats`. 
Still Pending: Documenting the v2 API.
cc @pwittrock

Track fs usage for docker versions >= 1.10

---

container/raw/handler.go
info/v1/container.go
info/v2/container.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

This adds support for the CPUQuota cgroup limit.
This actually does not work , i miss something, any hints?

add support for cgroup  CPUQuota  and CPUPeriod prometheus limit

---

client/v2/client.go
container/docker/factory.go
container/docker/handler.go
container/docker/handler_test.go
integration/tests/api/docker_test.go

@jimmidyson: Here's an alternate approach to fix #1094.
PTAL. It works with docker v1.10 device mapper backend on my workstation.

Fix fs stats handling for non-aufs storage drivers.

---

client/README.md
client/client.go
client/v2/README.md

Fixes the worst of https://github.com/google/cadvisor/issues/997, but the overall documentation needs more work.
The documentation could use a complete rewrite with some additional examples, but I think it would be better to do that through better method comments, and directing users to the [godoc](https://godoc.org/github.com/google/cadvisor/client) instead.

Fix out of date client/README.md

---

integration/tests/api/docker_test.go

use http to avoid not ssl support for wget in busybox

---

fs/fs.go

Presently, if the cmd returns and error the function immediately returns and doesn't stop the timer, leading to a stray timeout message a minute later for a command the has long since failed.

avoid stray timeout message

---

info/v1/machine.go
utils/cloudinfo/aws.go
utils/cloudinfo/cloudinfo.go

This came to my attention when debugging startup time of the kubelet when not on a cloud.
I would like to get this into kubernetes if possible as it negatively impacts our ability to test kubelet in its current state.
/cc @vishh @dchen1107

Cadvisor hangs on startup

---

cadvisor.go
cadvisor_test.go
manager/manager.go
manager/manager_test.go

kubelet would like to be able to set the ignore metrics but currently this is only supported when invoking cadvisor from the command line.
This allows the caller of manger.New() to pass in a set of metrics to ignore, falling back to the defaults if none are provided.
cc @ncdc @derekwaynecarr

allow ignoreMetrics in new manager

---

integration/runner/runner.go

Will make parsing errors such like the following much easier:
```
F0405 05:38:38.584447   18226 runner.go:290] Error 0: error on host e2e-cadvisor-coreos-beta: command "godep" ["go" "test" "--timeout" "15m0s" "github.com/google/cadvisor/integration/tests/..." "--host" "e2e-cadvisor-coreos-beta" "--port" "8080" "--ssh-options" "-i /home/jenkins/.ssh/google_compute_engine -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no"] failed with error: exit status 1 and output: "godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists\nE0405 05:37:13.574085   26077 framework.go:335] About to run - [ssh -i /home/jenkins/.ssh/google_compute_engine …
```

Don't escape e2e test command output in error messages

---

container/docker/factory.go
container/docker/handler.go
manager/manager.go
validate/validate.go

- Synchronize `Validate` policy with docker `factory.go` checks
- Don't enforce `ExecutionDriver == "native"` for docker >= v1.11

Fix cAdivsor docker validation

---

utils/cpuload/netlink/netlink.go
utils/cpuload/netlink/reader.go

This is a very simple patch, but I've run into the issue described in the commit message when running the load tests described in #1188. This is, however, not a testing-only problem, as I've needed this patch to roll out a shorter collection interval for load probes in production.
The refactoring (of `getLoadStats`) is here to make it clearer that `getLoadStats` is effectively borrowing the open file and not just a number (i.e. it's important  that the file stays open while `getLoadStats` runs, otherwise we'll use an invalid FD, or even FD that refers to another cgroup..!). There isn't a great way to check that the FD is actually valid (that I know of), though. 
I'm happy to provide a much simpler version of that patch (https://github.com/aptible/cadvisor-factory/blob/master/patches/0009-N …

Netlink: aggressively close cgroup fds

---

build/integration.sh
container/docker/handler.go
integration/runner/runner.go
integration/tests/api/docker_test.go

Regressed in https://github.com/google/cadvisor/pull/1213
Added an integration test to catch this in the future.
Thanks @sjpotter for spotting this!

Fix docker GetSpec to include image, labels, and env vars

---

container/rkt/client.go

Attempts an initial connection to the rkt api service via the golang net api.  Only try grpc if that succeeds.

Dont block on grpc if nothing is listeing on rkt api service port

---

container/systemd/factory.go
manager/manager.go

Fixes https://github.com/google/cadvisor/issues/1211
/cc @vishh @pmorie - per our conversation today, this is really basic for now.
FYI @ncdc @smarterclayton  - This was the source of random errors when invoking the kubelet summary stats api when tearing down or bringing up new containers on the node.  Putting this on your radar if you see any other reports, but I suspect I was the one primarily exercising this API right now.

on systemd, we should ignore .mount cgroups

---

storage/influxdb/influxdb.go

This contribution adds the docker labels to the tags for influxdb.  This is handy to filter out or distinguish data points based on custom criteria (is it staging or production?  is it version 0.1 or 0.2? etc).

Adds docker labels to tags for influxdb storage

---

README.md
docs/elasticsearch.md

It's strange that there is not docs about ES storage driver. It would be useful for me.

Add docs about using elasticsearch as a storage driver

---

utils/machine/machine.go

Follow the same behaviour as aarh64 and s390/x
Signed-off-by: Dennis Gilmore <dennis@ausil.us>

ClockSpeed not defined in /proc/cpuinfo for 32 bit arm, so return 0.

---

build/build.sh

Fix error: `cannot install, GOBIN must be an absolute path`

Fix build for go 1.6

---

cadvisor.go
cadvisor_test.go

1. Fix for writing to nil map when value is non-empty.
2. Fix the usage string: go flag package uses backticks for the flag
name.
3. Render the flag default value in the same format as the flag accepts.

Fixes for --disable_metrics flag

---

Godeps/Godeps.json
docs/storage/README.md
docs/storage/kafka.md
storage/kafka/kafka.go

This pull requests adds the optional TLS client authentication to the kafka storage driver.

add optional TLS client auth to Kafka storage

---

utils/cloudinfo/aws.go

Because openstack and aws uses the exact same api,
the previous method to check for if running on aws
would have returned true on openstack as well.

cloudinfo: bugfix openstack identified as aws

---

container/container.go
container/docker/factory.go
container/docker/handler.go
container/factory.go
container/factory_test.go
container/mock.go
container/raw/factory.go
container/raw/handler.go
container/rkt/factory.go
container/rkt/handler.go
container/systemd/factory.go
manager/manager.go
manager/watcher/raw/raw.go
manager/watcher/watcher.go

So this PR is about trying to enable other methods of identifying container creation that can run in parallel with cgroup based detection as well as enabling one to override a cgroup based detection handler (either to operate outside the cgroup hierarchy, as might be case with VMs) or simply override the cgroup based handler.
idea is to use get it so the we an determine when rkt pods are created not via cgroup creation but via the rkt api service itself.

Refactor container watching out of raw handler into its own inteface / package

---

build/build.sh

Build releases with:
```
RELEASE=true build/build.sh
```
Differences in release mode are:
- Don't use cached build artifacts (`go build` instead of `go install`)
- Don't include hostname in the binary, use git email instead
- Day (instead of second) granularity for the BuildDate

Add 'release mode' to build script

---

utils/oomparser/oomparser.go

SteamOoms() blocks on a chan receive on the last line of the OOM kernel message block here:
https://github.com/google/cadvisor/blob/master/utils/oomparser/oomparser.go#L124
This results in the oom event not being reported until another kernel log line comes in after the oom block.

fix chan recieve block on oom event

---

api/versions.go
manager/manager.go
manager/manager_test.go

This is a slight change in behavior, as cases that would previously return `nil, err` will now include a non-nil result. It is common go practice to ignore the result if there's an error so this shouldn't existing users. However, to take advantage of the partial results will require a code change in most cases.
The exception is `GetRequestedContainersInfo`, which was discarding the errors and returning the partial result, and now returns a `partialFailure`. The change in behavior is reflected in `api/versions.go`, which now needs to check for a result and handle the error in that case.
Addresses https://github.com/kubernetes/kubernetes/issues/25131

Make manager multi-container functions robust to partial failures

---

manager/container.go
manager/container_test.go
manager/manager.go
manager/manager_test.go
utils/cpuload/cpuload.go

This ensures each goroutine is given its own Netlink connection, and presumably avoids having a message destined for one goroutine read by another goroutine. 
This does means cAdvisor will use a larger number of connections (one per container being tracked), but I don't see any locking or serialization taking place in `cpuload`, so that seems like the lesser of two evils (the other evil being racy behavior).
I'm going to be running this patch on our end for a little while, but I'd be curious to know if you have feedback to provide so far! 
I presume this might address the issue I've reported in https://github.com/google/cadvisor/issues/1182 and https://github.com/google/cadvisor/issues/452, as well as another issue we've been experiencing here at Aptible (but haven't reported yet), where …

Use a dedicated CpuLoadReader per container

---

utils/oomparser/oomparser.go
utils/tail/tail.go

Fixes #1248
Add some "tail -F" support (via polling and reopening) so that cadvisor can continue to track kernel log messages across log rotations.
Looked at doing this with fsnotify but 1) fsnotify depends on golang.org/x/sys/unix and that is about 10k LOC and 2) I couldn't find a tail implementation that actually worked with fsnotify.

add log file tailing and logrotate support

---

manager/manager.go
manager/manager_test.go

This slipped through the cracks because `require.NoError` handles nil interfaces differently from a standard `err != nil` check (filed https://github.com/stretchr/testify/issues/311).

Fix nil-interface partialFailure bug

---

build/build.sh

Link cAdvisor statically.

---

collector/prometheus_collector.go
collector/prometheus_collector_test.go

We were experimenting with custom metrics earlier today. When we enabled it on one of our kubelets the next time our prometheus server polled the cadvisor endpoint for metrics the kubelet paniced.
The panic that we got in the logs started with this:
```
panic: runtime error: slice bounds out of range
goroutine 602 [running]:
github.com/google/cadvisor/collector.(*PrometheusCollector).GetSpec(0xc2082f2d20, 0x0, 0x0, 0x0)
/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/google/cadvisor/collector/prometheus_collector.go:129 +0x7bc
github.com/google/cadvisor/collector.(*GenericCollectorManager).GetSpec(0xc20888a660, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/google/cadvisor/collector/collector_manager.go:67 +0x118 …
```

Fixes a panic when a prometheus endpoint ends with a newline

---

info/v2/conversion.go
info/v2/conversion_test.go

For https://github.com/kubernetes/kubernetes/issues/27194.
The current implementation of `InstCpuStats` will sometimes cause data overflow. (See [detail](https://github.com/kubernetes/kubernetes/issues/27194#issuecomment-226355934))
Without this change, when `valueDelta` is `18949414524`, `timeDeltaNs` is `17978530662`, it will return `27959484`, with this change it will return `1054002403` correctly.
I also removed the dead code `instCpuStats`.
@dchen1107 
/cc @timstclair @vishh

Fix uint64 overflow in info/v2/conversion.go.

---

manager/manager.go

It is not an error to fail to register the Docker factory on a system
running only rkt, and vice-versa, so these failures are downgraded from
an Error to a Warning. The raw handler should always be registered.
/cc @sjpotter

Downgrade failure to rgeister runtime factory to warning

---

container/docker/factory.go
utils/docker/docker.go

@derekwaynecarr @aveshagarwal @pmorie @ncdc 
In systems that have an LVM managed docker thin pool, docker info does not contain information for the data or metadata devices:
```
$ docker info
..
Storage Driver: devicemapper
Pool Name: fedora-docker--pool
Pool Blocksize: 524.3 kB
Base Device Size: 107.4 GB
Backing Filesystem: xfs
Data file: 
Metadata file: 
...
```
LVM puts the metadata device at /dev/mapper/<poolname>_tmeta.  If we fail to get the metadata device from the docker info, we should fall back to the LVM path.
Fixes #1338

fallback to /dev/mapper device if metadata device is not set in docker info

---

devicemapper/thin_pool_watcher.go
devicemapper/thin_pool_watcher_test.go

Because new versions of devicemapper may add additional fields to the output of 'dmsetup status',
change the check to use SplitN to get the minimum fields required, and ignore any additional fields
after the one we care about.
Ref https://github.com/kubernetes/kubernetes/issues/27955
@derekwaynecarr @sjenning @pmorie

Fix detection of devmapper metadata reservation

---

devicemapper/thin_pool_watcher.go
devicemapper/thin_pool_watcher_test.go

Cherrypick https://github.com/google/cadvisor/pull/1348 to v0.23
Because new versions of devicemapper may add additional fields to the output of 'dmsetup status',
change the check to use SplitN to get the minimum fields required, and ignore any additional fields
after the one we care about.
@ncdc @timstclair @yujuhong

Cherrypick #1348: Fix detection of devmapper metadata reservation

---

info/v2/container.go
manager/manager.go

This info helps Kubelet decide on declaring OutOfDisk

Including the number of free inodes in FsInfo

---

build/jenkins_e2e.sh

Update jenkins_e2e.sh to match the up-to-date configurations of the
cAdvisor jenkins PR-builder and CI jobs. Once this is merged, we can
update those jobs to call this script instead.
/cc @vishh @ixdy

Update jenkins script to match job configs

---

Makefile
build/build.sh
build/integration.sh

The integration test script was changed so that it aborts the testing
when the cAdvisor binary exits with a non-zero error code.
Also in this PR:
- clean up makefile to print more informative output
- change make release to build the release binary
I will follow up with another PR to enable the race detector on the jenkins jobs.

Run the integration tests locally with the race detector enabled

---

fs/fs.go
fs/fs_test.go

Exclude Docker devicemapper mounts from the list of filesystem partitions (e.g.
/var/lib/docker/devicemapper/mnt/*) because these are handled by the ThinPoolWatcher for
per-container filesystem information.
Fixes #1048
@derekwaynecarr @sjenning @timstclair @vishh @jimmidyson @rhvgoyal @pmorie

Exclude Docker devicemapper mounts from fs info

---

container/container.go
container/docker/handler.go
container/raw/handler.go
container/rkt/handler.go
container/testing/mock_handler.go

Adds support to the handler to be able to fetch the ip address of a container and the files from within a container.
Support added for docker containers, but if someone knows more about the raw or rkt containers, they should also be updated to add in this support.
Being able to fetch the ip address of container is essential for supporting custom metrics. Without this we need to be able to know the ip address before starting the container. This is especially cumbersome with kuberentes as it requires setting up hostports and manually managing each container that wants to expose metrics. The support added here will work with both plain docker images and kubernetes pods.
Note: this is in piece of the PR sent for https://github.com/google/cadvisor/pull/1328 as it has been deemed more …

Add support to the handler to support fetching the ip address and files

---

collector/config.go
collector/config/sample_config_endpoint_config.json
collector/config/sample_config_prometheus_endpoint_config.json
collector/generic_collector.go
collector/generic_collector_test.go
collector/prometheus_collector.go
collector/prometheus_collector_test.go
collector/util.go
manager/manager.go

Allows collectors to directly use the ip address of containers.
This means that custom metrics no longer have to know the ip address of the container before they are deployed.
In Kubernetes environments, it greatly makes handling custom metrics much easier. We no longer have to deal with special permissions for hostports and we can now deploy multiple pods of the same type without having to manually manage the ports in use.

Update collectors to be able to directly use the ip address of containers

---

container/libcontainer/helpers.go

Change working set calculation to usage - total_inactive_file, rather than usage - total_inactive_anon - total_inactive_file. Since writes to tmpfs get tracked as total_inactive_anon when swap is disabled, the old calculation would under-report memory pressure.
See these for context:
https://github.com/kubernetes/kubernetes/issues/28619
https://github.com/kubernetes/kubernetes/pull/28693
cc @vishh @timstclair

Modify working set memory stats calculation

---

cadvisor.go
collector/generic_collector.go
collector/generic_collector_test.go
collector/prometheus_collector.go
collector/prometheus_collector_test.go
manager/manager.go
manager/manager_test.go

Updates collectors to use a customized httpClient.
This client has been configured to be able to read from https endpoints which in which cAdvisor cannot entirely trust. For instance, in the case of endpoints where its secured with self signed certificates or do not have the right ip address as part of the certificate. We do not need to verify that endpoints have properly certificates, this is just to make reading endpoints regardless if they are http or https based.
Expose as a configuration option the ability to specify a certificate to be used by the collectors when accessing endpoints. This means that endpoints can be configured to be use client certificate based authentication, allowing endpoints to only allow access to custom metrics if they trust the cAdvisor certificates.

Update collectors to use a customized httpClient.

---

metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics_failure

This fixes an issue where errors during Prometheus metrics collection would stay counted in the gauge `container_scrape_errors`, making that particular metric useless. Instead, it must be reset on
every scrape.

Fix for Prometheus metric "container_scrape_errors" getting stuck

---

info/v2/conversion.go

Go reuses memory, so the result was that things that took the pointer value of `stat` would get a random result from a different `filesystem` for available, capacity, etc.  It caused the output of `/v2.1/machinestats` to just be really wrong and confusing ;-)
/cc @ronnielai @vishh @timstclair @ncdc @pmorie

filesystem usage stats are wrong in v2 api

---

metrics/prometheus.go
metrics/testdata/prometheus_metrics

Fixes #1279. Supersedes #1315 (it's become inactive sadly).
@grobie What do you think? I decided to go with consistent, plain `docker_{label,env}_` prefix as the actual Docker label itself will (should) be namespaced. This also fixes a potential for conflicts in env vars used in Prometheus labels.

Prefix Docker labels & env vars in Prometheus metrics to prevent conflicts

---

container/raw/handler.go
container/raw/handler_test.go
info/v1/container.go
info/v2/container.go
manager/manager.go

Our operators want to support inode-based disk eviction policies in Kubernetes as a percentage of available inodes rather than a fixed value.  In order to support building a percentage, we need to expose total inodes and inodes free.
Related: https://github.com/kubernetes/kubernetes/pull/28501
/cc @vishh @ronnielai @ncdc @pmorie

Expose total inodes

---

container/libcontainer/helpers.go
info/v1/container.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

If CPU quota is configured (cpu.cfs_quota != -1) the CFS will provide
stats about elapsed periods and throtting in cpu.stats. This change
makes these information available as container_cpu_cfs_* metrics.
Fixes #1337
@chbatey @matthiasr @rtreffer

Expose cpu cgroup CFS prometheus metrics

---

container/docker/factory.go
container/docker/factory_test.go

Cherry pick for v0.23: https://github.com/google/cadvisor/pull/1411
End goal is to get this fix into Kubernetes 1.3 release
@ncdc @timstclair @vishh

Ensure minimum kernel version for thin_ls

---

container/libcontainer/helpers.go
info/v1/container.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

Hi ,
this adds the swap information from memory.stat and exports this via prometheus metrics.
Question: Atm this is implemented with the memory.stat file, maybe ists better to use memory_usage_in_bytes and memsw_usage_in_bytes ?
regards f0

add cgropu swap usage and export as prometheus metric

---

CHANGELOG.md
docs/storage/README.md
docs/storage/prometheus.md

prometheus.io is HTTPS only for some time now.

Update prometheus.io URL

---

http/handlers.go
metrics/prometheus.go
metrics/prometheus_test.go

This change generalizes the existing ContainerNameToLabelsFunc to allow the user to fully control all labels attached to exported Prometheus metrics. The existing behavior is available as DefaultContainerLabels and is used if no custom function is provided.
This will allow Kubernetes to filter out its internal Docker labels.
Fixes #1312. Once Kubernetes provides a custom function to filter its internal labels implemented in kubernetes/kubernetes#31064.
PTAL @jimmidyson @fabxc @vishh @timstclair 
@vishh Tim and I discussed that the current label settings classify as bug and that this should be included in Kubernetes v1.4.

Provide option to control Prometheus labels

---

metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

Add inodes to /metrics endpoint

---

pages/assets/styles/containers.css

No one likes horizontal scrollbars.
Before:
After:

Cosmetic styling change: break long words in container name title

---

CHANGELOG.md

Dropped 82ce4ff6fc8747773cc62c5d0e9dcfcbf4011650 - Update prometheus.io URL, since it includes other changes.
I will cut the v0.24 release once this is merged.
/cc @vishh @sjenning @dchen1107 @ncdc

Cherry-pick changelog into release-v0.24 branch

---

Godeps/Godeps.json
container/libcontainer/helpers.go
vendor/github.com/opencontainers/runc/libcontainer/README.md
vendor/github.com/opencontainers/runc/libcontainer/SPEC.md
vendor/github.com/opencontainers/runc/libcontainer/cgroups/cgroups.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuset.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/devices.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unix.go
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runc/libcontainer/configs/device_defaults.go
vendor/github.com/opencontainers/runc/libcontainer/container.go
vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go
vendor/github.com/opencontainers/runc/libcontainer/generic_error.go
vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
vendor/github.com/opencontainers/runc/libcontainer/keys/keyctl.go
vendor/github.com/opencontainers/runc/libcontainer/label/label_selinux.go
vendor/github.com/opencontainers/runc/libcontainer/process_linux.go
vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
vendor/github.com/opencontainers/runc/libcontainer/setns_init_linux.go
vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_386.go

Fixes https://github.com/google/cadvisor/issues/1461
- update the libcontainer dependency.
- look at all cgroup mounts

Fix running cAdvisor in container on RHEL systems

---

collector/prometheus_collector.go
collector/prometheus_collector_test.go
info/v1/metric.go
manager/manager_test.go

Fixes #1472
@fabxc This is a hand-rolled parser to collect application metrics from containers. Forgetting the question or application metrics & cadvisor, I assume the better approach for this would be to use Prometheus' own parser? If so, can you point me to it please?

Switch to Prometheus decoders for Prometheus custom metric endpoint parsing

---

collector/config.go
collector/generic_collector.go
collector/generic_collector_test.go
collector/prometheus_collector.go
collector/prometheus_collector_test.go
container/rkt/handler.go
info/v1/container.go
storage/influxdb/influxdb_test.go
storage/redis/redis.go
storage/statsd/statsd.go
utils/cloudinfo/azure.go
utils/cloudinfo/cloudinfo.go
utils/tail/tail.go

A pet peeve, comments // should be proceeded by a space for greater consistency.

Cleanup comment style: // should be proceeded by a space

---

container/common/fsHandler.go
container/docker/handler.go
container/rkt/handler.go
fs/fs.go
fs/fs_test.go
fs/types.go
info/v2/container.go
info/v2/conversion.go
info/v2/conversion_test.go

Per-container stats available in the v2 api in the FileSystemStats.InodeUsage field.  They are available in the v1 stats in the Filesystem.Inodes field.  Per-container Inode stats collected using the command "find . -xdev | wc -l".  The collection of inode stats uses the same back-off strategy as measuring per container bytes used, so that slow calls to find do not severely impact performance.

Cadvisor now publishes per-container inode stats

---

fs/fs_test.go

Tests relied on timeouts, and were subject to flakes.  They have been removed.
Fixes https://github.com/google/cadvisor/issues/1500

removed flaky test

---

cadvisor.go
fs/fs.go
fs/fs_test.go
manager/manager.go
manager/manager_test.go

Cadvisor allows the RootPath to be configured.  The RootPath is used to determine which filesystem is the RootFs.

Cadvisor Configure Root Path

---

cadvisor.go
fs/fs.go
fs/fs_test.go
manager/manager.go
manager/manager_test.go

Undo this commit
This reverts commit 719df516db2581e41a753f739148c46aebb4cd4a, reversing
changes made to cae5bfaee63f62fdf374519f04bf24e02a742f87.
We decided that we could get filesystem information from the filesystem that contains a specific path in a better way.

Revert "Merge pull request #1503 from dashpole/configure_root_path"

---

manager/manager_test.go

This was probably due to a change in go vet.  It does not allow Mutex's to be copied.  Testify.Mock contains a Mutex, and cannot be copied.  Because of this, we cannot change a testify.Mock object after it is added to a list for all viewers of the list.  Since we cannot change objects after they are added to the list, I had to pass a boolean to the function that initially creates the list.  When true, the boolean causes GetSpec to return an error, rather than the normal return value, and cases Exists to return true.

fixed go vet bug

---

manager/manager.go

This will allow us to, for example, monitor the filesystem that includes /var/lib/kubelet, by calling GetDirFsInfo("/var/lib/kubelet").

added GetDirFsInfo, which returns filesystem information for the specified directory

---

manager/manager.go

Cherry-pick https://github.com/google/cadvisor/pull/1507 into the `kubernetes-1.4` branch.
/cc @vishh

[cherry-pick] added getdirfsinfo, which finds fsinfo for the filesystem containing dir

---

docs/runtime_options.md

The link to the container_hints definition was broken 😞 
I updated the link to point to the right location 😀 💥

fix broken link: container_hints definition

---

utils/tail/tail.go
utils/tail/tail_test.go

Found this bug when using the `utils/tail` package in node problem detector.
If the reader try to read right after creating `Tail`, `Read` will keep returning `0, nil`.
If it does this too many times, golang will report error [`var ErrNoProgress = errors.New("multiple Read calls return no data or error")`](https://golang.org/pkg/io/).
This PR initializes `readerErr` as `io.EOF`, so that the reader can work properly.
@AdoHe @timstclair

Fix a bug in tail.

---

fs/fs.go
info/v2/conversion.go

1. Fix https://github.com/google/cadvisor/issues/1523 - partitionRegex can not fit usual device name
2. Fix https://github.com/google/cadvisor/issues/1546 - cadvisor do gather but not copy tcpstat of container
3. Handle restarting a Manager instance. This may be necessary if a new disk device is mounted after the cAdvisor manager is started.

Fixes partion name, v2 TCP stats

---

Makefile
build/build.sh
build/release.sh
docs/development/releasing.md

I've gotten a lot of requests to share the release instructions document (publicly), so I scrubbed the google-internal details & converted to markdown. I kept a link to the internal version (which includes some details for Googlers who handle the push).

Publish public version of release instructions

---

build/boilerplate/boilerplate.py
pages/static/assets.go
pages/templates.go

This was causing build failures on git ( #1564, #1558).  We may want to consider fixing this for the future.

updated assets to 2017 using make assets

---

fs/fs.go

`GetDirInodeUsage` requires extended functionality provided by the GNU `find` implementation to work correctly. When deployed on a system with the BusyBox `find` implementation, the extra arguments are unrecognized and find terminates. (#1556, kubernetes/minikube#923, kubernetes/kubernetes#38894)
When `find` exits with an error, the wait for the `wc` process never happens and `wc` becomes a zombie. On systems without GNU find, these zombies can accrue quickly.
In lieu of a solution that would work everywhere (ie. not relying on GNU find), this PR simply replaces `wc` with a writer implementation that counts what has been written. This simplifies the code a bit and removes the pipe.

Remove pipe to wc and prevent zombie on err

---

utils/tail/tail.go

Add error log when `tail` can not open a log file. This is useful for debug. :)

add error log for open log file

---

api/versions.go
info/v2/conversion.go
info/v2/conversion_test.go
manager/manager.go

Addresses [Kubernetes #22586](https://github.com/kubernetes/kubernetes/issues/22586).  The log line in question is designed to alert users that containers cannot span multiple filesystem devices.  However, it is being triggered when gathering information for the "/" (root) filesystem device, which includes all devices on the image.  Images configured to use multiple filesystem devices (coreos, GCI, to name a few) spam the logs with the line: "conversion.go:128 failed to handle multiple devices for container. Skipping Filesystem stats"
For this particular device ("/"), kubernetes does not consume the filesystem stats, making this log message unimportant.  Lowering the verbosity level is appropriate in this case.
cc: @derekwaynecarr (I messaged you about this in december) @timstclair

Lower verbosity level for spamming log

---

container/docker/factory.go
container/docker/factory_test.go

Fixes https://github.com/google/cadvisor/issues/1572
Fixes https://github.com/google/cadvisor/issues/1510
/cc @timstclair @ncdc @smarterclayton

Ignore any .mount cgroup in docker

---

deploy/Dockerfile
devicemapper/util.go

xref
https://github.com/openshift/origin/issues/10940
https://github.com/openshift/origin/pull/12753
We should not look in `/rootfs` for the `thin_ls` binary as it is not statically linked and the dependent libraries might not be present in the container.
@derekwaynecarr @ncdc @pmorie @lukegb

do not look in rootfs for thin_ls binary

---

container/docker/handler.go

If an environment variable is an empty string, cadvisor panics and fails to start. this change enables cadvisor to start regardless of the content of environment variables.

check docker container environment variables for empty strings

---

storage/statsd/client/client.go

Error message should be logged with `glog.Errorf` instead of `glog.Infof`.
/ping @timstclair

Fix statsd error log

---

CHANGELOG.md
container/docker/factory.go
container/docker/factory_test.go

Cherrypick Ignore .mount cgroup & Release v0.24.2

---

cadvisor.go
utils/sysfs/sysfs.go
utils/sysinfo/sysinfo.go

remove second return value since it will never return err

optimize NewRealSysFs()

---

container/docker/factory.go
container/docker/handler.go
utils/docker/docker.go
zfs/watcher.go

After testing, this seems to give the most consistent view of ZFS compared to the other providers. It is a bit more code than I would like, but it is modeled after the devicemapper code.

Add watcher for zfs similar to devicemapper

---

container/docker/docker.go
container/docker/docker_test.go
container/docker/factory.go
info/v1/docker.go
info/v1/machine.go
info/v2/machine.go
manager/manager.go
pages/docker.go

Information like docker version in kubelet is used via cadvisor and there is a need now for docker api version([Issue 42492](https://github.com/kubernetes/kubernetes/issues/42492)), so submitting this PR to expose docker API version.

Add Docker API version

---

metrics/prometheus.go

Only include cpu's in the Prometheus metrics endpoint that were used.
In recent kernels the `cpuacct.statcpus` behavior has changed to include all possible cpu's. See kernel commit [5ca3726af7f66a8cc71ce4414cfeb86deb784491](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=5ca3726af7f66a8cc71ce4414cfeb86deb784491) for details.
This can results in a high number of metrics in the Prometheus endpoint. For example, with VMware ESXi the kernel detects 128 hot swappable cpu's, adding >100 metrics per container for most machines. With a couple of VM's running >10 containers this quickly blows up a Prometheus server and makes most dashboards unmanageable.

Ignore unused cpus in Prometheus metrics

---

cadvisor.go
cadvisor_test.go
container/factory.go
container/libcontainer/helpers.go
container/libcontainer/helpers_test.go
container/libcontainer/testdata/procnetudp
info/v1/container.go
info/v2/container.go

This is a first crack at adding UDP stats collection support.
One possible issue here is that the dropped packets is a coutner.
if many sockets come and go withint he container, the sum of the
dropped packet counters will not be monotonically increasing.

Add udp and udp6 network statistics

---

info/v2/conversion.go
info/v2/conversion_test.go

The `Envs` field was never being set in the v1->v2 container spec conversion.

set envs when converting to v2 spec

---

info/v2/conversion.go

This can cause excessive spam in the logs that drowns out useful messages.

Reduce cAdvisor log spam with multiple devices

---

container/common/helpers.go
container/docker/handler.go
container/raw/handler.go
container/rkt/handler.go
info/v1/container.go
info/v1/machine.go
machine/info.go
metrics/prometheus.go

Fixes #1403
PerDiskStats reported from cgroups were not being surfaced into
prometheus. In order to properly correlate the metrics, we need to
assign a device label to each metric (which is the FS or device path).
Since blkio cgroup tracks devices, we create a synthetic device
`/dev/NAME` for the metric.
Assign a Device label to each PerDiskStat for the handlers up front, and
then surface the PerDiskStat values into the prometheus metrics. Report
two new metrics - total bytes read and total bytes written.
Open questions:
- Does this add too much extra data (are there metrics we would drop?)
- Do I have the correct mapping between blkio and the Filesystem stats (at casual reading yes, but not positive)
- Do we want to add the `_bytes_total` metrics?
- Is there an equivalent to …

Report container FS metrics into prometheus /metrics

---

docs/runtime_options.md

Many flags are missing from docs/runtime_options.md. Add all missing
flags that aren't storage driver specific.
Resolves https://github.com/google/cadvisor/issues/1244

Document runtime options

---

manager/manager.go
manager/manager_test.go

Allow docker containers to be found by a short prefix name to match
the behavior of the docker daemon. This change now matches the examples
on the API docs.
Return an error if the given short, prefix name of a container is not
unique.
---
Resolves https://github.com/google/cadvisor/issues/1164
I'm not sure about all the contexts that `DockerContainer` is being called in and am slightly concerned about iterating through all the containers if an exact match is not found.
I'm pretty new to golang so I welcome all feedback.

Allow finding docker containers by short name

---

docs/storage/prometheus.md

fix centurylink labs link to prometheus integration

---

fs/fs.go

Both GetDirDiskUsage and GetDirInodeUsage do not use the fsInfo object they are called on.
This PR removes this dependency, making both functions utility functions.  This will allow kubernetes to use these functions when calculating volume disk usage, and minimize code duplication.
cc @timstclair

GetDirDiskUsage and GetDirInodeUsage now also exist as utility functions

---

container/docker/docker.go
container/docker/factory.go
container/docker/handler.go

Cache the Docker thin pool name in the dockerFactory and pass it to each Docker container handler,
instead of calling `docker info` each time a new container handler is created, as the thin pool name
is extremely unlikely to change.
@derekwaynecarr @pmorie @sjenning @timothysc

Cache the Docker thin pool name

---

fs/fs.go

Helps with the situation in kubernetes where /var/lib/kubelet is
mounted using tmpfs.

Support tmpfs in processMounts

---

metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

Hi folks,
Related to #1670  , I'd like to take a PR to expose more about `container_cpu_load_average_10s`, `container_network_tcp_usage_total`, `container_network_udp_usage_total` metric within the `/metrics` endpoint.
Currently, tcp/udp usage will be disabled via `disable_metrics` flag by default, thus `/metrics` would show zero values. Due to [ContainerSpec](https://github.com/google/cadvisor/blob/master/info/v2/container.go#L67) has no `ignoreMetrics` flag, I don't know how to handle this...
Thanks.

Add cpu load,tcp\udp usage statistics in prom `/metrics` endpoint.

---

http/handlers.go

PR https://github.com/google/cadvisor/pull/1460 upgraded prometheus to v0.8.0.
However, prometheus v0.8.0 [enforced some consistency check]( https://github.com/prometheus/client_golang/pull/214), which our current metrics could not pass, thus caused https://github.com/google/cadvisor/issues/1671 and https://github.com/kubernetes/kubernetes/issues/47744.
This PR configure prometheus http handler to `ContinueOnError` so that the metrics could be collected/exposed regardless of the error. This is also the solution suggested in https://github.com/prometheus/client_golang/pull/214.
This is only a quick fix for Kubernetes 1.7 release. We should figure out what in our metrics caused the inconsistency and fix it.
@dchen1107 @google/cadvisor @grobie

Set ContinueOnError for prometheus http handler.

---

devicemapper/thin_ls_client.go

ref:
https://godoc.org/github.com/golang/glog#Warningf
https://godoc.org/github.com/golang/glog#Warning

use glog.Warningf when a format string is passed

---

utils/oomparser/oomparser.go
utils/oomparser/oomparser_test.go

The oomparser logic would end up stuck, unable to detect the end of a
given oom trace, for any process witha a name that didn't match \w+.
This includes processes like "python3.4" due to the '.', or
'docker-containerd' due to the '-'.
This fix was included in pr #1544 last year, but since that PR seems
dead it seems like a good idea to break this more important fix out.
I've updated the test such that it would have caught this issue.

oomparser: don't get stuck for certain processes

---

info/v1/machine.go
info/v2/machine.go
machine/info.go

I plan to add support for pre-allocated huge pages in Kubernetes 1.8.
In order to add that support, I need the ability to introspect the supported set of huge pages on the node, and the number of them that are pre-allocated.
This adds that support.

Machine info introspects hugepages

---

build/build.sh

Fixes https://github.com/google/cadvisor/issues/1481
Not sure if this has side effects but `make build; ./cadvisor; <segfault>` isn't fun.

add netgo tag to fix segfault

---

machine/info.go

Attempts to merge this in kube are failing because the test nodes disable hugepages at the OS level meaning that /sys/kernel/mm/hugepages does not exist.
Treat this situation as non-fatal.
@derekwaynecarr @dashpole

make lack of hugepages support non-fatal

---

manager/container.go
manager/container_test.go
manager/manager.go
manager/manager_test.go

Currently `GetInfo()` updates both the spec and the subcontainers.  The subcontainer walk is VERY expensive as it does a stat syscall on basically every directory and file in the cgroupfs tree via `ioutil.Readdir()`.  This uses lots of CPU directly and also allocates a TON of objects that have to be GCed later, consuming even more CPU.
AFAICT, the v2 api does not need to do this subcontainer update at all since the v2 ContainerInfo doesn't have a subcontainers field:
https://github.com/sjenning/cadvisor/blob/master/info/v1/container.go#L128-L139
https://github.com/sjenning/cadvisor/blob/master/info/v2/container.go#L59-L65
The code supports this conclusion as v2 go paths look like this
```
cinfo, err := container.GetInfo(false)
...
result.Spec = self.getV2Spec(cinfo)
```
The …

Skip subcontainer update on v2 calls

---

container/libcontainer/helpers.go

I have multiple reports of this spamming logs and causing stability issues.
```
Unable to get network stats from pid 36618: couldn't read network stats: failure opening /proc/36618/net/dev: open /proc/36618/net/dev: no such file or directory
```
suspect the container process has exited but the cgroup still remained.

Reduce log spam when unable to get network stats

---

utils/oomparser/oomparser.go

This fixes the journalctl leak that occurs when a process that uses
cadvisor exits. See issues #1725 and https://github.com/kubernetes/kubernetes/issues/34965.
I tested this by changing the Kubelet configuration 100 times (which causes 100 restarts of cadvisor). After this, there were no leaked inotify nodes:
```
root@test-cos-beta-61-9765-31-0:~# for foo in /proc/*/fd/*; do readlink -f $foo; done | grep inotify | sort | uniq -c | sort -nr | awk '{print $2}' | cut -d/ -f 3 | xargs ps -p
PID TTY      STAT   TIME COMMAND
1 ?        Ss     0:01 /usr/lib/systemd/systemd noresume noswap cros_efi
383 ?        Ss     0:00 /usr/lib/systemd/systemd-udevd
516 ?        Ssl    0:00 /usr/lib/systemd/systemd-timesyncd
579 ?        Ss     0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork …
```

Fix journalctl leak

---

container/libcontainer/helpers.go

If hierarchy is enabled, we should return total_rss instead of rss when reporting container stats.
This is a follow-up to previously reported issue in kubernetes here:
https://github.com/kubernetes/kubernetes/pull/43399#issuecomment-287858599
/cc @sjenning @dashpole @vishh @smarterclayton

Expose total_rss when hierarchy is enabled

---

README.md
api/versions.go
fs/fs.go
fs/types.go
info/v2/container.go
manager/manager.go

Ref: https://github.com/kubernetes/kubernetes/issues/46984
- Added `GetFsInfoByFsUUID(uuid string) (*v2.FsInfo, error)` in the manager.
- Added timestamp into `v2.FsInfo` so that we will know when the stats are sampled.
Tested manually:
```
$ docker run --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --volume=/dev/disk:/dev/disk:ro --publish=8080:8080 --detach=true --name=cadvisor cadvisor:9e51697
$ curl http://127.0.0.1:8080/api/v2.0/storage?uuid=9eb3792d-3b9a-4e50-84e0-fb8e6119b9e1
{"timestamp":"2017-08-23T16:11:37.451208174Z","device":"/dev/dm-1","mountpoint":"/rootfs","capacity":58923675648,"available":35672920064,"usage":20234002432,"labels":[],"inodes":3662848,"inodes_free":3277799}
$ curl …
```

Add an API to get FsStats from filesystem UUID

---

container/docker/client.go
container/docker/factory.go
docs/runtime_options.md

Addresses #1631 by adding runtime options for using TLS to connect to docker. The -docker-tls flag enables TLS, the other three (-docker-tls-cert, -docker-tls-key, -docker-tls-ca) specify the keypair and CAs to use. This solution matches the existing interface in that it uses runtime options (like -docker) over environment variables (like DOCKER_HOST).
If -docker-tls is not set, the behaviour is the same as before.
Let me know if you have any feedback.

Add runtime options for TLS support

---

container/libcontainer/helpers.go
container/libcontainer/helpers_test.go

As of the 4.7 kernel, the cpustats field returned from libcontainer
contains values for every possible cpu (including nonexistent ones).
The extra values are all 0s.
If we assume that hotplug events won't happen, we can get a more
accurate cpu count by using runtime.NumCPU and then ignoring any values
beyond that.
This was reported as an issue against the CoreOS bug tracker (https://github.com/coreos/bugs/issues/2088).
I haven't tested this, but running it on AWS and looking for extra 0s before/after would apparently be a good way to see.

libcontainer: use real number of CPUs for usage

---

container/container.go
container/crio/client.go
container/crio/client_test.go
container/crio/factory.go
container/crio/factory_test.go
container/crio/handler.go
container/crio/handler_test.go
fs/fs.go
manager/manager.go

This patch adds native support for the CRI-O runtime to cadvisor.
Tested by integrating it with kubernetes and verified the necessary stats are now returned properly.
/cc @derekwaynecarr @mrunalp
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

*: add CRI-O handler

---

deploy/canary/Dockerfile

failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-cadvisor-canarypush/298
follow-up to #1751
cc @ixdy

apt-get update, not apt-cache update

---

metrics/prometheus.go
metrics/prometheus_test.go

Hi folks,
I'd like to take a PR to expose `container_spec_memory_reservation_limit_bytes` metric within the `/metrics` endpoint.
Currently, [memory reservation](https://github.com/google/cadvisor/blob/master/info/v1/container.go#L37) is collected but just not exposed to prometheus.
Thanks.

Add memory reservation in prom `/metrics` endpoint.

---

container/common/fsHandler.go

When running pod density tests on the order of 500 pods, the du operation in the fsHandler can take longer than a second, even if everything about the filesystem is cached.  This is a persistent condition that causes the message to continually print.
This PR makes `longOp` adaptive so if the long du duration is a persistent condition, the message won't continue in the logs forever.
https://bugzilla.redhat.com/show_bug.cgi?id=1498632
@dashpole @vishh @derekwaynecarr @ravisantoshgudimetla

adaptive longOp for du operation

---

container/libcontainer/helpers.go
info/v1/container.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

Expose `memory.max_usage_in_bytes` per container from memory cgroup.
Value is visible from REST API and Prometheus (container_memory_max_usage_bytes)
This is useful for understanding peak usage for a container over its life.
/cc @dashpole @sjenning @smarterclayton @dchen1107 @vishh

Container stats expose memory max usage

---

container/docker/handler.go

Fixes https://github.com/kubernetes/kubernetes/issues/52336
The directory structure of overlay2 is different from overlay, and we should monitor the contents of /var/lib/docker/overlay2/CONTAINER_ID/diff/ instead of just /var/lib/docker/overlay2/CONTAINER_ID/

Monitor diff directory for overlay2

---

container/crio/handler.go

Verified we're now reading the `diff` dir in container's storage:
```json
"rootfs": {
"time": "2017-10-13T08:27:45Z",
"availableBytes": 10798333952,
"capacityBytes": 52710469632,
"usedBytes": 90112,
"inodesFree": 2659325,
"inodes": 3276800,
"inodesUsed": 16
},
```
```sh
[root@runcom 4f4cc46320d76a12e9a833a7708ad62d5d5c8359911553cb3a25e0b12d6c3f75]# pwd
/var/lib/containers/storage/overlay2/4f4cc46320d76a12e9a833a7708ad62d5d5c8359911553cb3a25e0b12d6c3f75
[root@runcom 4f4cc46320d76a12e9a833a7708ad62d5d5c8359911553cb3a25e0b12d6c3f75]# du -s -B1 ./diff/
90112   ./diff/
```
@derekwaynecarr @mrunalp @dashpole PTAL
related to #1770 
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

CRI-O: fix handling of overlay2 storage

---

fs/fs.go

We have 400+ containers per host, each with 2GB+ container filesystems. Running cadvisor on this hosts is not possible because it get OOM'ed after short period (1min) because of:
```
Tasks: 2921 total,   2 running, 2919 sleeping,   0 stopped,   0 zombie
%Cpu(s): 68.5 us, 16.1 sy,  0.0 ni, 13.6 id,  0.4 wa,  0.0 hi,  1.3 si,  0.0 st
KiB Mem : 32781868 total,   254724 free, 27097596 used,  5429548 buff/cache
KiB Swap:  5242876 total,        0 free,  5242876 used.  3512320 avail Mem
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
11234 root      20   0 9862.7m 8.491g   6304 S 532.0 27.2   8:22.50 cadvisor
60 root      20   0       0      0      0 S  22.7  0.0   2086:31 kswapd0
```
We can fix this behavior by adding
```
--disable_metrics=disk
```
but thats not what …

Memory leak in fs.go

---

manager/manager.go

The variable dockerStatus and rktPath are still being used even when there is an error.
#1322

Don't rely on the returned value when there's an error

---

container/common/fsHandler.go

https://github.com/google/cadvisor/pull/1766 introduced a message that prints out in nanoseconds.  This fixes up that message.
@derekwaynecarr @dashpole

fix long du duration message

---

container/docker/handler.go

cherrypick overlay2 fix to v0.26 branch, which corresponds to the k8s 1.7 branch

Cherrypick v0.26 1770

---

container/libcontainer/helpers.go
container/libcontainer/helpers_test.go

Typically the first cgroup found is going to be the right one (the
/sys/fs/cgroup mount on most normal machines).
This is only a heuristic to make cadvisor more right more of the time,
but it should be correct in practice to the point where it's okay.
See kubernetes/kubernetes#49835

 libcontainer: Use first cgroup subsystem found 

---

container/crio/client.go

@mrunalp @smarterclayton @derekwaynecarr PTAL
ref https://github.com/kubernetes-incubator/cri-o/pull/1030
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

container: crio: change crio socket

---

info/v1/container.go

This PR will make `device` available when json marshal disk stats as we will use device name as a label in heapster when adding disk io metrics in [heapster #1450](https://github.com/kubernetes/heapster/pull/1450)
Since @smarterclayton added `device` to cadivsor in #1642 , so could you please take a look at this.
/cc @dashpole @derekwaynecarr

marshal device name to json output

---

accelerators/nvidia.go
cadvisor.go
container/containerd/factory.go
container/crio/factory.go
container/crio/handler.go
container/docker/factory.go
container/raw/factory.go
container/rkt/factory.go
container/systemd/factory.go
fs/fs.go
http/handlers.go
machine/info.go
manager/container.go
manager/manager.go
manager/watcher/rkt/rkt.go
storagedriver.go
utils/cpuload/cpuload.go
utils/oomparser/oomparser.go

I got annoyed by the misleading "failed to connect to rkt" type warnings, and that lead me down a rathole of cleaning up all of cAdvisors logging, using the guidelines [here](https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md).

Clean up cAdvisor logging

---

container/docker/docker.go
container/docker/factory.go
manager/manager.go

As these can otherwise block indefinitely due to docker issues.
It would be better if these methods took a context, so the client could
specify timeouts. To preserve API compatibility, I've just added an
internal timeout of 5s to all the calls. In my testing, this is plenty
of time even for slower queries (like image lists, which should take <1s
even with thousands of images).
This is to fix https://github.com/kubernetes/kubernetes/issues/53207,
where kubelet relies on cadvisor for gathering docker information as
part of its periodic node status update.

Add timeouts for docker queries

---

fs/fs.go
pages/static/assets.go
pages/templates.go

There are a lot of spurious exceptions in the kubernetes kubelet logs
like:
E1018 21:03:09.616581   22780 fs.go:332] Stat fs failed. Error: no such
file or directory
Since we know that calling syscall.Statfs will just fail when the path
does not exist, we should just skip making the call.
Fix for https://github.com/kubernetes/kubernetes/issues/35062

Skip getVfsStats when file does not exist

---

container/docker/docker.go
container/docker/factory.go
manager/manager.go
pages/static/assets.go
pages/templates.go

This is to fix https://github.com/kubernetes/kubernetes/issues/53207.
Cherry picks https://github.com/google/cadvisor/pull/1830.

Cherrypick #1830 to release-v0.27

---

manager/container.go

Looks like we forgot to use the method that uses formatting arguments

Fix Warning->Warningf for better logging

---

fs/fs.go

We are switching off UUID in CRI. But I think it's still good to keep this feature.
However, Cadvisor shouldn't fail if `/dev/disk/by-uuid` is not found. Because `/dev/disk/by-uuid` is not always available on different OS distributions.
Signed-off-by: Lantao Liu <lantaol@google.com>

Do not error out when /dev/disk/by-uuid is not found.

---

container/docker/handler.go

Issue: https://github.com/kubernetes/kubernetes/issues/59155
I have confirmed this fixes the issue, but don't know why yet.  I think this is along the same vein as the overlay2 bug (https://github.com/kubernetes/kubernetes/issues/47943), but I am surprised it wasn't caught earlier.
May have something to do with COS, or which things are mounted into the container.

monitor only the upper directory for overlay

---

cadvisor.go
container/factory.go
container/libcontainer/helpers.go
container/libcontainer/helpers_test.go
metrics/prometheus.go
metrics/testdata/prometheus_metrics

Fixes #1513 
I'm a little uneasy that disabling the per-cpu stats means we use a different source for the data.
I could have it still go through the loop, but is that necessary?
cc @dashpole

 Add Prometheus total CPU metric and allow per-cpu stats to be disabled

---

container/containerd/handler.go

I keep seeing this error in kubelet log:
```
Feb 23 09:31:05 workstation kubelet[11956]: I0223 09:31:05.336135   11956 factory.go:105] Error trying to work out if we can handle /kubepods/burstable/pod445bc55c-187c-11e8-bb75-42010af00002/de9b277dbb62d6e2bc2e372f190c84e227986acd40f6e2f2af8a115a51061373: error inspecting container: Error: No such container: de9b277dbb62d6e2bc2e372f190c84e227986acd40f6e2f2af8a115a51061373
Feb 23 09:31:05 workstation kubelet[11956]: I0223 09:31:05.336156   11956 factory.go:116] Factory "docker" was unable to handle container "/kubepods/burstable/pod445bc55c-187c-11e8-bb75-42010af00002/de9b277dbb62d6e2bc2e372f190c84e227986acd40f6e2f2af8a115a51061373"
Feb 23 09:31:05 workstation kubelet[11956]: I0223 09:31:05.336733   11956 factory.go:112] Using factory …
```

Use backoff to tolerant race condition.

---

cadvisor.go
container/factory.go
container/libcontainer/handler.go
info/v1/container.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

Adding scheduler statistics of all processes in a container as discussed in #1865 . 
I will try this out in the coming days see how useful these are in reality and whether anything else pops up.
@dashpole

Adding /proc/<pid>/schedstat

---

storage/statsd/statsd.go

Solves same issue as https://github.com/google/cadvisor/issues/1899 for statsd storage.

Add memory rss to statsd storage

---

container/containerd/client.go

Avoid cadvisor 2 seconds start up latency.
/cc @abhi @miaoyq 
Without this PR cadvisor will always wait for 2 seconds to confirm containerd is not there. It means that kubelet will also finish initialization 2 seconds slower. This is a regression in Kubernetes 1.9 and 1.10. We may want to cut a cherry-pick.
@mtaufen Do we still care about kubelet start up latency now?
Signed-off-by: Lantao Liu <lantaol@google.com>

Fix containerd connection wait.

---

manager/watcher/raw/raw.go

This fixes a bug in cAdvisor where it could miss container discovery.  The following sequence of events would cause this to occurr:
1. Start cAdvisor
2. cAdvisor completes recovery of all cgroups
3. create two levels of cgroups at once (e.g. /docker/CONTAINER_ID)
4. cAdvisor will generate a ContainerAdd event for docker, and start watching the docker/ directory and the /docker/CONTAINER_ID directory.
However, cAdvisor will never generate a ContainerAdd event for the /docker/CONTAINER_ID directory, as it already exists when we start watching the /docker directory.
This fixes the issue by adding a ContainerAdd event when preexisting subdirectories are discovered.
/assign @tallclair

Upon discovering a subdirectory, add a creation event for it

---

storage/kafka/kafka.go

Logs are disabled by default in Shopify/sarama library.
* enabled Shopify/sarama logs
* fix small log string bug

Enable kafka logs

---

docs/development/build.md

The project uses the built-in `context` package introduced in go 1.7 - update the docs to reflect that.

Update docs - go 1.7 needed for building

---

build/build.sh
build/release.sh

When using `make build` to compile the source,
build fails with error/s. The reason is because
of GO_CMD variable is set to 'install' as default,
which is not valid when running `make build` or
`make`.
Depending on the valid git tag, release.sh will
set the GO_CMD variable. If valid git tag is
available e.g.: vx.y.z.beta1, then GO_CMD is
set to `build`.
If valid git tag is not available, release.sh
will any way bails out serving the puspose.
So drop using GO_CMD, to fix the default build.

cadvisor: build: fix broken build with Makefile

---

Godeps/Godeps.json
machine/info.go
vendor/github.com/docker/docker/pkg/parsers/operatingsystem/operatingsystem_linux.go
vendor/github.com/docker/docker/pkg/parsers/operatingsystem/operatingsystem_solaris.go
vendor/github.com/docker/docker/pkg/parsers/operatingsystem/operatingsystem_unix.go
vendor/github.com/docker/docker/pkg/parsers/operatingsystem/operatingsystem_windows.go
vendor/github.com/mattn/go-shellwords/.travis.yml
vendor/github.com/mattn/go-shellwords/LICENSE
vendor/github.com/mattn/go-shellwords/README.md
vendor/github.com/mattn/go-shellwords/shellwords.go
vendor/github.com/mattn/go-shellwords/util_go15.go
vendor/github.com/mattn/go-shellwords/util_posix.go
vendor/github.com/mattn/go-shellwords/util_windows.go

The current `/etc/os-release` parsing code is not robust and assumes that the value of `PRETTY_NAME` is in double quotes when bash env var rules do not require it.  In such cases, the parsing fails.
Docker has a function for this already that does it in a more robust way.  This PR converts to using that method.  The new rules are double quotes and single quotes work and required if the value has spaces.  If no spaces, not quotes are required.
Notes: other options include fixing the code in place or copy-pasting that function from docker.
xref https://bugzilla.redhat.com/show_bug.cgi?id=1521087
@dashpole @derekwaynecarr

Fix os release parsing

---

fs/fs.go

Let us run du with idle io priority
Will this help? mentioned by @meeee in https://github.com/kubernetes/kubernetes/issues/61999#issuecomment-387367763

Run du with ionice

---

fs/fs.go

Reduce impact of running the "find" command when system is loaded. We
already use "nice" with the "du" command.

Run find command with nice to reduce cpu load

---

container/crio/handler.go
container/docker/handler.go

GetSpec() can be called concurrently in manager/container.go.updateSpec()
results into a concurrent map access on the labels map because we're
directly updating the map inside GetSpec(). The labels map from the
container handler is not a copy of the map itself, just a reference,
that's why we're getting the concurrent map access.
Fix this by moving the label update with restartcount to the handler's
initialization method which is not called concurrently.
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

container: fix concurrent map acccess

---

manager/watcher/raw/raw.go

We already [don't collect metrics on .mount cgroups](https://github.com/google/cadvisor/blob/master/container/systemd/factory.go#L39).  But watching each of the mount cgroups for sub-cgroups can use up all of the inotify watches on the node.  This change now makes the watcher ignore .mount cgroups.

Dont watch "*.mount" cgroups

---

accelerators/nvidia.go
accelerators/nvidia_test.go

Earlier if the NVIDIA driver was not installed when cAdvisor was started
we would start a goroutine to try to initialize NVML every minute.
This resulted in a race. We can have a situation where:
- goroutine tries to initialize NVML but fails. So, it sleeps for a minute.
- the driver is installed.
- a container that uses NVIDIA devices is started.
This container would not get GPU stats because a minute has not passed
since the last failed initialization attempt and so NVML is not
initialized.

Initialize NVML on demand.

---

deploy/build.sh
docs/deploy.md

- `git clone` from master branch latest commit (b1535b8)
- `./deploy/build.sh` failed
```
[#15#root@ubuntu-1604 /go/src/github.com/moooofly/cadvisor]$./deploy/build.sh
+ make build
>> building assets
>> building binaries
>> building cadvisor
+ docker build -t google/cadvisor:beta .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /go/src/github.com/moooofly/cadvisor/Dockerfile: no such file or directory
[#16#root@ubuntu-1604 /go/src/github.com/moooofly/cadvisor]$
```
- fix by adding `-f $(dirname $0)/Dockerfile`
```
[#16#root@ubuntu-1604 /go/src/github.com/moooofly/cadvisor]$vi ./deploy/build.sh
[#17#root@ubuntu-1604 /go/src/github.com/moooofly/cadvisor]$
[#17#root@ubuntu-1604 /go/src/github.com/moooofly/cadvisor]$git diff
diff --git a/deploy/build.sh …
```

fix: ./deploy/build.sh can not find Dockerfile

---

cadvisor.go
metrics/prometheus.go

See #1951 for context.
when cadvisor exports metrics for docker containers, there is a root cgroup (/) and cgroup for a docker container (/docker/uuid).
If docker container has a label on it, then this label is applied to all containers including the root container. Because some containers don't have that label, the label will have an empty value. The reason for this is that Prometheus does not allow sending a metric with the same name, but different labels, so cadvisor uses empty label values based on the set of all labels for a given metric. This can result in many docker containers getting a large number of empty labels because another container has that label.
If large number of docker labels vary a lot across images, then the set of labels will be enormous, where most of the labels …

Control whether container labels are exported as prometheus metrics.

---

README.md
deploy/kubernetes/README.md
deploy/kubernetes/base/daemonset.yaml
deploy/kubernetes/base/kustomization.yaml
deploy/kubernetes/base/namespace.yaml
deploy/kubernetes/overlays/examples/cadvisor-args.yaml
deploy/kubernetes/overlays/examples/critical-priority.yaml
deploy/kubernetes/overlays/examples/kustomization.yaml
deploy/kubernetes/overlays/examples/stackdriver-sidecar.yaml

Adds the base cAdvisor daemonset in the base directory, and includes examples on how to mark it "critical", how to limit the metrics cadvisor collects, and how to add a prom-to-sd sidecar container to put metrics in stackdriver

Add cadvisor daemonset using kustomize

---

cadvisor.go
container/containerd/factory.go
container/containerd/factory_test.go
container/containerd/handler.go
container/containerd/handler_test.go
container/crio/factory.go
container/crio/factory_test.go
container/crio/handler.go
container/crio/handler_test.go
container/docker/factory.go
container/docker/handler.go
container/factory.go
container/libcontainer/handler.go
container/mesos/factory.go
container/mesos/factory_test.go
container/mesos/handler.go
container/mesos/handler_test.go
container/raw/factory.go
container/raw/handler.go
container/rkt/factory.go
container/rkt/handler.go
container/systemd/factory.go
http/handlers.go
manager/manager.go
metrics/prometheus.go
metrics/prometheus_test.go

Not all of the metrics can actually be ignored, but I found it helpful to sort them by the MetricKind.
Fixes https://github.com/google/cadvisor/issues/1925

Don't emit prometheus metrics for metrics that are disabled

---

docs/storage/prometheus.md

At the moment, there's no way of knowing which Prometheus metrics are exposed by cAdvisor without digging through source code. This table provides, I believe, something much more convenient.

Add table listing Prometheus metrics to Prometheus doc

---

metrics/prometheus.go

Issue detail is https://github.com/kubernetes/kubernetes/issues/66366
I found the only code is,
```
// Now for the actual metrics
stats := container.Stats[0]
```

Check the length before using container.Stats

---

fs/fs.go

This fixes #1772. I considered having the log verbosity be different for devicemapper/zfs vs other filesystems, but this error doesn't seem serious to me in any case, so I didn't see a compelling reason to make the log verbosity be a function of the filesystem or mount type.

Lower log verbosity for statfs failures, fixes #1772

---

container/libcontainer/handler.go

This makes the behavior of `container_memory_cache` consistent with `container_memory_rss` for hierarchical cgroups. See https://github.com/google/cadvisor/issues/2008 for more detail.

Fix cache reporting with cgroup hierarchy

---

README.md
deploy/kubernetes/base/daemonset.yaml

Fixes https://github.com/google/cadvisor/issues/1955, and makes the kustomize base equivalent to the `docker run` docs.
/assign @tallclair

Update documentation to make /var/run read-only

---

deploy/Dockerfile

1. Update glibc version to 2.28-r0
2. fix build break caused by the URL of the public signing key has been changed to "https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub"

Update Dockerfile and dependencies

---

manager/manager.go

Sometimes, when reading of cgroups tree is too slow, manager.getContainersDiff during global housekeeping could block any other actions due to acquiring mmanager.containersLock for a long time.
To fix it, we could release lock while list cgroups tree and then acquire it again to get diff.

Get rid of lock during list containers

---

manager/watcher/raw/raw.go
utils/oomparser/oomparser.go

This allows cadvisor to build/test properly with a 1.11 toolchain.

fix minor errors revealed by go 1.11

---

deploy/canary/Dockerfile
docs/development/build.md

The canary builds run with the latest go version, which has been failing since it was updated to 1.11:
https://k8s-testgrid.appspot.com/sig-node-cadvisor#cadvisor-push
Rather than making cadvisor work with 1.11, this changes the canary version to 1.10 (the same development version as k/k).  We can change it back to the `latest` tag after we move to 1.11, assuming 1.11 and 1.12 are compatible.

Use go1.10 for canary builds

---

metrics/prometheus.go
metrics/testdata/prometheus_metrics

fixes #2053 
```release-note
Backwards-incompatible change: change the "type" label to "failure_type" for the metric "container_memory_failures_total"
```

Rename extraLabel "type" to "failure_type" for memory_failures_total

---

container/mesos/client.go

We see a lot of logs in k/k CI as follows:
"Factory "mesos" was unable to handle container "/system.slice/home-kubernetes-containerized_mounter.mount"
Example, please see:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/69003/pull-kubernetes-node-e2e/105485/artifacts/tmp-node-e2e-9f0e4e26-cos-stable-63-10032-71-0/kubelet.log
It would be better if we do some sanity check for mesos running before
we try to use it.
Change-Id: I5f6ebcd44fdd4f8d724b85857edf1600473ef1ab

Avoid too many mesos errors in logs when mesos is not present

---

cache/memory/memory.go
container/common/inotify_watcher.go
container/docker/handler.go
fs/fs.go
info/v1/container.go
info/v2/container.go

```
modified:   cache/memory/memory.go
modified:   container/common/inotify_watcher.go
modified:   fs/fs.go
modified:   info/v1/container.go
modified:   info/v2/container.go
```
:smiley:

fix spelling errors

---

container/libcontainer/handler.go
info/v1/container.go
metrics/prometheus.go
metrics/prometheus_test.go

Cache the process stats (ProcessCount, File Descriptor Count) of a container, so that the response time is improved.

Cache process metrics

---

metrics/prometheus.go
metrics/prometheus_test.go

The interface was added in https://github.com/google/cadvisor/pull/2069, but then we took a different approach in https://github.com/google/cadvisor/pull/2093.  This is causing issues for the cAdvisor godependency update: https://github.com/kubernetes/kubernetes/pull/70829.
cc @dims @sashankreddya

Remove unused interface method

---

deploy/kubernetes/overlays/examples/gpu-privilages.yaml
deploy/kubernetes/overlays/examples/kustomization.yaml

I have gotten a bunch of questions about how to use containerized cAdvisor to monitor GPUs.  This should give _something_ for me to point at, even if it isn't perfect.
cc @mindprince 
/assign @tallclair

Add example kustomization which gives cAdvisor access to NVML

---

cadvisor.go
http/handlers.go
pages/pages.go

Some reverse proxies do not support overriding 'Location' header
in 3xx responses. This commit adds a --uri_base_prefix option
that adds a prefix to all URLs of cAdvisor so that
redirects go to the correct places.

added --uri_base_prefix option (#2018)

---

container/mesos/mesos_agent.go

This patch fixes the panic issue when `mesos.Task` does not have a Labels reference:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xded5e4]
goroutine 1 [running]:
github.com/google/cadvisor/container/mesos.(*state).fetchLabelsFromTask(0xc000a0b378, 0xc000988270, 0x30, 0xc000980ae0, 0xc00087c1b8, 0x0)
/home/lanchang/go/src/github.com/google/cadvisor/container/mesos/mesos_agent.go:116 +0xf4
github.com/google/cadvisor/container/mesos.(*state).FetchLabels(0xc000a0b378, 0xc000988240, 0x29, 0xc000988270, 0x30, 0x4, 0x4, 0xc000a0b388)
/home/lanchang/go/src/github.com/google/cadvisor/container/mesos/mesos_agent.go:141 +0x3dd
github.com/google/cadvisor/container/mesos.(*client).getLabels(0xc00000e2b8, …
```

Check whether Mesos task labels are available

---

cadvisor.go
metrics/prometheus.go

This adds a flag `white_listed_container_labels` which allows specifying
a comma separated list of container labels that are allowed to be
attached to prometheus metrics. This helps limit the label space of
each data point and limits the memory used by cadvisor compared to just
add all labels from all containers which is the default.
This is somewhat similar to the `store_container_labels` flag but a bit
more flexible because it allows white listing some common labels e.g.
`io.kubernetes.pod.name`, `io.kubernetes.pod.namespace` etc.
Without this white listing in place we saw the memory footprint of
cadvisor explode in our production environment because users add a lot
of data in pod labels, data which is not useful for metrics but may be
useful for the individual applications.

Add flag to white list container labels for prometheus metrics

---

machine/machine.go

After testing for edge devices with minimal kernel configuration(without numa),
I think we should report coreId = threadId/nodeId=0 if found error.
Signed-off-by: Bin Lu <bin.lu@arm.com>

Bug fix if no NUMA support in kernel

---

metrics/prometheus.go
metrics/testdata/prometheus_metrics

Since PR  https://github.com/google/cadvisor/pull/2124, prometheus can not scrape cAdvisor /metrics now.
Issue https://github.com/google/cadvisor/issues/2133 report the bug. 
I don't know this PR is an appropriate way to fix that bug.

fix timestamp error for container_last_seen

---

cadvisor.go
container/containerd/factory.go
container/containerd/handler.go
container/crio/factory.go
container/crio/handler.go
container/docker/factory.go
container/docker/handler.go
container/libcontainer/handler.go
container/libcontainer/helpers.go
container/libcontainer/helpers_test.go
container/mesos/factory.go
container/mesos/handler.go
container/raw/factory.go
container/raw/handler.go
container/rkt/factory.go
manager/watcher/raw/raw.go

Add support to disable diskIO metrics
ref:https://github.com/google/cadvisor/issues/2045

Add support to disable diskIO metrics

---

docs/runtime_options.md
manager/manager.go

Proposal to resolve https://github.com/google/cadvisor/issues/2146

Periodically updates machine info

---

utils/cloudinfo/aws.go

Adds a second check for Amazon to cover Ec2 Gen5 Instances where DMI values have changed.

Fix Amazon VM detection on EC2 Nitro generation.

---

container/common/fsHandler.go
fs/fs.go
fs/fs_test.go
fs/types.go

Hello there,
I would like to return to the PR have been making almost two years ago. (this one https://github.com/google/cadvisor/pull/1576). @euank proposed to get rid of `find` command. I took as a basis his PR and also got rid of `du` command. Now we collect both disk space and inode stats at the same time.
Why it matters for us: both `du` and `find` overwhelme our audit log.
Also, I have benchmarked `du` command and pure go implementation and got the following results:
```
Benchmark_duDiskUsage-8             1000           1597743 ns/op           22551 B/op        165 allocs/op
Benchmark_osStatDiskUsage-8        20000             56153 ns/op           53624 B/op         88 allocs/op
```
As we can see, pure go implementation is ~20x faster.

fs: get inodes and disk usage via pure go

---

container/common/container_hints_test.go
container/raw/handler.go

Always collect disk stats for root.
Kubelet needs it for all runtimes.
@dashpole Can you help me double check whether this is sufficient for CRI runtimes?
Based on my understanding and testing, this seems sufficient.
Signed-off-by: Lantao Liu <lantaol@google.com>

Always collect disk stats for rootfs.

---

fs/fs.go

When LXD containers are backed up by a ZFS storage pool they do not have the `/dev/zfs` device. Trying to get the file system stats from that device will fail (va the zfs utility).
With this PR, in the above setup (ZFS inside and LXD container), we default to getting the file system stats from VFS.
Here is the error you get when `/dev/zfs` is not present:
```
Feb 19 09:38:54 definite-cricket microk8s.daemon-kubelet[3118]: I0219 09:38:54.595436    3118 fs.go:425] Stat fs failed. Error: exit status 1: "/snap/microk8s/383/sbin/zfs zfs get -Hp all zfsdefault/containers/definite-cricket" => /dev/zfs and /proc/self/mounts are required.
```

Fix stats in LXD with ZFS storage pool

---

container/crio/client.go

Before, making a ContainerInfo request returned an uninformative message about failing to decode json.
Fix this by catching response codes that aren't 200, and return a more informative message.
Signed-off-by: Peter Hunt <pehunt@redhat.com>

container: crio: Return more informative error

---

container/containerd/client.go
container/containerd/factory.go

1. Change the default value of command line flag `--containerd` to '/run/containerd/containerd.sock'.
2. Add a command line flag `--containerd-namespace` defaulting to 'k8s.io'.
3. Create containerd client with values from `--containerd` and `--containerd-namespace`.

Make the containerd factory configurable

---

cadvisor.go
utils/cloudinfo/aws/aws.go
utils/cloudinfo/azure/azure.go
utils/cloudinfo/cloudinfo.go
utils/cloudinfo/gce/gce.go

Change CloudInfo to use a registration pattern, making the dependencies on the cloud provider SDKs optional. The CloudProviders are registered in the main cadvisor binary, so for non-library usages there are no changes.
For Kubernetes, I verified that the info provided by CloudInfo is unused by removing it and confirming everything still builds: https://github.com/tallclair/kubernetes/commit/9274b43f7c2a270b464e8ff5a7a5034d4618d562 (the only reference in Kubernetes was in the cadvisor fake)

Remove CloudProvider SDK dependencies

---

cache/memory/memory.go
storagedriver.go

Sometimes, we want to push stats to more than one storage backends.

Support multiple storage backends

---

utils/cloudinfo/aws/aws.go

Hey all :smiley: !
This commit fixes #2232 where cadvisor was not able to detect the cloud provider when it's running on a custom AMI derived from Amazon Linux 2.
It does so by checking /etc/os-release. However, from what I've read, /etc/os-release is pretty much a systemd thing. Although Amazon Linux 2 comes with systemd, cadvisor cannot assume the existence of systemd in other AMIs / OSes, therefore we would only be checking for /etc/os-release if all other methods fail us.
I have also made a small refactoring so the resulting diff is a little bigger than I wanted it to be for such a small PR, so sorry about that :(

Fixes #2232

---

deploy/kubernetes/overlays/examples/cadvisor-args.yaml

These are actually present in cadvisor metrics that are served via
kubelet (version v1.13.5). This change will bring stand-alone cadvisor
daemonset closer with the one shipped with the kubelet

Do not disable disk and network metrics

---

metrics/prometheus.go
utils/utils.go

Avoid dupe labels in prom metrics

---

info/v2/conversion.go

Add `Envs` to `specV2` from `specV1`, so the cAdvisor remote `REST API 2.x` can get the env specs.

Add Envs to specV2 from specV1

---

deploy/kubernetes/base/daemonset.yaml

see issue #2264 
this patch adds default memory limitation for Cadvisor in K8s so k8s will restart it.

set memory limitation for cadvisor 

---

container/libcontainer/handler.go
info/v1/container.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

**What**
Add metrics `container_threads` and `container_sockets` for container。
As follows:
```
Processes: info.ProcessStats{
ProcessCount: 1,
ThreadCount:  10,
FdCount:      5,
SocketCount:  3,
},
```

Add socketCount for container process stat

---

docs/running.md
docs/runtime_options.md

**What changed**
1. Add `Note` when cadvisor running in docker want to scrape process metrics. 
2. Update `--disable_metrics` information.
related issues [2258](https://github.com/google/cadvisor/issues/2258) [2250](https://github.com/google/cadvisor/issues/2250) [2251](https://github.com/google/cadvisor/issues/2251)

docs: update running flag for current process metrics

---

container/crio/handler.go

When a container is created, cadvisor creates a handler, triggered by inotify.  In the case of a crio managed container, the crio handler immediately queries crio for the pid of the just created container.  Due to performance concerns in crio, the pid might not yet be known and thus returns 0.  If the pid is 0, then network stats are not collected for the lifetime of the container or the lifetime of cadvisor, whichever is shorter.
https://github.com/google/cadvisor/blob/master/container/libcontainer/handler.go#L80-L83
This PR changes the crio handler to requery crio for the pid if the pid was unknown during handler initialization or the last `GetStat()` call.  Once the pid becomes known, the libcontainer handler with the non-zero pid is cached and no further crio queries are needed.
Fixes …

container/crio: retry getting pid if 0

---

deploy/Dockerfile

During coreos/clair scan of image, we can see lot's of security issues:
```
clair-scanner --ip=192.168.1.199 google/cadvisor:canary
2019/07/29 22:12:50 [INFO] ▶ Start clair-scanner
2019/07/29 22:13:08 [INFO] ▶ Server listening on port 9279
2019/07/29 22:13:08 [INFO] ▶ Analyzing ef9a4ff474958b9a2d5cd094a0eec98592409204e99009e4fd11a5cf130dcdda
2019/07/29 22:13:10 [INFO] ▶ Analyzing dd9025d43c3a02c77de9e4b02021a46443456141bcdcf7fbed4b33537526911e
2019/07/29 22:13:11 [INFO] ▶ Analyzing 1f63c10165d40d556a4cf7c7896cb5305d9079a525449948dfa5083fd7046b3d
2019/07/29 22:13:11 [INFO] ▶ Analyzing 512d7b4edea1c6567deb10a997ad697ffb8d1c504c41471803df21fd4ea91f3f
2019/07/29 22:13:14 [INFO] ▶ Analyzing 87862a09725060dba575ef899b3ec6e82d1673c2c51534f7556a4cad2649c327
2019/07/29 22:13:18 [INFO] ▶ Analyzing …
```

Fix security issues: bump alpine to 3.10

---

container/raw/factory.go
container/raw/handler.go

Provide a config knob to disable collecting root Cgroup stats #2259

---

build/prow_e2e.sh

We the makes it print 'make assets FORCE=true', rather than run it (which just exits 1 since it fails).
Related: #2291
/assign @mJace

Fix printed output for prow script

---

machine/info.go

Add error handler after reading `cpuinfo`.

Add missing error handler in machine info

---

container/mesos/mesos_agent.go

GetSource API for mesosContainers ensures to return a safer empty string on non-existence unlike the previous reference which would crash.

Update the reference to Source attribute via safer Get API for mesos containers.

---

storage/elasticsearch/elasticsearch.go
storage/redis/redis.go

The e2e tests are currently failing with:
```
I1107 01:53:45.099] >> checking go formatting
I1107 01:53:45.634] The following files are not properly formatted:
I1107 01:53:45.634] storage/elasticsearch/elasticsearch.go storage/redis/redis.go storage/redis/redis.go storage/elasticsearch/elasticsearch.go
```
https://k8s-testgrid.appspot.com/sig-node-cadvisor#cadvisor-e2e

Update gofmt with go1.13

---

fs/fs.go
fs/fs_test.go

support multi tmpfs in cadvisor
fix https://github.com/kubernetes/kubernetes/issues/81575

support multi tmpfs in cadvisor

---

README.md

Dockerhub repository has a deprecation notice.
Signed-off-by: Roman Mazur <roman@balena.io>

Fix deprecated image reference in readme

---

container/libcontainer/handler.go
container/libcontainer/handler_test.go
info/v1/container.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

This change is intended to address issue #2311.
It adds a ContainerSpec field for Ulimits and populates it for docker containers from the HostConfig. I only emitted the fd soft limit since that's the one we need right now. In theory we could emit all ulimits that are populated (and generate metric names from the resource names), but it seemed better to avoid emitting unnecessary metrics.
The fd soft limit is emitted as container_spec_file_descriptor_limit_soft, which is longer than I would like, but seems to be consistent with the naming convention.
An alternative approach that might be more "container agnostic" involves looking up all the processes in the cgroup, and emitting the ulimits for the "parent/init/session" process for the cgroup. However, it might be more "fragile".

Add support for emitting file descriptor limits for containers.

---

manager/container.go
manager/container_test.go

The `stop` channel used in `container.go` is selected in both public method `OnDemandHousekeeping` and as a base case in `housekeepingTick`. A deadlock condition can occur when the user calls `OnDemandHousekeeping` with a `maxAge` more recent than the last stats update time after the container has already been stopped and the `stop` channel already drained in `housekeepingTick`.
I've been able to reproduce this issue consistently by ramping up a number of docker containers and stopping them in groups.
I've added unit test to demonstrate the fix. Without the stop channel changes this test times out due to blocking call.

Fix container `OnDemandHousekeeping` blocking on stop channel.

---

storage/stdout/stdout.go

Add Unix Timestamp in nanoseconds to container metrics stats for stdout storage driver.
This commit resolves #2360

Add timestamp support in stdout storage driver

---

pages/static/assets.go
pages/templates.go

See https://github.com/google/cadvisor/pull/2364#issuecomment-571345370 for an example of the failure.  This is the classic new year's bump of UI assets...  Everything has to say 2020!

Update assets to fix e2e tests

---

machine/machine.go

Add riscv64 to clock speed ignore list.

Ignore CPU clock for riscv64

---

machine/topology_test.go

It fails on s390x and aarch64, since GetTopology
function is platform specified.

Skip TestTopology on non-amd64

---

container/common/helpers.go

In GetSpec, we shouldn't assign val to spec.Cpu.Quota if the parsing fails.

Assign quota if the parsing doesn't encounter error

---

machine/machine.go

In getNodeIdFromCpuBus, the nodeBusRegExp is used twice.
This PR drops the regexp.MatchString call which doesn't seem necessary.
The check on err is not relevant for the loop.
When nodeId is determined, we can come out of the loop.

Simplify getNodeIdFromCpuBus

---

container/crio/handler.go

In crioContainerHandler#getFsStats, we come out of the loop over mi.Filesystems when device is found.
However, in case the device is not found, we should return info.FsStats with limit of 0.
This PR adds check against the device not found case.

Verify that fsType is found for device

---

fs/fs.go

Don't ignore error of filepath.Walk

fix GetDirUsage error ignored

---

collector/prometheus_collector.go
info/v1/metric.go
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics

Solves https://github.com/google/cadvisor/issues/1616

Append application metrics to /metrics so that prometheus can read #1616

---

utils/oomparser/oomparser.go
utils/oomparser/oomparser_test.go

Fixes #2417, which caused all OOMs on >5.0 kernels to be considered system ooms.
This adds parsing for the new format.  When this format is found, we can "finish" immediately, since the message has all of the information we want in a single place.  If the format is not found, we fall back to looking for the old message.  It also grabs the Constraint that is hit, which may be useful for users that have topology constraints.

Handle the new 5.0 linux format for oom messages

---

container/common/fsHandler.go

In realFsHandler#update, extraUsage.Bytes is accessed without checking extraErr.
This PR adds check before referencing extraUsage.Bytes

Check extraErr before accessing extraUsage.Bytes

---

info/v1/machine.go

I have realized that `info.MemoryInfo` that I added recently is missing (de)serialization tags.

Adding missing struct tags for JSON consistency

---

cadvisor.go
cadvisor_test.go
container/factory.go
metrics/prometheus_test.go

ref: https://github.com/kubernetes/kubernetes/pull/88841
To support configurable metricSet in `kubelet`, we should add a `AllMetrics` to relieve hard code pain.
And  `AllMetrics` has been used for some other where like `cadvisor.go` and `prometheus_test.go` in cadvisor, we can unified it.

refactor AllMetrics to support external reference

---

accelerators/nvidia.go
accelerators/nvidia_test.go
manager/container.go
manager/container_test.go
manager/manager.go
stats/types.go

Moving Nvidia interfaces to stats package so that they can be used outside of the accelerators package. This is related to #2419 and will be used there eventually.

Moving Nvidia interfaces

---

info/v1/machine.go
machine/info.go
machine/machine_libipmctl.go
machine/machine_no_libipmctl.go

NVM memory mode capacity is visible on API in following form:
```
"nvm": {
"memory_mode_capcity": 429496729600,
"avg_power_budget": 15
}, 
``` 
related to #2388

Extending machine API by NVM memory mode capacity

---

info/v1/machine.go
machine/machine.go
machine/machine_libipmctl.go

Fix typos related to NVMinfo struct and GetMachineMemoryByType function

---

container/docker/factory.go
container/docker/handler.go
container/docker/handler_test.go

This is a feature that cadvisor can export envs with kinds of prefix pattern. It can be set by flag --docker-env-metadata-whitelist in kubelet. If exec cmd like `kubelet --help`(master branch),
```
--docker-env-metadata-whitelist string                                                                      a comma-separated list of environment variable keys that needs to be collected for docker containers (DEPRECATED: This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.)
```
ref: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/globalflags_linux.go#L57
If exposed metrics with cadvisor daemonset, we can also add this feature to exposed tags …

support to expose environments with prefix specified

---

build/assets.sh

Builds go-bindata in a tmp dir to avoid mutating the go.mod/go.sum file of this module
Split out of #2437 for separate review/merge
cc @dashpole

Build go-bindata in a tmpdir

---

container/systemd/factory.go

Just turn the message into a log that folks can see if they turn up the
logging level.
Fixes #2440

Avoid logging unnecessary errors from systemd handler

---

machine/info.go
manager/manager.go
nvm/machine_libipmctl.go
nvm/machine_no_libipmctl.go

Fixes #2457.
Files have been moved from `machine` to `nvm` in order to break a cycle.

Workaround for not being able to call nvm_init() after nvm_uninit()

---

container/crio/client.go

Signed-off-by: Ted Yu <yuzhihong@gmail.com>
Currently the error return from configureUnixTransport is ignored for CRI-O client construction.
This PR checks the error return.

CRI-O client should check Unix Transport error

---

container/crio/client.go

Signed-off-by: Ted Yu <yuzhihong@gmail.com>
via commit 2f2e88c93931f678201ef65ffd80161b1072f5f8 :
Add dual stack IPv6 support
cri-o may return multiple IPs:
```
-       IP              string            `json:"ip_address"`
+       IPs             []string          `json:"ip_addresses"`
```
This PR introduces an internal struct, containerInfoDualStack, to crio client.
If IP is not obtained by parsing with single IP struct, we try with parsing using containerInfoDualStack struct.

Populate IP address for cri-o release with dual stack support

---

container/crio/client.go

configureUnixTransport calls Transport#Dial which is deprecated.
This PR replaces it with DialContext

Replace deprecated Dial call

---

utils/sysinfo/sysinfo.go

This PR adds error return checking for GetCPUPhysicalPackageID().

Check the error return from GetCPUPhysicalPackageID()

---

fs/fs.go

Some storage drivers seems to be missing which are now supported by
CRI-O. Beside that, we removed the non-existing overlay2 driver.

Update CRI-O storage driver support

---

utils/sysinfo/sysinfo.go
utils/sysinfo/sysinfo_test.go

The latest kubernetes deployment on Arm64 VM-s(official ubuntu18.04) always fails.
Because k8s always get num_cores=0 from cAdvisor on Arm64 VM-s.
The reason is that, there is no cache info on Arm64 VM-s.
So the process of getMachineInfo was blocked by the step of getCacheInfo
on Arm64 guest.
And the good news is, we can get cache info on Arm64 hosts.
When this patch was merged, I will deliver a patch to update the version
of cAdvisor in kubernetes as soon as possible.
Signed-off-by: bblu <bin.lu@arm.com>

Issue fix: get wrong machine info on Arm64 guest

---

manager/manager.go

manager#Exists doesn't perform write operation.
Taking read lock should suffice.

manager#Exists should take read lock

---

accelerators/nvidia.go
accelerators/nvidia_test.go
manager/manager.go
stats/noop.go
stats/types.go

@dashpole I would appreciate if you took a look - I need these changes to proceed with #2419.
Not changed:
* when `nil` and real `error` are returned.
Changed:
* `stats.NoopCollector` might be returned sometimes.
* `stats.Manager.Setup()` may return an error
* `stats.Collector.Setup()` may return an error

Returning more error information from stats.Manager and stats.Collector

---

info/v1/container.go

There were some recently added fields of ContainerSpec missing in Eq().
This PR adds them.

Add missing fields to ContainerSpec#Eq

---

machine/topology_test.go
manager/manager.go

Fixes #2487
The data race was due to manager.machineInfo being read after manager#GetMachineInfo() returns.
This PR makes a copy of MachineInfo and returns the pointer to the copy.

Make a copy of MachineInfo in GetMachineInfo()

---

info/v1/machine.go
manager/manager.go

For manager#GetMachineInfo(), we should duplicate the maps inside MachineInfo when copying.
This completes #2490

Make a copy of the maps of MachineInfo

---

manager/container.go

This addresses existing comment by making a copy:
```
// Make a copy of the info for the user.
```

Make a copy of containerInfo in containerData#GetInfo

---

metrics/prometheus.go
metrics/prometheus_test.go

Condition for `container.PerfMetrics` was nested in condition for `container.ProcessMetrics`.

Perf metrics were exported only if process metrics were

---

.github/workflows/test.yml
build/integration-in-docker.sh

Instead of installing requested Go version in a VM we should use proper version of container image.

Go version must be passed to docker

---

deploy/Dockerfile

In case we change setting:
- ``url_base_prefix``
- ``port``
The default healthcheck URL is wrong, and so, the container is always marqued down.
I propose a simple solution, a new env variable ``CADVISOR_HEALTHCHECK_URL`` , so it's easy to specify the full URL to check.

Add healthcheck url env variable

---

Makefile
build/unit-in-container.sh

Centos/RHEL 8 and Fedora >= 31 do not provide `docker` by default. It would be great if running unit tests in `podman` were possible.
Unfortunately integration tests can't be run in `podman` at the moment. https://github.com/containers/libpod/issues/4131 might help, eventually.

Ability to run unit tests in podman

---

.golangci.yml
container/common/container_hints.go
container/containerd/client.go
container/containerd/client_test.go
container/containerd/factory.go
container/containerd/handler.go
container/containerd/handler_test.go
container/crio/client.go
container/crio/client_test.go
container/crio/factory.go
container/crio/handler.go
container/crio/handler_test.go
events/handler.go
events/handler_test.go
summary/percentiles.go

I think we should be rather safe. I haven't check it (I don't really know how) but I don't think that any project would rely on unexported struct properties.

 Using unexported return type from exported function shall be forbidden

---

go.mod
utils/sysinfo/sysinfo.go

As indicated [here](https://godoc.org/github.com/google/go-cmp/cmp) go-cmp should not be used in production environment because  it may panic if it cannot compare the values.

Remove go-cmp from from cache comparison

---

cmd/cadvisor.go
cmd/cadvisor_test.go
cmd/internal/http/handlers.go
container/factory.go
docs/storage/prometheus.md
info/v1/machine.go
machine/info.go
metrics/prometheus_fake.go
metrics/prometheus_machine.go
metrics/prometheus_machine_test.go
metrics/testdata/prometheus_machine_metrics

- machine_cpu_cache_capacity_bytes
- machine_node_hugepages_count
- machine_node_memory_capacity_bytes
- machine_nvm_avg_power_budget_watts
- machine_thread_siblings_count
Introduce timestamp for machine related information (it is possible to reconfigure huge pages without restart so it seems to be useful to have timestamp for this information)

Introduce new machine metrics:

---

docs/storage/prometheus.md

Adds metrics added by [PR2420](https://github.com/google/cadvisor/pull/2420/files) to documentation
Signed-off-by: Piotr Wagner <piotr.wagner@intel.com>

Add hugetlb metrics to prometheus metrics documentation

---

deploy/kubernetes/overlays/examples/cadvisor-args.yaml
deploy/kubernetes/overlays/examples/critical-priority.yaml
deploy/kubernetes/overlays/examples/gpu-privilages.yaml
deploy/kubernetes/overlays/examples/stackdriver-sidecar.yaml

Without changes introduced in this PR I'm observing following error:
```
$ kustomize build deploy/kubernetes/overlays/examples
Error: no matches for OriginalId apps_v1_DaemonSet|~X|cadvisor; no matches for CurrentId apps_v1_DaemonSet|~X|cadvisor; failed to find unique target for patch apps_v1_DaemonSet|cadvisor
```
My Kustomize version:
```
$ kustomize version
{Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
```

Fix generating daemonset with example patches using Kustomize

---

machine/machine.go
machine/testdata/cpuinfo_lower_case
machine/testdata/cpuinfo_upper_case
machine/topology_test.go

Signed-off-by: sayaoailun <guojianwei007@126.com>
**What type of PR is this?**
/kind bug
**What this PR does / why we need it**:
Fix bug:
GetClockSpeed use Regular Expression `(?:cpu MHz|clock)\s*:\s*([0-9]+\.[0-9]+)(?:MHz)?` to get ClockSpeed.
When I start the Kubelet, I met this error:
```
failed to run Kubelet: could not detect clock speed from output: "system type       : generic-loongson-machine
machine         : loongson,generic
processor       : 0
cpu model       : ICT Loongson-3 V0.4  FPU V0.1
model name      : Loongson-3A R4 (Loongson-3B4000)
CPU MHz         : 1800.00
BogoMIPS        : 12730.64
wait instruction    : yes
microsecond timers  : yes
tlb_entries     : 2112
extra interrupt vector  : yes
hardware watchpoint : yes, count: 0, address/irw mask: []
isa         : mips1 mips2 …
```

Fix GetClockSpeed error when dealing with upper case

---

.github/workflows/test.yml
integration/tests/api/machine_test.go

Replacing `golangci-lint` from my fork with upstream version.

Using upstream golangci-lint

---

.golangci.yml
cache/memory/memory_test.go
integration/tests/api/machine_test.go
manager/manager_test.go
utils/cloudinfo/aws/aws.go
utils/sysinfo/sysinfo.go

The only remaining errors (besides fixed in #2513) are those from `utils/cpuload/netlink/netlink.go` - do you think it's worth fixing them? `netlink.addAttribute()` is used in two places and in both cases buffers are based on slice of bytes; I can't imagine when it would be impossible to write to them.

Some linting errors

---

machine/machine.go
machine/topology_test.go

GetClockSpeed() uses the information from the file
/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq when it exists.
Make sure it is not used for tests.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

machine, topology_test: not read system file

---

docs/storage/prometheus.md

The description of machine_cpu_cores and machine_cpu_physical_cores was swapped.

Fix description of cpu_cores metrics in docs

---

deploy/canary/Dockerfile

The job is broken on testgrid: https://k8s-testgrid.appspot.com/sig-node-cadvisor#cadvisor-push
Its complaining about not being able to find dependencies: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cadvisor-canarypush/1262135885336416257

update canary job to go 1.14

---

integration/tests/api/docker_test.go

There are a number of flakes in the ci job: https://k8s-testgrid.appspot.com/sig-node-cadvisor#cadvisor-e2e
For example: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cadvisor-e2e/1259431819728654336
```
I0517 03:04:22.588] === RUN   TestDockerContainerNetworkStats
I0517 03:04:22.588] I0517 03:04:07.218068    2342 framework.go:332] About to run - [sudo docker run -d busybox watch -n1 wget http://www.google.com/]
I0517 03:04:22.588] I0517 03:04:18.022055    2342 framework.go:332] About to run - [sudo docker rm -f 4b92991560acd1df0f3eac769ea616391ea6a2e3a8b88c7fc90d874da514f119]
I0517 03:04:22.588] --- FAIL: TestDockerContainerNetworkStats (11.06s)
I0517 03:04:22.589]     docker_test.go:304: 
I0517 03:04:22.589]         	Error Trace:	docker_test.go:304
I0517 03:04:22.589] …
```

Lengthen timeout and add additional information for debugging flakes

---

integration/runner/runner.go

Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
The send operation to the channel done will certainly be executed, but the receive operation may not, if the goroutine times out. Hence the goroutine might get stuck and cause a leak. A simple fix is to use a buffered channel so that the goroutine can write to it without having to care if there's a reader or not. This PR converts the channel to a buffered channel.

runner: fix goroutine leak

---

manager/container.go
manager/manager.go
manager/manager_test.go

There are something wrong with function `SubcontainersInfo` in `manager/manager.go` if host is in benchmarking or some critical status. It will result in missing subcontainers info for new container or collecting dead container info.
if request `kubelet` api like this: 
`curl -X GET -k -i "https://127.0.0.1:10250/stats/container" -H "Authorization: Bearer $token" -d '{"num_stats":1,"containerName":"kubepods","subContainers": true}' > test.txt`,  the kubepods' subcontaines are not all in response and some containers in response are not in kubepods' subcontainers.
Response file is here: 
[test.txt](https://github.com/google/cadvisor/files/4614308/test.txt)
And containers in kubepods burstable directory subcontaines are not equal to all containers with burstable prefix.
I find that some …

fix missing container info when getting sub-containers stats

---

manager/manager.go

This PR adds nil check in manager#getSubcontainers() so that we don't dereference nil container.
Fixes https://github.com/kubernetes/kubernetes/issues/91323

Check container against nil before de-referencing

---

info/v1/machine.go
machine/topology_test.go
utils/sysinfo/sysinfo.go
utils/sysinfo/sysinfo_test.go

Now cadvisor in MachineInfo.Topology keeps NUMA nodes.
There is no socket information, except number of sockets.
Since socket - NUMA nodes relationship could be many-to-many,
it's more reasonable to keep socket_id per Core, not per NUMA node.
This socket id could be used in kubernetes cpu manager to provide
per socket allocations.
Signed-off-by: Alexey Perevalov <alexey.perevalov@huawei.com>

Add socket id into Core

---

utils/oomparser/oomparser_test.go

Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
Capture the iterator variable pair in the goroutine to avoid data race.

oomparser_test: fix data race

---

machine/topology_test.go

GetTopology provides Nodes not in order of Node.Id.
PR https://github.com/google/cadvisor/pull/2551 removed that check,
as result test acidentially passed.
Fixes: #2557
Signed-off-by: Alexey Perevalov <alexey.perevalov@huawei.com>

Fix test with different order of Topology's nodes

---

info/v2/container.go
info/v2/conversion.go

Perf stats and hugetlb stats were not available on API v2.0, this pull request fixes it.

Fixes perf stats and hugetlb stats on API v2.0

---

go.mod
go.sum

Updating the "go-connections" version to v0.4.0 from v0.3.0
cc @dims

updating go-conenctions to v0.4.0

---

deploy/Dockerfile

I was trying to build Docker image on aarch64 and I failed miserably because of some incompatibilities between `glibc` and `musl`. Using multistage Dockerfile helps and, as a side-effect, shrinks the image to 150 megabytes.

Using multistage Dockerfile and upgrading Alpine to 3.12

---

fs/fs.go
fs/fs_test.go
fs/types.go

This PR fixes the issue of generating correct `DiskStats` if disk names do not match with the device name found in `/proc/diskstats`
When we have dm devices, the name of the root device may not match with the device name seen by `lsblk` of `/proc/self/mountinfo`. 
```bash
NAME                     FSTYPE      LABEL        UUID                                 MOUNTPOINT
sda1                     ext4        boot         fd9689d9-fbcc-488a-a70e-145fddf245e7 /boot
└─sda                                                                                  
sda2                     vfat        EFI-SYSTEM   4FC5-6A46                            /boot/efi
└─sda                                                                                  
sda3 …
```

Fix incorrect diskstats for dm devices

---

accelerators/nvidia.go
cmd/cadvisor.go
manager/manager.go

Hello!
This is a slight improvement of the NVIDIA API, this is needed because the NVIDIA manager opens a handle on nvml at NewNvidiaManager time.
This is problematic in a kubernetes setting where kubelet now has an open handle on the NVIDIA driver, preventing an update of the NVIDIA driver unless kubelet is restarted.
Additionally with the new metrics pipeline in Kubernetes, metrics are now expected to be collected through a container rather than through the kubelet itself.
I'm hoping that with the following enhancement in Kubernetes: https://github.com/kubernetes/kubernetes/pull/88841 we can add a knob for cluster admins to remove that reference on the driver.
For testing, here is an example output (slightly edited):
```
➜  cadvisor git:(master) ./cadvisor -v 2 --disable_metrics …
```

Return a NoopManager if metricset does not container the accelerator value

---

fs/fs.go
fs/fs_test.go

Images path is incorrectly detected as the last one in the list of possible locations.
As all tests used the last value as the expected value, this issue was not detected earlier.
The issue has a pretty high risk as one can end up with:
* frequent unnecessary images GC
* no images GC at all
* nodes being tainted `node.kubernetes.io/disk-pressure: NoSchedule`
Ref: https://github.com/kubernetes/kubernetes/issues/91982

Fix incorrect detection of images path

---

cmd/internal/storage/influxdb/influxdb.go
cmd/internal/storage/influxdb/influxdb_test.go

Fix unit tests for InfluxDB storage which are executed with command `go test -tags influxdb_test`
Add stats to InfluxDB storage: memory, hugetlb, perf, resctrl, referenced memory

Add stats to InfluxDB storage

---

manager/manager.go
resctrl/manager.go

- Change warning for resctrl path to Info with verbosity level
- Change info log to Info with verbosity level
- Change imports grouping
- Add verbosity level to perf Info logs 
- Add checking if resctrl path exists
Without changes introduced in this pull request cAdvisor was very verbose when running without log level verbosity, e.g.:
```
sudo ./cadvisor
W0624 10:56:56.152857   28203 nvidia.go:61] NVIDIA GPU metrics will not be available: no NVIDIA devices found
W0624 10:56:56.167991   28203 manager.go:960] Error getting resctrl path: "mountpoint for Intel RDT not found"
W0624 10:56:56.185596   28203 manager.go:960] Error getting resctrl path: "mountpoint for Intel RDT not found"
W0624 10:56:56.186009   28203 manager.go:960] Error getting resctrl path: "mountpoint for Intel RDT not found" …
```

Verbosity level for resctrl and perf logs

---

deploy/Dockerfile

libpfm4 was built and installed twice, see lines 12-14 and lines 16-18 in Dockerfile

Remove redundant installation of libpfm4

---

cmd/cadvisor.go
docs/storage/prometheus.md
manager/manager.go

This PR adds information about the `-disable_metrics` parameter to the Prometheus metrics table.

Add "-disable_metrics" column to prometheus metrics table.

---

.github/workflows/test.yml

This is pretty straightforward change that brings `golangci-lint` up-to-date.

Upgrading golangci-lint to 1.28.0

---

cmd/internal/api/versions.go
cmd/internal/http/handlers.go
info/v2/container.go
manager/container.go
metrics/metrics.go
metrics/prometheus.go
metrics/prometheus_fake.go
metrics/prometheus_test.go

Fix #1989 
This is a rework of #2000 
This allows user to set v2.RequestOptions for PrometheusCollector to be
used when retrieving container stats. The options will only be set once
per collector to ensure that we don't race for concurrent metrics
request. This should not be a problem for prometheus scrapes as the
scrapes are usually in the same format.
One can design the on-demand metrics collection as such to minimize CPU
usage in housekeeping routine:
- assuming prometheus scrape interval is 60s
- increase housekeeping interval to a high value such as 300s
- set max_age paramether in scrape to a low value ( such as 1s ), so
that if we scrape just as housekeeping finish, we don't do any extra
work. When we scrape, if current metrics are older than 1s, we will
collect the metrics again. …

Allow on-demand metrics collection for prometheus

---

docs/storage/prometheus.md

- Corrected information about perf metrics
- Add information about build flags required for metrics

Improve information about metrics

---

Makefile

It must be possible to run libpfm related tests with Makefile.

Add entry for libpfm related tests to Makefile

---

cmd/cadvisor.go
cmd/cadvisor_test.go
container/factory.go
container/libcontainer/handler.go
docs/storage/prometheus.md
info/v1/container.go
metrics/prometheus.go
metrics/prometheus_fake.go
metrics/testdata/prometheus_metrics

This pull request introduces information from memory.numa_stat as Prometheus metrics.

Memory numa stats

---

perf/uncore_libpfm.go

- Add logs informing about incorrect configuration for perf events
- Simplify setup of raw perf events

Add logs and simplify setup of raw perf events

---

docs/runtime_options.md
metrics/prometheus.go
metrics/prometheus_test.go
metrics/testdata/prometheus_metrics_perf_aggregated

I want to test it more and add more unit tests.
Related to #2608

Aggregate perf metrics

---

info/v2/machine.go

the hugepages info in "_/attributes_" should be equal to "_/machine_"

add hugepages info to attributes

---

build/release.sh
docs/development/releasing.md

Simplify where we push images, 
print out information to make it easier to write the github release,
clarify which go version we should use to build release artifacts,
remove `$` to make it easier to copy commands,
add instructions for updating the dependency in kubernetes.

Update release documentation and process

---

container/raw/watcher.go
manager/manager.go

when watchForNewContainers and rawContainerWatcher  Start fails and return err, but it does not have some clean operations since some ContainerWatchers already execute the Start() functions. so this commit tries to add clean operations when this happens.

add clean operation when watchForNewContainers/Start failed

---

deploy/Dockerfile

The default alpine 'wget' cannot handle https proxies. The solution is installing wget via `apk add wget`. 
More about it you can read here: https://gitlab.alpinelinux.org/alpine/aports/-/issues/10446
```
Executing busybox-1.31.1-r16.trigger
OK: 632 MiB in 105 packages
Removing intermediate container 2c082d006a1d
---> 62ad5850270c
Step 3/19 : RUN wget https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.10.1.tar.gz &&   tar -xzf libpfm-4.10.1.tar.gz &&   rm libpfm-4.10.1.tar.gz
---> Running in 4e852f499181
Connecting to proxy [...]
wget: server returned error: HTTP/1.1 400 Bad Request
```
```
Executing busybox-1.31.1-r16.trigger
OK: 634 MiB in 108 packages
Removing intermediate container fb9929f9946a
---> f43faec7c894
Step 3/19 : RUN wget …
```

Fixed https proxy issue by installing 'full' wget in Docker alpine-based build stage

---

go.mod
go.sum
perf/collector_libpfm.go
perf/types_libpfm.go

Use perf attributes from unix lib.

Use perf attributes from unix lib.

---

cmd/internal/storage/stdout/stdout.go

Add stats to stdout storage: memory, hugetlb, perf, resctrl, referenced memory

Add stats to stdout storage

---

cmd/internal/storage/statsd/statsd.go

Add stats to stdout storage: memory, hugetlb, perf, resctrl, referenced memory

Add stats to statsd storage

---

.golangci.yml

Some of the CI linters appear to be timing out, e.g. on https://github.com/google/cadvisor/pull/2697 
```
2020-10-28T21:26:44.8348743Z >> running golangci-lint using configuration at .golangci.yml
2020-10-28T21:27:45.0836302Z level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
2020-10-28T21:27:45.0960089Z ##[error]make: *** [Makefile:99: lint] Error 4
2020-10-28T21:27:45.0966521Z ##[error]Process completed with exit code 2.
```
Default timeout appears to be [1m](https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml), so bumping to 5 minutes to avoid `golangci-lint` from timing out

Increase golang ci lint timeout to 5 minutes

---

docs/runtime_options.md

Flag was merged in https://github.com/google/cadvisor/pull/2283, but never added to the docs

Add missing flag to runtime_options.md

---

docs/development/build.md
nvm/machine_libipmctl.go
nvm/machine_no_libipmctl.go

Fix typo in libipmctl

---

README.md

This should just display the results from the most recently merged PR if I understand it correctly.

Add a badge for the current e2e test result

---

docs/runtime_options.md

Add information about limits of opened perf event files.

---

perf/collector_libpfm.go
perf/collector_libpfm_test.go

From https://man7.org/linux/man-pages/man2/perf_event_open.2.html :
```
exclude_guest (since Linux 3.2)
When conducting measurements that include processes running VM
instances (i.e., have executed a KVM_RUN ioctl(2)), do not
measure events happening inside guest instances.  This is only
meaningful outside the guests; this setting does not change
counts gathered inside of a guest.  Currently, this function‐
ality is x86 only.
```
Depend on the kernel version, `perf_event_open` can throw `invalid_argument` for uncore events with this flag set.
For core events it's also unnecessary.

Remove exclude guest flag from perf event attrs. 

---

manager/manager.go
manager/manager_test.go
pages/static/assets.go
pages/templates.go

Ref. discussion in k/k here: https://github.com/kubernetes/kubernetes/pull/94176

Cherry-pick #2490  Make a copy of MachineInfo in GetMachineInfo() to v0.35

---

manager/manager.go
perf/uncore_libpfm.go

Increase the readability of perf event logs.

---

container/docker/client.go

**What type of PR is this?**
/kind bug 
/kind cleanup 
**What this PR does / why we need it**:
`dockerclient.NewClient` has been deprecated. And change to recommended public methods `dockerclient.NewClientWithOpts`.  
using WithAPIVersionNegotiation() makes the Docker client negotiate down to a lower version if Docker's current API version is newer than the server version.
ref: [kubelet: pod metrics not visible with Docker 18 (19.03 works) ](https://github.com/kubernetes/kubernetes/issues/94281)
After https://github.com/kubernetes/kubernetes/pull/89687 merged(docker client dependency update to newer), We find that kubelet failed to register cadvisor  docker factory when we use k8s v1.19 with docker 18.X. And info as fellow: 
```
[factory.go:161] Registration of the docker container …
```

update docker client method

---

machine/machine.go

cAdvisor is currently giving up reading CPU frequency for some platforms (such as `aarch64`) before looking into `/sys/devices/system/cpu/`. I think it's wrong, even knowing that on big.LITTLE platforms wrong information will be displayed.

Try to read from sysfs before giving up on non-x86_64

---

perf/collector_libpfm.go
perf/collector_libpfm_test.go
perf/uncore_libpfm.go

To avoid unix.PerfEventAttr with random fields from `readPerfEventAttr`, fill memory with 0 values.
This fixes getting an "invalid argument" when opening perf events.
@kwisniewski98 @iwankgb @katarzyna-z

[Fix] Avoid random values in unix.PerfEventAttr{}

---

nvm/machine_libipmctl.go

do not initialize libipmctl package when getting an error from nvm_init()

---

accelerators/nvidia.go

Reverts a small part of https://github.com/google/cadvisor/pull/2419, which changed how the nvidia collector is setup.  NVIDIA driver and library installation is often done via daemonset.  If cadvisor starts before the library is installed, youdon't get any GPU metrics.  
This should fix the problem by returning a manager instead of a noop.  Setup will be retried when GetCollector is called.
cc @RenaudWasTaken @iwankgb @bobbypage 
I'd like to cherrypick this back to v0.37 as well.

Don't fail permenantly when nvml isn't installed

---

cmd/go.sum
container/docker/client.go
go.mod
go.sum

* Cherrypick  update docker client method #2714 to v0.37
* Bump docker to https://github.com/moby/moby/tree/v19.03.8 to match that of k8s 1.19 - https://github.com/kubernetes/kubernetes/blob/release-1.19/go.mod#L39 
```
github.com/docker/docker v1.4.2-0.20200309214505-aa6a9891b09c
```

Cherrypick to v0.37 - update docker client method

---

Makefile
build/check_gotidy.sh

Add a presubmit script that checks if `go mod tidy` needs to run on either the main module or cmd module. 
Closes #2730

Check go mod tidy as part of presubmit and CI

---

container/containerd/client.go

Originally the gRPC backoff multiplier is not set so it got defaulted as zero. Once a connection timeout happens, gRPC exponential backoff will be triggered which results in setting the backoff durating to zero, causing retries flooding. Setting gRPC multiplier to 1.6 which is the default one from gRPC package will solve the issue.
Closes #2748

Fix timeout flooding issue after containerd restart

---

cmd/go.sum
go.mod
go.sum

Fixes #2753. `runc` version is the same in both projects so I would assume that it is a safe change.

Upgrading containerd because of CVE-2020-15257

---

container/containerd/client.go

Backport pick fixes from https://github.com/google/cadvisor/pull/2749

Cherrypick to v0.37: Fix timeout flooding issue after containerd restart

---

container/containerd/client.go

Backport pick fixes from https://github.com/google/cadvisor/pull/2749

Cherrypick to v0.38: Fix timeout flooding issue after containerd restart

---

fs/fs.go
fs/fs_test.go

Fix kubernetes issue #94335
- Issue: kubernetes/kubernetes#94335
- Fix `GetDirFsDevice` to return correct `*DeviceInfo` when "/" is Btrfs
- Refactor to call new function `mountInfoFromDir` that returns
`*MountInfo` which `dir` belongs
- Add TestMountInfoFromDir to verify the fix
Signed-off-by: Geonju Kim <rjswn042@gmail.com>

Return correct DeviceInfo from GetDirFsDevice on / path for Btrfs - Fix kubernetes issue #94335

---

cmd/internal/storage/influxdb/influxdb_test.go

If actually running the influxdb tests (not included in Makefile), a compiler error occured ("cannot use promoted field in struct literal of type") because direct access to promoted fields is only allowed in assignments, not when initializing structs (at least, unless golang/go#9859 gets implemented).
The tests run fine otherwise, as soon as the required tag is added.
<sup>Jens Erat <jens.erat@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

Properly initialize nested struct in influxdb test

---

manager/container.go
manager/container_test.go

This fixes the data race between the functions which could be running
in different goroutines.
Signed-off-by: Pradyumna Agrawal <pradyumnaa@vmware.com>
Fixes #2754

Fix race between `OnDemandHousekeeping` and `housekeepingTick`

---

fs/fs.go
fs/fs_test.go
go.mod

CAdvisor is vendored into kubernetes/kubernetes, so it cannot use staging
repositories as dependencies. The k8s utils/mount is a staging repository.
This commit switches cAdvisor to use moby/sys/mountinfo instead to avoid
dependency issues.

Switch from k8s utils/mount to moby/sys mount

---

fs/fs.go
fs/fs_test.go

Backport pick fixes from https://github.com/google/cadvisor/pull/2752
(Fix https://github.com/kubernetes/kubernetes/issues/94335)

Cherrypick to v0.37: Return correct DeviceInfo from GetDirFsDevice on / path for Btrfs - Fix kubernetes issue #94335

---

fs/fs.go
fs/fs_test.go

Backport pick fixes from https://github.com/google/cadvisor/pull/2752
(Fix https://github.com/kubernetes/kubernetes/issues/94335)

Cherrypick to v0.38: Return correct DeviceInfo from GetDirFsDevice on / path for Btrfs - Fix kubernetes issue #94335

---

README.md
docs/running.md

Updated README.md to include a docker run command that works on a redhat docker host.
Running the container on a Redhat docker host was throwing and oci error. The comments in the github issue #2155 suggested a slightly different docker command that worked when it was executed on an RHEL7 docker host.

Command to run container on a RHEL docker host

---

utils/sysinfo/sysinfo.go
utils/sysinfo/sysinfo_test.go

Fix incorrect CPU topology on single NUMA and multi socket platform.

---

container/libcontainer/handler.go
container/libcontainer/handler_test.go

sched_getaffinity does not return number of online CPUs

---

deploy/Dockerfile
docs/development/build.md

This PR adds libipmctl to the docker image.

Add libipmctl to the docker image.

---

container/libcontainer/handler.go
container/libcontainer/handler_test.go
utils/sysinfo/sysinfo.go
utils/sysinfo/sysinfo_test.go

Porting of recent fixes applied to master.

Porting fixes to #2792 and #2798 to v0.37

---

utils/sysfs/sysfs.go

Values in Power OF device-tree are null-terminated. For example:
```
$ sudo od -t cx1 /proc/device-tree/system-id
0000000   I   B   M   ,   0   6   7   8   B   2   3   0   0  \0
49  42  4d  2c  30  36  37  38  42  32  33  30  30  00
```
The null character needs to be trimmed or otherwise it will be part of the Go string.
This is causing problems with node attribute `systemUUID` in Kubernetes/OpenShift clusters for ppc64le nodes:
```
...
nodeInfo:
architecture: ppc64le
bootID: dab6f6ac-7d18-4411-9b87-9bd990752071
containerRuntimeVersion: cri-o://1.19.1-7.rhaos4.6.git6377f68.el8
kernelVersion: 4.18.0-193.41.1.el8_2.ppc64le
kubeProxyVersion: v1.19.0+1833054
kubeletVersion: v1.19.0+1833054
machineID: 5884c39c43a843d78f6051c8485e376a
operatingSystem: linux
osImage: Red Hat Enterprise Linux …
```

Remove trailing \0 from values read from ppc64le device-tree.

---

utils/oomparser/oomparser.go
utils/oomparser/oomparser_test.go

#2418 introduced new regex for 5.0 kernels and higher, the regex had a typo and wasn't resolving the correct container names.
Fixes: https://github.com/google/cadvisor/issues/2813

Fix oomparser regex for kernels 5.0 and higher

---

container/libcontainer/handler.go

In cgroup v2, MemoryStats.UseHierarchy has no meaning, since all
resources are tracked as if UseHierarchy=true in v1. cgroup v2 also have
some other names for the stats.
For those interested, the mapping can be found here:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/mm/memcontrol.c#n4026

Fix memory stats for cgroup v2

---

container/libcontainer/handler.go

Some of the root stats are used by kubernetes metrics endpoints, and recent kernel versions expose a lot of the stats on the root cgroup as well.

Allow gathering of stats for root cgroup on v2

---

container/common/helpers.go

The file "cgroup.clone_children" is not a part of cgroup v2, so use
"cgroup.events" instead. This heuristic is quite bad, so also check the
cgroup directories to see.
The old metric based on this is also constantly increasing due to this, making it more or less useless:

Update heuristic for container creation time

---

cmd/cadvisor.go
cmd/cadvisor_test.go
container/factory.go
container/libcontainer/handler.go
docs/runtime_options.md
docs/storage/prometheus.md
info/v1/container.go
metrics/prometheus.go
metrics/prometheus_fake.go
metrics/testdata/prometheus_metrics

Signed-off-by: Wisniewski, Krzysztof2 <Krzysztof2.Wisniewski@intel.com>

Add cgroup_memory_migrate metric

---

cmd/cadvisor.go
cmd/cadvisor_test.go
container/factory.go
info/v1/container.go
manager/container.go
manager/manager.go
metrics/prometheus.go
metrics/testdata/prometheus_metrics

Expose OOM event count to prometheus

---

deploy/Dockerfile

Add missing python interpreter for ipmctl install in dockerfile.
```
Step 5/21 : RUN git clone -b v02.00.00.3820 https://github.com/intel/ipmctl/ &&     cd ipmctl &&     mkdir output &&     cd output &&     cmake -DRELEASE=ON -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_INSTALL_LIBDIR=/usr/local/lib .. &&     make -j all &&     make 
install                                                                                                                                                                                                                                                       
---> Running in 3738cec7fe4f …
```

Add missing python3 in Dockerfile.

---

container/common/helpers.go

and also simplify some other code to behave like cgroup v1
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

Fix read "max" value for cgroup v2

---

fs/fs.go

We can create a `*DeviceInfo` from the mount even if the `FSType` is not
`btrfs`.
Refers to: https://github.com/kubernetes/kubernetes/issues/94825
Testing in: https://github.com/kubernetes/kubernetes/pull/100451

Add support for non btrfs devices in GetDirFsDevice

---

info/v1/machine.go
machine/topology_test.go
utils/sysfs/sysfs.go
utils/sysinfo/sysinfo.go
utils/sysinfo/sysinfo_test.go

Add cache id for cache info.

---

info/v1/machine.go
machine/topology_test.go
metrics/prometheus_machine.go
utils/sysinfo/sysinfo.go
utils/sysinfo/sysinfo_test.go

In some architecture, l3 cache(or llc) is not shared among whole node but
among some cores, it is neccessary distinguish core-cache, uncore-cache, node-cache
for runtime awareness and performance impact analysis.
Signed-off-by: ranchochen <ranchochen@tencent.com>

add uncore cache in topology.

---

docs/runtime_options.md

Update `disable_metrics` parameters to latest version

fix(docs/runtime_options): Update `disable_metrics` parameters

---

container/containerd/factory.go
container/containerd/handler.go
container/containerd/handler_test.go

Currently, when using cadvisor with containerd it exposes all the environment variables for every container which can be dangerous (i.e. secret env vars in k8s) and can result in big and slow metrics responses (/metrics endpoint in our environment takes some seconds to reply and gives a >500MB body size) and high memory usage.
This PR adds the whitelisting functionality mimicking the same functionality in the docker module to keep consistency between them.

Implement containerd environment variables whitelisting

---

manager/manager.go

Fixes: https://github.com/google/cadvisor/issues/2867
Signed-off-by: Harshal Patil <harpatil@redhat.com>

Do not return the error when hitting the cache not synced issue

---

deploy/kubernetes/base/daemonset.yaml
deploy/kubernetes/overlays/examples_perf/configmap.yaml

Upgrade cAdvisor version in k8s deployment.

---

cmd/go.sum
go.mod
go.sum

**What this PR does / why we need it:**
This PR bumps the `containerd` version to v1.5.1
**Additional context**
Link to the new release: https://github.com/containerd/containerd/releases/tag/v1.5.1
Signed-off-by: Priyanka Saggu <priyankasaggu11929@gmail.com>

bump containerd version to v1.5.1

---

cmd/cadvisor.go

Adds ability to disable {memory, cpuLoad, and perf_event} metrics via --disable_metrics flag.

Allow {memory, cpuLoad, and perf_event} metrics to be disabled

---

cmd/go.sum
go.mod
go.sum

**What this PR does / why we need it:**
This PR bumps the `runc` version to `v1.0.0-rc95`
---
**Additional context**
- Link to the new release: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc95
- This release of `runc` contains a fix for [CVE-2021-30465](https://github.com/opencontainers/runc/security/advisories/GHSA-c3xm-pvg7-gh7r).
---
Signed-off-by: Priyanka Saggu <priyankasaggu11929@gmail.com>

bump runc version to v1.0.0-rc95

---

deploy/Dockerfile

Cherrypick https://github.com/google/cadvisor/pull/2832 to v0.39 to ensure `make release` continues to work on v0.39 branch.

Cherrypick Add missing python3 in Dockerfile to release-v0.39

---

fs/fs.go

The new error type `ErrDeviceNotInPartisionsMap` can be used by external
consumers like Kubernetes to distinguish certain error paths.
Refers to https://github.com/kubernetes/kubernetes/pull/100448

Add custom error type if device not found in partitions map

---

info/v2/conversion_test.go

2-letter typo fix is too small change to be copyrightable, so this "contribution" should not require CLA.

Fix typo in test function name

---

deploy/kubernetes/README.md

There is not anymore need to use a separate "kustomize" tool, one can use "kubectl".
It has supported "kustomize" command since v1.14 (released in March 2019).

Use "kubectl kustomize" instead of "kustomize build"

---

cmd/cadvisor.go

List of metric names being generated automatically also avoids it accidentally getting out of date.
PS. Eventually I would like metrics to be sorted in all the lists based on their metric names for coder convenience too. It's harder to verify whether a metric is missing from some place in the cAdvisor code when metrics are not listed in same order, and they need to be added to so places.

Sort metric names in options for readability

---

cmd/cadvisor.go
cmd/cadvisor_test.go
container/factory.go

Looking at the cAdvisor issues, it's nowadays often used to get just some specific metrics [1].  Doing that with 'disable_metrics' option is bothersome because there's such a large number of options one needs to disable, and that set can grow on cAdvisor updates.
Doing that by specifying only metrics one wants with 'enable_metrics' is easier & hopefully future-proof.
Btw. Regarding toIncludedMetrics() function, I think it would be clearer just to inline container.AllMetrics.Difference() call instead of having that wrapper function for it.  Any comments on that, and whether such change should be another PR or part of this one?
[1] Eventually it would be nice to be able to disable all cAdvisor metrics, not just the ones on ignoreWhitelist, but that belongs definitely to another PR.

Add 'enable_metrics' option

---

info/v2/container.go

The only valid options are "name" (default) or "docker", while "dockerid" and "dockeralias" fail with an 'unknown type' error.
Reference:
https://github.com/google/cadvisor/blob/20e306ab0398f00daaafeda2444b9ec157636f74/cmd/internal/api/versions.go#L531-L540

Fix documentation of RequestOptions.IdType

---

deploy/kubernetes/overlays/examples/cadvisor-args.yaml
docs/running.md
docs/runtime_options.md
docs/storage/prometheus.md

Fixes also -disable_metrics 'process' metric name in running.md, and updates list of '-disable_metrics' option metrics.
Note: I've followed the existing documentation convention of giving cAdvisor option names with two dashes (--enable_metrics) although current cAdvisor uses only one dash (-enable_metrics).

Add '-enable_metrics' option to docs / examples

---

cmd/cadvisor.go
manager/manager.go

As per the discussion https://github.com/google/cadvisor/pull/2920#issuecomment-902406524, this PR refactors `max_housekeeping_interval` to move it from `cmd` package to `manager` package so that along with the command line kubelet can also override it. 
Potential users of this refactor - https://github.com/kubernetes/kubernetes/pull/104339 
I have tested this refactoring with cadvisor command, 
```bash
[harshal@localhost cadvisor]$ ./cadvisor -h 
Usage of ./cadvisor:
</snip>
-max_housekeeping_interval duration
Largest interval to allow between container housekeepings (default 1m0s)
</snip>
```
So this isn't breaking existing flag. 
Plus it works with kubelet too,
```bash
[harshal@localhost kubernetes]$ _output/bin/kubelet -h | grep max-house
--max-housekeeping-interval duration …
```

Refactor max_housekeeping_interval to move in manager package

---

build/integration.sh
container/libcontainer/helpers.go
manager/manager.go

Fix cAdvisor constantly polls data that has been disabled 

---

container/containerd/client_test.go
container/containerd/handler.go
container/containerd/handler_test.go

Signed-off-by: Qiutong Song <songqt01@gmail.com>
Previous PR: https://github.com/google/cadvisor/pull/2919
In Prometheus and Statsd, they use the first container alias as the "container name" in the output metrics. However, docker handler and containerd handler have different logics for the alias.
In docker, it is `k8s_<container-name>_<pod-name>_<namespace>_<pod-uid>_<restart-count>` but it is <container id> in containerd.
This PR is to make containerd behave the same way as docker.
- For sandbox container (pause), the restart is hardcoded to "0"
```
$ go test github.com/google/cadvisor/container/containerd
$ make test
```
Query Prometheus endpont: `localhost:8080/metrics`
```
name="k8s_nginx-pod_nginx-pod_default_3842c335-15cc-4b1a-8aa2-112a1eac3f82_0" …
```

Fix the first alias of container reference

---

fs/fs.go
fs/fs_test.go

when cadvisor Initialize FS Context, docker restart or something wrong happen, context.Dokcer.Driver set to "", now default use /var/lib/docker device usage as image fs usage. if we use device mapper as storage driver,  we may get wrong image fs usage inforamation， so may be lead kubelet image gc manager to get a wrong information。

if docker can't connect during InitializeFSContext , do not add image dev info to real fs info label cache

---

cmd/go.sum
go.mod
go.sum

Matching bump in k/k - https://github.com/kubernetes/kubernetes/blob/dd5c3a109e2f156774576b7e7a38e104fa5c7202/go.mod#L202
from https://github.com/kubernetes/kubernetes/pull/104880

Bump to containerd v1.4.9

---

build/integration.sh
container/libcontainer/helpers.go

https://github.com/google/cadvisor/pull/2910 made CPU usage metrics configurable from CLI, and process metrics were that already earlier.  Prometheus code skips reporting them when they are disabled, and polling should be skipped too.
Fixes: https://github.com/google/cadvisor/issues/2932

Disable polling of CPU & PIDs cgroups when they are not needed

---

container/common/fsHandler.go
container/containerd/client.go
container/containerd/client_test.go
container/containerd/factory_test.go
container/containerd/handler.go
container/containerd/handler_test.go
container/crio/handler.go
container/docker/handler.go

Signed-off-by: Qiutong Song <songqt01@gmail.com>
File system metrics are not supported in cadvisor-containerd. This PR attempts to fix it. 
The majority of code is copied from https://github.com/google/cadvisor/pull/2872
Fixed:
```
fs_inodes_free
fs_inodes_total
fs_usage_bytes
fs_limit_bytes
```
```
$ make test
```
Query prometheus endpoint
```
$ curl localhost:8080/metrics 2>/dev/null | grep fs_usage_bytes | grep nginx
container_fs_usage_bytes{container_label_io_cri_containerd_kind="container",container_label_io_kubernetes_container_name="nginx-pod",container_label_io_kubernetes_pod_name="nginx-pod",container_label_io_kubernetes_pod_namespace="default",container_label_io_kubernetes_pod_uid="9de12299-f7c6-4404-8483-b40636023b5e",container_label_k8s_app="",container_label_pod_template_hash= …
```

Add missing file system metrics in containerd handler

---

build/release.sh

To support tags like `v0.41.0-rc.1`.

Support git tag with `rc` when doing releases

---

container/containerd/handler.go

Signed-off-by: Qiutong Song <songqt01@gmail.com>
Previous commit has a bug of checking wrong path. The problem was the path should be prepended with rootfs if cadvisor runs within container.
```
Failed to create existing container: /kubepods/besteffort/pod3fd5ec35-da3b-4174-8cb6-d710b7c483b3/ffd567befc2a43b587af98008130f195fb6f0693e8807e93df085252e3576369: stat failed on /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/177/fs with error: no such file or directory
```
```
make build
make test
```
```
make release
VERSION=v0.36.0 # use the latest release version from https://github.com/google/cadvisor/releases
sudo docker run \
--volume=/:/rootfs:ro \
--volume=/var/run:/var/run:ro \
--volume=/sys:/sys:ro \
--volume=/var/lib/docker/:/var/lib/docker:ro \ …
```

Prepend rootfs to the paths in containerd handler

---

container/containerd/client_test.go
container/containerd/factory_test.go
container/containerd/handler.go
container/containerd/handler_test.go

1. Refactor disk usage collection code so that any error will not fail the handler creation `newContainerdContainerHandler`.
2. Add more unit tests

Refactor disk usage code in containerd handler

---

container/crio/factory.go

In Openshift we are [seeing](https://bugzilla.redhat.com/show_bug.cgi?id=1978528#c4) systemd components get added to housekeeping within the Kubelet using crio. This patch filters the `system-systemd` namespace for containers.
cc @harche

crio: filter out systemd related components

---

container/libcontainer/handler.go

Since runsc v1.0.0-rc94 `stats.MemoryStats.SwapUsage` on cgroupv2 includes memory usage:
* https://github.com/opencontainers/runc/commit/b99ca25ad0f
This results in wrong metrics:
```
container_memory_rss{id="/system.slice/qs-dnsv2.service"} 9.173716992e+09 1635890983582
container_memory_swap{id="/system.slice/qs-dnsv2.service"} 1.249011712e+10 1635890983582
container_memory_usage_bytes{id="/system.slice/qs-dnsv2.service"} 1.249011712e+10 1635890983582
```
Here my service dosn't have any swapped pages, yet it reports all memory as swapped.

cgroupv2: fix swap accounting

---

container/common/helpers.go
container/common/helpers_test.go

Path lookups fail in the cgroups v2 cgroupPaths map (common/helpers.go, getSpecInternal) that only has key "" and some metrics are missing (cpu cfs related ones, for instance).

Fix missing metrics on cgroups v2

---

container/containerd/client.go
container/containerd/client_test.go
container/containerd/containers/containers.go
container/containerd/errdefs/errors.go
container/containerd/errdefs/grpc.go
container/containerd/errdefs/grpc_test.go
container/containerd/factory_test.go
container/containerd/grpc.go
container/containerd/handler.go
container/containerd/handler_test.go
container/containerd/identifiers/validate.go
container/containerd/identifiers/validate_test.go
container/containerd/namespaces/context.go
container/containerd/namespaces/context_test.go
container/containerd/namespaces/grpc.go
container/containerd/namespaces/store.go
container/containerd/namespaces/ttrpc.go
container/containerd/namespaces/ttrpc_test.go
container/containerd/pkg/dialer/dialer.go
container/containerd/pkg/dialer/dialer_unix.go
container/containerd/pkg/dialer/dialer_windows.go
go.mod

When cadvisor vendors in things from containerd, there is a dependency loop between cadvisor<->containerd<->kubernetes as containerd vendors in cri-api. So we have been unable to move to newer versions of containerd that use go modules. To help with this effort in 1.6, containerd folks will publish `containerd/containerd/api` as a separate go module. To prep for this, we can cleanup our usage of containerd now to depend only on the code under `containerd/containerd/api` by borrowing some code from containerd repository that essentially acts as a containerd client. 
When containerd 1.6 goes GA, we can switch over to the new `containerd/api` go module. Kubernetes also needs https://github.com/moby/moby/pull/42624 from moby/moby to completely eliminate this dependency loop unless/until we …

Depend only on containerd API and avoid vendoring unnecessary things from containerd

---

deploy/kubernetes/README.md

Update cadvisor daemonset doc to customize the image version.

Update cadvisor daemonset doc to customize the image version

---

cmd/go.sum
go.mod
go.sum

`make build` passing. This pulls in the fix for https://github.com/containerd/containerd/security/advisories/GHSA-5j5w-g665-5m35
Similar PR to: https://github.com/google/cadvisor/pull/2952
(This is my first PR to this repo, so happy to update / modify anything I may have missed)

Bump containerd to v1.4.12

---

manager/container.go

xref: https://github.com/kubernetes/kubernetes/issues/106977
prevent panic on atomic operations

fix: atomic operations on 32-byte device

---

cmd/go.sum
go.mod
go.sum

Don't think we end up using the code ... but still good thing to keep up with the jones'es. containerd updated it as well here - https://github.com/containerd/containerd/blob/main/script/setup/runc-version
Also the same for image-spec to v1.0.2
- https://github.com/advisories/GHSA-v95c-p5hm-xq8f
- https://github.com/advisories/GHSA-77vh-xpmg-72qh

Upgrade github.com/opencontainers/runc to version 1.0.3

---

cmd/go.mod
cmd/go.sum
go.mod
go.sum

cadvisor has memory leak: cadvisor watch all cgroup director. when file or directory delete, inotify will recevie IN_DELETE event, when cadvisor recevie IN_DELETE, cadvisor will call inotify RemoveWatch to remove watch descriptor. When watch descriptor delete before function called, function will return EINVAL, may lead this path remain in watches and paths map, and also not delete path in containersWatched, finally lead to memory leak
update k/utils repo to fixs inotify memory leak.
fixs [#100241](https://github.com/kubernetes/kubernetes/issues/100241)

Bump k/utils to v0.0.0-20211116205334-6203023598ed

---

cmd/go.mod
cmd/go.sum
go.mod
go.sum

Hey, long time, no see.
This is an RFC to some extent: go 1.13 is not supported since 1.15 (August 2020). Should we still indicated 1.13 as minimum required golang version? I don't think so:
* there has been bunch of CVEs published since 08/2020
* I think it's good idea to force users to use supported compiler version
@bobbypage, what do you think? Kubernetes requires 1.16 since [March 2021](https://github.com/kubernetes/kubernetes/commit/3c2824e3dbed6069dabddac7816239de9cb2a6ee).

Bumping up minimum version of go to a supported version

---

container/common/helpers.go
container/libcontainer/handler.go

This PR fixes #3026 to use a unified root path to collect process stats from procs if cadvisor is running in cgroup v2.
Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>

Fix process metrics collection in cgroup v2

---

manager/manager.go

I found that on cgroup v1 `selfContainer` was not being determined correctly, due to two issues, both of which this PR fixes.

manager: fix determining selfContainer name

---

fs/fs.go
fs/types.go

This allows using the error type on non Linux systems as well.

Move `ErrDeviceNotInPartitionsMap` outside of the build constraints

---

cmd/go.sum
go.mod
go.sum

Brought to you by
go get -d github.com/opencontainers/runc@latest
go mod tidy
cd cmd
go get -d github.com/opencontainers/runc@latest
go mod tidy

vendor: bump runc to 1.1.0

---

deploy/Dockerfile

Go version changed in #3046.
It should be also changed in the dockerfile.
This fixes:
```
build github.com/google/cadvisor/cmd: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
The command '/bin/sh -c ./build/build.sh' returned a non-zero code: 1
make: *** [Makefile:79: docker-%] Error 1
```
when building a docker image.
@iwankgb @bobbypage 

dockerfile: Use the same Go version.

---

deploy/Dockerfile
deploy/Dockerfile.ppc64le

One of our security tools is reporting that the version of Alpine upon which the `cadvisor` image is built is reaching EOL soon (see [here](https://endoflife.date/alpine) for details). This PR just bumps the minor version. Unfortunately Alpine doesn't follow SemVer so there's no guarantees around minor version bumps but nothing in the subsequent release notes seems to indicate any issue with how `cadvisor` runs so it ought to be fine.

Update Alpine base image

---

cmd/internal/api/versions.go
info/v2/container.go

The underlying code already knows how to consume count=-1 when fetching
all data points. This patch allows the server to accept such a value
from the client and pass it through.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
cc @mrunalp

api/v2: document and consume count=-1

---

container/containerd/client.go
container/containerd/handler.go

In some cases, it appears that containerd task api can return a zero pid
when the task is not ready yet. In these cases, the process task state
is reported to be in unknown state. In this case, we should retry the
containerd task api request as the task can take some time to move away
from unknown state and be initialized.

Retry containerd task api request when task is in unknown state

---

container/containerd/client.go
container/containerd/handler.go

In some cases, it appears that containerd task api can return a zero pid
when the task is not ready yet. In these cases, the process task state
is reported to be in unknown state. In this case, we should retry the
containerd task api request as the task can take some time to move away
from unknown state and be initialized.

(cherrypick to release 0.44) Retry containerd task api request when task is in unknown state

---

container/containerd/client.go
container/containerd/handler.go

Cherrypick https://github.com/google/cadvisor/pull/3105 to release-0.43
In some cases, it appears that containerd task api can return a zero pid
when the task is not ready yet. In these cases, the process task state
is reported to be in unknown state. In this case, we should retry the
containerd task api request as the task can take some time to move away
from unknown state and be initialized.

[Cherrypick to release-0.43] Retry containerd task api request when task is in unknown state

---

container/containerd/client.go
container/containerd/handler.go

Cherrypick https://github.com/google/cadvisor/pull/3105 to release-0.39
In some cases, it appears that containerd task api can return a zero pid
when the task is not ready yet. In these cases, the process task state
is reported to be in unknown state. In this case, we should retry the
containerd task api request as the task can take some time to move away
from unknown state and be initialized.

[Cherrypick to release-0.39]  Retry containerd task api request when task is in unknown state

---

.gitignore
Makefile
build/build.sh
build/check_container.sh
build/integration-in-docker.sh
build/integration.sh
build/release.sh
deploy/Dockerfile
deploy/Dockerfile.ppc64le
docs/development/releasing.md

I took a prototype by @bobbypage and added support for additional architectures, simplified the docker build, and  wrote a script to test the images generated by release.sh.
Note: My GCR repository is private you'll have to use your own container registry that you have permissions to.
```
VERSION=v0.44.1-test-8 IMAGE_NAME=gcr.io/tstapler-gke-dev/cadvisor make release
```
Starting each of the images and curling the healthz endpoint:
```
build/check_container.sh gcr.io/tstapler-gke-dev/cadvisor:v0.44.1-test-8
Testing that we can run gcr.io/tstapler-gke-dev/cadvisor:v0.44.1-test-8 on ppc64le and curl the /healthz endpoint
Unable to find image 'gcr.io/tstapler-gke-dev/cadvisor:v0.44.1-test-8' locally
v0.44.1-test-8: Pulling from tstapler-gke-dev/cadvisor
602896d44249: Already exists …
```

Add support for building multi-arch images

---

build/integration.sh
container/common/helpers.go
container/common/helpers_test.go
integration/tests/api/docker_test.go
integration/tests/api/machinestats_test.go
integration/tests/api/test_utils.go

Adds a few fixes to the integration tests to support running on cgroupv2. Now running `make docker-test-integration` on a cgroupv2 host should work fine.

Support running integration tests on cgroupv2 hosts

---

manager/manager.go

Remove cgroupv2 related log warning as it confused users and doesn't
provide any value.
Fixed https://github.com/google/cadvisor/issues/3121

Remove cgroupv2 log warning

---

cmd/go.sum
go.mod
go.sum

Bump runc to v1.1.3
runc diff - https://github.com/opencontainers/runc/compare/v1.1.0...v1.1.3

Bump runc to v1.1.3

---

container/crio/client.go

In the kubernetes main branch, the following exception log appears in the kubelet log
```
E0729 01:14:33.037428  170935 manager.go:1123] Failed to create existing container: /system.slice/crio-ccc008b39f6ce2e2bfa0bbda7d8873d0164a7917a4c469ad2fbb5fc50ecb98b1.scope: Error finding container ccc008b39f6ce2e2bfa0bbda7d8873d0164a7917a4c469ad2fbb5fc50ecb98b1: Status 404 returned error &{%!s(*http.body=&{0xc0025f5bd8 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x835360) %!s(func() error=0x835460)}
```
The following log information output is wrong
`return nil, fmt.Errorf("Error finding container %s: Status %d returned error %s", id, resp.StatusCode, resp.Body)`
After the update, the log information is as follows …

fix error log of crio client

---

.golangci.yml
Makefile
accelerators/nvidia.go
accelerators/nvidia_test.go
client/client.go
cmd/cadvisor.go
container/containerd/grpc.go
container/containerd/namespaces/store.go
devicemapper/dmsetup_client.go
devicemapper/fake/dmsetup_client_fake.go
devicemapper/fake/thin_ls_client_fake.go
devicemapper/thin_ls_client.go
devicemapper/thin_ls_client_test.go
devicemapper/thin_pool_watcher.go
devicemapper/thin_pool_watcher_test.go
devicemapper/util.go
integration/framework/framework.go
resctrl/utils_test.go
zfs/watcher.go

* Update to golangci 1.48.0
* Re-enable linting

Re-enable presubmit linting

---

build/build.sh
build/release.sh

This is to avoid depending on glibc which can be quite old on certain
distros. For the docker image, since glibc is part of the container,
there is no reason to disable cgo.
Fixes #3044

Disable cgo for static binaries

---

cmd/internal/container/mesos/client.go

From [mesos-go](https://github.com/mesos/mesos-go/blob/master/api/v1/lib/mesos.pb.go) ContainerStatus spec ExecutorPID can be null with *uint32.
This will cause nil pointer panic from line [L111](https://github.com/google/cadvisor/blob/24e7a9883d12f944fd4403861707f4bafcaf4f3d/cmd/internal/container/mesos/client.go#L111)
```go
// *
// Container related information that is resolved during container
// setup. The information is sent back to the framework as part of the
// TaskStatus message.
type ContainerStatus struct {
ContainerID *ContainerID `protobuf:"bytes,4,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
// This field can be reliably used to identify the container IP address.
NetworkInfos []NetworkInfo `protobuf:"bytes,1,rep,name=network_infos,json=networkInfos" …
```

fix mesos client panic while ExecutorPID is nill

---

deploy/Dockerfile

Typo in go build tags in the Dockerfile leads to cAdvisor images without perf support.
Versions v0.45.0, v0.46.0, and v0.47.0 are affected.

dockerfile: Fix typo in go build tags.

---

deploy/Dockerfile

Reverts google/cadvisor#3237
This is breaking the release build:
```
$ make release
...
#19 [build 12/12] RUN export GO_TAGS="--tags=libpfm,netgo";     if [ "$(uname --machine)" = "x86_64" ]; then           export GO_TAGS="$GO_TAGS,libipmctl";     fi;     GO_FLAGS="$GO_TAGS" ./build/build.sh
#19 1.443 >> building cadvisor
#19 73.36 # github.com/google/cadvisor/perf
#19 73.36 ../perf/collector_libpfm.go:256:34: cannot use _Ctype_ulong(unsafe.Sizeof(unix.PerfEventAttr{})) (constant 128 of type _Ctype_ulong) as type _Ctype_uint in argument to (_Cfunc__CMalloc)
#19 73.36 ../perf/collector_libpfm.go:258:61: cannot use _Ctype_ulong(unsafe.Sizeof(unix.PerfEventAttr{})) (constant 128 of type _Ctype_ulong) as type _Ctype_uint in variable declaration
#19 73.36 ../perf/collector_libpfm.go:271:15: …
```

Revert "dockerfile: Fix typo in go build tags."

---

resctrl/utils.go
resctrl/utils_test.go

Fix https://github.com/google/cadvisor/issues/3263
In the resctrl file system, there will be automatically created mode and size files, so we can remove the useless check for them in the `findGroup` function.

reduce useless check in resctrl file system

---

utils/sysinfo/sysinfo.go
utils/sysinfo/sysinfo_test.go

add nerdctl to ignoredDevices

---

nvm/machine_libipmctl.go

Official cAdvisor image is built with the `libimpmctl` flag. This causes trying to gather information about non-volatile memory modules.
This log confuses users. It's verbosity should be decreased.
Fixes #3241

nvm: Decrease the "no nvm devices" warning log.

---

utils/sysinfo/sysinfo.go

feat(logging): add verbosity to non-NUMA node warning

---

container/containerd/client.go

Set containerd grpc.MaxCallRecvMsgSize to 16MB

---

container/crio/handler.go

When using CRI-O as the container runtime, the infrastructure container can be dropped. In this scenario, CRI-O provides cadvisor with the process ID (PID) of one of the containers within the pod to collect network statistics. However, if the particular container exits, cadvisor is left with an invalid PID. To address this issue, this PR makes cadvisor to switch to another PID from the same pod, ensuring the continuous collection of network statistics. 
Pod used to validate this change, 
```yaml 
apiVersion: v1
kind: Pod
metadata:
name: init-sleep-pod
spec:
initContainers:
- name: init-sleep
image: busybox
command: ["sh", "-c", "sleep 60"]
containers:
- name: forever-sleep
image: busybox
command: ["sh", "-c", "while true; do sleep 1; done"]
```

Request the pid of another container if current pid is not longer valid

---

container/crio/handler.go

This PR backports the changes from https://github.com/google/cadvisor/pull/3301 to 0.47

[0.47] Backport of PR 3301 to 0.47

---

info/v1/machine.go
info/v1/machine_test.go

This PR fixes a small bug in MachineInfo's Clone() method.
Today, `SwapCapacity` is not being cloned, therefore after cloning it is being set to 0.

Bugfix: MachineInfo Clone() to also clone "SwapCapacity"

---

container/common/helpers.go
container/common/helpers_test.go
container/containerd/handler.go
container/crio/handler.go
container/docker/handler.go
container/factory.go

Apparently, we collect network stats for all containers, and then discarding some or most of it:
- for docker, we collect and discard stats for containers which share netns with another container (which is rare I guess);
- for both crio and containerd, we collect and discard stats for containers that are not infra (sandbox, pod, pause) containers (which is very common).
Instead of reading and parsing a bunch of files in /proc/PID/net and when removing those, let's set things up in a way so we don't collect useless stats in the first place.
This should improve performance, memory usage, and ease the load on garbage collection.

Optimize network metrics collection

---

container/crio/handler.go

This PR backports the changes from https://github.com/google/cadvisor/pull/3301 to 0.46

[0.46] Backport of PR 3301 to 0.46

---

cmd/go.mod
cmd/go.sum
container/docker/factory.go
go.mod
go.sum

This is the first version to be fully go-mod-compatible.
Signed-off-by: Stephen Kitt <skitt@redhat.com>

Upgrade to blang/semver/v4 v4.0.0

---

cmd/cadvisor.go

Some developers prefer to write lists by adding spaces after commas, so add handling of spaces to increase code robustness

fix: add space trimming for label allowlist

---

docs/storage/prometheus.md
metrics/prometheus_machine.go
metrics/testdata/prometheus_machine_metrics

While for memory there are metrics for both current consumption (`container_memory_usage_bytes`) and total machine capacity (`machine_memory_bytes`), for swap memory the only supported metric is for current consumption (`container_memory_swap`).
This PR adds the missing piece by adding `machine_swap_bytes` metric that would be helpful to monitor the total amount of swap memory available on the machine.

Add a metric for machine swap capacity

---

deploy/kubernetes/README.md

This PR makes installation process much easier for fresh users by taking advantage of Kustomize remote build. So no one need to have clone the repo.

docs(deploy/k8s): remote build for kustomize

---

container/libcontainer/handler.go
info/v1/container.go
info/v1/test/datagen.go
metrics/prometheus.go
metrics/prometheus_fake.go
metrics/testdata/prometheus_metrics
metrics/testdata/prometheus_metrics_whitelist_filtered

Pick up the PR: https://github.com/google/cadvisor/pull/2302
Fixes: https://github.com/google/cadvisor/issues/2138
>Through prometheus testing the following relationship seems to be present:
container_memory_usage_bytes == container_memory_rss + container_memory_cache + container_memory_kernel
please review @dashpole 
Thanks

export-memory-kernal-usage

---

perf/collector_libpfm.go

We should use C.free after using C.CString in cgo, and fix a typo issue.

fix: fix cgo memory leak&fix typo issue

---

fs/fs.go
fs/types.go

One NFS is mounted to multiple Pods and statistics are requested only once.
fix #3349

fix performance degradation of NFS

---

container/raw/watcher.go
manager/manager.go

Only setup inotify watch for included metrics
fix https://github.com/google/cadvisor/issues/3353
Before the change, number of container is 190+ , and number of inotify watch is 4800+
After this change, the number of inotify watch is 2052

reduce inotify watch

---

fs/fs.go

after #3351, we find there are still many requests for nfs stats in some case.
through analysis and debugging, we found the FileExists function will cause manay unnecessary requests.
so we suggesst remove the check for the existence of NFS files and that reduced requests to nas significantly.
fix #3349 
fix #3351

remove the check for the existence of NFS files

---

utils/sysfs/fakesysfs/fake.go
utils/sysfs/sysfs.go
utils/sysinfo/sysinfo.go

Some devices are "hidden" from userspace due to various reasons. One reason is native nvme multipathing, where the path devices do not present a device node to the user but only exposes the stacking device as the only nvme device. Still there are sysfs attributes for these hidden devices, but we should ignore them altogether because these are not "real" devices at all.

sysinfo: Ignore "hidden" sysfs device entries

---

cmd/go.mod
cmd/go.sum
go.mod
go.sum

to fix an issue with cgroupv2 memory accounting not being accurate

vendor: bump runc to 1.1.9

---

container/libcontainer/handler.go
container/libcontainer/handler_test.go
container/libcontainer/testdata/limits

Only max open files is ever parsed from limits files, therefore this
change optimizes for that case.
Benchmark:
```
$ benchstat old.txt new.txt
goos: linux
goarch: amd64
pkg: github.com/google/cadvisor/container/libcontainer
cpu: AMD Ryzen 5 3400GE with Radeon Vega Graphics
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
ProcessLimitsFile-8   85.012µ ± 1%   1.324µ ± 0%  -98.44% (p=0.000 n=10)
```
On a GKE v1.27.4 production cluster, this code path used roughly 1.5% of
the total kubelet CPU usage, and at 98.44% improvement this likely
results in at least a 1.5% CPU reduction (perhaps even more since also
less garbage is produced to be collected by the GC).
This change came out of a live stream that we do on a weekly basis trying …

container/libcontainer: Improve limits file parsing perf 

---

cmd/cadvisor.go

This seems to be related to a change in the klog library where the "v" flag isn't defined until after InitFlags() is called. Defer the call of setting the default verbosity until after we do that instead of during init(). Fixes startup:
$ GO_FLAGS=-trimpath build/build.sh && _output/cadvisor -logtostderr
>> building cadvisor
go: downloading github.com/prometheus/common v0.38.0
panic: flag v set at github.com/google/cadvisor/cmd/cadvisor.go:105 before being defined
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00017a150, {0x1874460, 0x2213bc8}, {0x1866490, 0x1}, {0x15f0596, 0x22})
flag/flag.go:1031 +0x33a
k8s.io/klog/v2.InitFlags.func1(0xc0001ab2f0?)
k8s.io/klog/v2@v2.80.1/klog.go:439 +0x31
flag.(*FlagSet).VisitAll(0xc00032fa50?, 0xc0005e1c90)
flag/flag.go:458 +0x42 …

Go 1.21 compatibility: Set verbosity after flag definition

---

nvm/machine_libipmctl.go

No NVM devices: information should be logged on increased verbosity only

---

manager/manager.go

This PR increases the required verbosity level for logging container stats info misses such as:
```
manager.go:694] Error getting data for container / because of race condition
```
When not scrapping root container metrics (using `-disable_root_cgroup_stats`), the above log message is repeated for every metrics scrape request. The error in this case is expected due to to the container stats info not having stats for `/`.
Fixes #3407 
Similar to #3341

manager: require higher verbosity level for container info misses

---

container/factory.go

Adjust the log level of Initialize Plugins to make it easier for users to analyze the registration status of Plugins.
Now the default log level of plugin register failure is 5. When plugin register fails, the error info cannot be recorded from the logs, and the issue cannot be analyzed.

Adjust the log level of Initialize Plugins

---

container/common/helpers.go
container/common/helpers_test.go

Inspired by profile data from @brancz at https://pprof.me/5dfadaf/ and confirmed via `strace`. On cgroup v1 systems about half of Stat calls turn out to be for files within paths that don't exist.
I have also added very basic benchmarks for getSpecInternal.

container: skip checking for files in non-existent directories.

---

manager/manager.go

Doing this drags in all sorts of dependencies into kubernetes which we do not need or want.
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
new file:   LICENSES/vendor/github.com/docker/distribution/LICENSE
new file:   LICENSES/vendor/github.com/docker/docker/LICENSE
new file:   LICENSES/vendor/github.com/docker/go-connections/LICENSE
new file:   LICENSES/vendor/github.com/opencontainers/image-spec/LICENSE
modified:   go.mod
modified:   go.sum
new file:   vendor/github.com/docker/distribution/LICENSE
new file:   vendor/github.com/docker/distribution/digestset/set.go
new file:   vendor/github.com/docker/distribution/reference/helpers.go
new file: …
```

Avoid using container/podman in manager.go

---

container/crio/client.go
container/crio/plugin.go
fs/fs.go
fs/fs_test.go
fs/types.go

https://github.com/kubernetes/enhancements/issues/4191
We are working on splitting the image disk and we realize that some upstream changes are needed in cadvisor in order to account for crio splitting the containers between a read-only and writeable layer.  
This is only mergeable once the K8s KEP is approved and the CRIO changes are merged.  
Pre Reqs:
- [CRIO](https://github.com/cri-o/cri-o/pull/7401)
- [KEP-PR](https://github.com/kubernetes/enhancements/pull/4198)
- [k8s/k8s](https://github.com/kubernetes/kubernetes/pull/120616)
Note we vendored these cadisvor changes in the k8s/k8s PR to test this idea out.

allow for cadvisor to detect disk stats when the read-only and writeable layers are on separate disks.

---

container/crio/factory.go
container/crio/factory_test.go

fix #3456
when We found that these logs are related to crio sandbox containers. The root cause is that when a pod is created, there will be a sandbox container folder in the cgroup file. When cadvisor scans the cgroup directory to identify containers, it recognizes the sandbox container. It then uses CanHandleAndAccept to determine that it needs to retrieve container information from crio using the id parameter. However, when attempting to get container information from crio via grpc, crio does not query the sandbox container, resulting in a 404 error(https://github.com/cri-o/cri-o/blob/main/server/inspect.go#L68). so cadvisor **createContainer** failed and print the logs periodically(https://github.com/google/cadvisor/blob/master/manager/manager.go#L1116) 
We think that this situation …

Reduce kubelet logs 'Failed to create existing container' when kubelet is using crio

---

docs/running.md

The image in question (https://hub.docker.com/r/google/cadvisor-canary) has not been updated in 5 years, so this section of running.md is misleading.

Remove section about canary image

---

deploy/Dockerfile
perf/collector_libpfm.go

See https://github.com/google/cadvisor/issues/3482 for more context
Built on top of https://github.com/google/cadvisor/pull/3480

Bump to alpine 3.18 and disable libipmctl

---

build/check_container.sh
build/release.sh

We can't build with s390x now due to missing package (thin-provisioning-tools)
```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/s390x/APKINDEX.tar.gz
ERROR: unable to select packages:
thin-provisioning-tools (no such package):
required by: world[thin-provisioning-tools]
```

Remove s390x support

---

build/check_container.sh
build/release.sh

Cherrypick https://github.com/google/cadvisor/pull/3485
We can't build with s390x now due to missing package (thin-provisioning-tools)
```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/s390x/APKINDEX.tar.gz
ERROR: unable to select packages:
thin-provisioning-tools (no such package):
required by: world[thin-provisioning-tools]
```

Cherrpick #3485 to release-v0.49- Remove s390x support

---

build/release.sh

This is causing failure to combine the multi-arch images. See https://github.com/docker/buildx/issues/1509 for discussion

build docker - add --provenance=false flag

---

README.md

The release version number for the quick start code snippet should be updated as this version won't work on most recent Linux distributions due to cgroups updates.

Update version number in README.md quick start example

---

docs/runtime_options.md

These were accidentally added in #3458.
cc @mythi

Remove non-existent psi_avg and psi_total from the docs

---

.github/workflows/test.yml
build/config/libipmctl.sh
build/integration-in-docker.sh

Fixing images: 
* Using community one instead of Google one.
* Using Debian Bookworm Go image
* Upgrading `libipmctl4` to `libipmctl5`
* Using Ubuntu 22.04 GH runners

Using bookworm images

---

cmd/go.mod
cmd/go.sum
go.mod
go.sum

27.0.0 was withdrawn, see https://github.com/moby/moby/issues/47980
cadvisor can’t currently be built except on systems that have 27.0.0 in their cache. The tag was created by mistake instead of an RC tag.

Revert to docker/docker 26.1.4

---

info/v1/container.go

Hi, this commit only modify the code comments without making any logical changes.

doc: fix TCPRcvCollapsed comment

---

integration/framework/framework.go

```
{
"Repository": "registry.k8s.io/busybox",
"Tags": [
"1.24",
"1.27",
"1.27.2",
"latest"
]
}
Using default tag: latest
latest: Pulling from busybox
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of registry.k8s.io/busybox:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
$ docker pull registry.k8s.io/busybox:1.27
1.27: Pulling from busybox
Digest: sha256:545e6a6310a27636260920bc07b994a299b6708a1b26910cfefd335fdfb60d2b
Status: Image is up to date for registry.k8s.io/busybox:1.27
registry.k8s.io/busybox:1.27
```

CI: update busybox image to fix CI

---

container/podman/podman.go

This exposes the Podman version and it's Docker API version. The fields were there, but they were always showing "Unknown".
This is how it looks after the patch:

Expose Podman version info

---

build/check_container.sh
build/release.sh

thin-provisioning-tools package is now available in Alpine Linux. We have tested and added it in latest, 3.19 and 3.18 releases.

Add s390x support again 

---

cmd/internal/storage/bigquery/bigquery.go
cmd/internal/storage/influxdb/influxdb.go
cmd/internal/storage/influxdb/influxdb_test.go
cmd/internal/storage/statsd/statsd.go
cmd/internal/storage/stdout/stdout.go
container/libcontainer/handler.go
info/v1/container.go
info/v2/conversion_test.go
integration/tests/api/test_utils.go
metrics/prometheus.go
metrics/prometheus_fake.go
metrics/testdata/prometheus_metrics
metrics/testdata/prometheus_metrics_whitelist_filtered

The goal of this PR is to have additional cAdvisor metrics which
expose total_active_file and total_inactive_file.
Today working_set_bytes subtracts total_inactive_file in its calculation,
but there are situations where exposing these metrics directly is valuable.
For example, two containers sharing files in an emptyDir increases total_active_file over time. This is not tracked in the working_set memory.
Exposing total_active_file and total_inactive_file to the user
allows them to subtract out total_active_file or total_inactive_file
if they so choose in their alerts.
In the case of prometheus with a thanos sidecar, working_set can give
a false sense of high memory usage. The kernel counts thanos reading prometheus written files as "active_file" memory.
In that situation, a user may want …

feat: add metrics for total_active_file and total_inactive_file memory

---

info/v1/container.go
manager/container.go
metrics/prometheus.go
metrics/prometheus_fake.go
metrics/testdata/prometheus_metrics
metrics/testdata/prometheus_metrics_whitelist_filtered

Currently container_cpu_load_average_10s only trace running tasks, we need uninterruptible metric to find out offline load too. Here I add a metric named load.d
see https://github.com/torvalds/linux/blob/master/kernel/cgroup/cgroup-v1.c#L724C1-L743C3

Add uninterruptible metric load d

---

container/crio/factory.go
container/crio/factory_test.go

This reverts commit b407dcd7447be18a4e83c1fa4973469dacc32572.
Fixes #3538
There may be a better way by detecting if cgroups are managed by systemd, but I have not enough knowledge of cadvisor, and not much time. So, the easy way out is to revert the commit causing the problem.
Further, I don't even know how to test it. I use K8s with cri-o, but cadvisor is vendored in K8s, so I don't know how to make K8s use this branch (I know howto build and test K8s from master though)

Revert "reduce_logs_for_kubelet_use_crio"

---

container/podman/factory.go

We ran into the same issue as #3464, but adding the check against `cntr.State` was insufficient to prevent the nil ptr panic.
The `ContainerJSON` type returned by `InspectContainer` embeds a ptr to `ContainerJSONBase`, and it seemed this ptr was nil in the return, leading cadvisor to crash loop on startup.
I haven't looked into the specific JSON response podman is returning to trigger this, so there's potentially a bug in the podman API itself where it returned a nil error and an empty payload in response to the inspect call.
I do see the podman daemon returning 500 error codes for some inspect queries, and it appears `validateResponse` (container/podman/podman.go:41) doesn't handle 5xx status codes? so that may be the underlying issue here - podman returns a 5xx and empty body, and the …

address another nil ptr check in podmanFactory.CanHandleAndAccept()

---

utils/sysfs/sysfs.go

The hidden file might have an endline, so the check for equals to 1 would not be true. Trimming the spaces would help to cover this case.

sysfs: trim spaces in device hidden check

---

build/prow_e2e.sh

Linting is failing in prow CI jobs. We should not be running linters in periodic CI jobs, 
By definition in Makefile, `all` is defined as:
```
all: presubmit build test
```
Since linters SHOULD be run in presubmits, let's skip them in https://testgrid.k8s.io/sig-node-cadvisor#cadvisor-e2e by limiting the targets to `build test`

Avoid linting in Prow CI jobs

---

cmd/go.mod
cmd/go.sum
go.mod
go.sum

There is a tag, can we please switch to it. newer https://github.com/opencontainers/image-spec/releases/tag/v1.1.1
related to some longer term cleanup we identified in https://github.com/kubernetes/kubernetes/issues/128572#issuecomment-2457145817. things need to land here, then back into kubernetes.

Bump to newer opencontainers/image-spec @ v1.1.1

---

container/containerd/factory.go

fix: #3671 
add timeout context for containerd factory during starting process.

fix potential hang on containerd client.LoadContainer

---

.github/workflows/publish-container.yml

Let us try to use ghcr.io for container images

---

.github/workflows/release-binaries.yml

use qemu/docker to build arch specific binaries
